// Structured PAL4 reconstruction for M05.csb
// Only simple if / if-else candidates backed by CFG evidence are folded.

void M05_1_init()
{
    giTimeScript(180.0, "func9001");
    if (global_mvar < 90100 /* 第二章 / 5-3-3.三寒器 / 前往即墨 / 三件寒器 */)
    {
        giSetObjectVisible("entrance3", true);
        giSetObjectVisible("entrance2", false);
        giArenaReadyRestore();
    }
    else
    {
        giSetObjectVisible("entrance2", true);
        giSetObjectVisible("entrance3", false);
        giArenaReadyRestore();
    }
    if (global_mvar >= 40401)
    {
        giSetObjectVisible("MO001", false);
        giSetObjectVisible("MO002", true);
        giArenaReadyRestore();
    }
    if (global_mvar >= 40400 /* 进入王陵 */)
    {
        giSetNpcVisible("MN003", false);
        giSetNpcVisible("MN004", false);
        giArenaReadyRestore();
    }
    if (global_mvar < 40401)
    {
        giSetObjectVisible("entrance4", false);
        giArenaReadyRestore();
    }
    if (global_mvar > 40500 /* 第一章 / 3-2-1.风水惊变 / 向北前行 */)
    {
        giArenaReadyRestore();
    }
    else
    {
        giScriptMusicStop(0, 2.5);
        giArenaReadyRestore();
    }
    func2001();
    func2002();
}

void EarthBall()
{
    giPlayerLock();
    giFlashOutBlack(1.0, true, true);
    giPlayerCurrentSetPos(1525.3, -281.5, 1837.6);
    giPlayerCurrentSetAng(192.0);
    giCameraSetMode(0, true);
    giFlashInBlack(1.0, true);
    giArenaReady();
    giPlayerUnLock();
}

void func1001()
{
    giArenaLoad("M06", "1", "1a", true);
    giPlayerCurrentSetPos(217.0, 0.0, 787.0);
    giPlayerCurrentSetAng(145.0);
    giCameraSetMode(5, true);
    giArenaReady();
}

void func1002()
{
    giArenaLoad("M07", "1", "", true);
    giPlayerCurrentSetPos(-377.6, 0.9, 1262.4);
    giPlayerCurrentSetAng(90.0);
    giCameraSetMode(5, true);
    giArenaReady();
}

void func1003()
{
    int select_dialog_last_select = 0;
    int leader_player_id = 0;

    if (global_mvar < 90100 /* 第二章 / 5-3-3.三寒器 / 前往即墨 / 三件寒器 */)
    {
        giArenaLoad("Q03", "Q03S", "", true);
        giPlayerCurrentSetPos(2.9, -13.3, -3285.2);
        giPlayerCurrentSetAng(356.0);
        giCameraSetMode(0, true);
        giArenaReady();
    }
    else
    {
        giMonsterStopPursuit();
        giPlayerLock();
        giSelectDialogAddItem("1.去寿阳城  ");
        giSelectDialogAddItem("2.御剑飞行  ");
        giSelectDialogAddItem("3.什么都不做");
        giSelectDialogSetDefaultSelect(2);
        giShowSelectDialog("   准备<colour red=255 green=102 blue=0 alpha=255>去寿阳城</colour><dc0>还是</dc0><colour red=255 green=102 blue=0 alpha=255>御剑飞行</colour><dc0>？</dc0>");
        select_dialog_last_select = giSelectDialogGetLastSelect();
        if (select_dialog_last_select != 0)
        {
            if (select_dialog_last_select != 1)
            {
                leader_player_id = giPlayerGetLeader();
                giPlayerWalkTo(leader_player_id, 1585.3, -263.5, 1991.6, true);
                giPlayerSetDir(leader_player_id, 184.0, true);
                giCameraAutoSeek(true);
                giCameraSetMode(0, true);
                giPlayerUnLock();
            }
            else
            {
                giShowWorldMap();
            }
        }
        else
        {
            giArenaLoad("Q03", "Q03S", "", true);
            giPlayerCurrentSetPos(2.9, -13.3, -3285.2);
            giPlayerCurrentSetAng(356.0);
            giCameraSetMode(0, true);
            giArenaReady();
        }
        giPlayerUnLock();
    }
}

void func1004()
{
    int leader_player_id = 0;

    giMonsterStopPursuit();
    giPlayerLock();
    giNpcPauseBeh("4001");
    giNpcFaceToCurrentPlayer("4001", true);
    giCurrentPlayerFaceToNpc("4001", true);
    giTalk("卫兵丙：前方官道被山上大石阻塞！绕道、绕道！", "");
    giNpcResetDir("4001");
    giNpcResumeBeh("4001");
    leader_player_id = giPlayerGetLeader();
    giPlayerWalkTo(leader_player_id, 2566.3, -197.6, 1438.1, true);
    giPlayerSetDir(leader_player_id, 270.0, true);
    giCameraAutoSeek(true);
    giCameraSetMode(0, true);
    giPlayerUnLock();
}

void func2001()
{
    if (global_mvar == 30201 /* 第一章 / 2-5-1.女萝平妖 / 北门出城 */)
    {
        giPlayerLock();
        giTimeScriptTerminate();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerCurrentSetVisible(false);
        giIMMBegin();
        giPlayerSetPos(0, 829.1, -320.0, 282.0);
        giPlayerSetPos(1, 829.1, -320.0, 282.0);
        giPlayerSetPos(2, 829.1, -320.0, 282.0);
        giMonsterSetHide("m05-02-01", false);
        giMonsterSetHide("m05-01-02", false);
        giMonsterSetHide("m05-02-03", false);
        giSetObjectVisible("item009", false);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giAddPlayerFavor(0, 2, 10);
        giAddPlayerFavor(1, 0, -10);
        giAddPlayerFavor(1, 2, 10);
        giAddPlayerFavor(2, 0, 2);
        giAddPlayerFavor(2, 1, 2);
        giIMMEnd();
        giCameraPrepare("MC001");
        giCameraRunSingle("002", true);
        giFlashInBlack(3.5, false);
        giArenaReady();
        giPlayerWalkTo(2, 818.6, -288.9, 63.3, false);
        giWait(0.8);
        giPlayerWalkTo(1, 841.6, -294.7, 117.4, false);
        giWait(0.8);
        giCameraRunSingle("001", false);
        giPlayerWalkTo(0, 790.3, -313.6, 157.4, false);
        giPlayerEndMove(2);
        giPlayerSetDir(2, 196.0, true);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 182.0, true);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 165.0, true);
        giCameraWait();
        giCameraRunSingle("003", true);
        giWait(1.0);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：<colour red=255 green=187 blue=0 alpha=255>上山之后往西北便是女萝岩，</colour><dc0>东北面则是——</dc0>", "41208");
        giCameraRunSingle("004", false);
        giSetPortrait("103B", false);
        giTalk("韩菱纱：嘻嘻，我知道，是先代淮南王的陵寝对不对？", "41209");
        giSetPortrait("106A", true);
        giTalk("柳梦璃：韩姑娘说的没错。", "41210");
        giSetPortrait("103M", false);
        giTalk("韩菱纱：那老头还挺会挑呢，八公山山势不错，兼具“四势”中的“青龙”、“白虎”，两相拱抱能让穴场不受外风吹袭，可惜啊可惜，山前却只有寿阳的护城河，要是能够聚水成沼，就真的再好不过了～", "41211");
        giPlayerSetDir(0, 107.0, false);
        giCameraWait();
        giSetPortrait("101A", false);
        giTalk("云天河：……菱纱，你讲的话怎么那么怪？好难懂……", "41212");
        giWait(0.6);
        giIMMBegin();
        giCameraRunSingle("005", false);
        giPlayerSetAng(1, 291.0);
        giPlayerSetAng(2, 318.0);
        giIMMEnd();
        giWait(0.5);
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("103F", true);
        giTalk("韩菱纱：哼！你就是吃的多，懂的少！", "41213");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "J17", -1, false);
        giSetPortrait("101E", false);
        giTalk("云天河：话是这么说没错……那我以后少吃点。", "41214");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giPlayerDoAction(1, "J06", 1, false);
        giSetPortrait("103F", true);
        giTalk("韩菱纱：算了算了，你爱吃多少吃多少，我已经习惯了，不然总有一天被你气死……", "41215");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", false);
        giTalk("云天河：哈哈……", "41216");
        giPlayerEndAction(0);
        giWait(0.3);
        giPlayerSetDir(2, 26.0, true);
        giWait(0.4);
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：……我听爹说过，风水堪舆之术晦涩难明，往往一二十年才能略有小成，韩姑娘真不简单。", "41217");
        giPlayerSetDir(1, 213.0, false);
        giPlayerSetDir(0, 140.0, true);
        giWait(0.8);
        giSetPortrait("103B", false);
        giTalk("韩菱纱：哈、哈哈，也没什么啦，在我老家要是不懂这个，会被人笑话一辈子的。", "41218");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103M", false);
        giTalk("韩菱纱：对了，我说，我们现在也算一条船上的了，你别那么见外，叫我菱纱就好，不然我可要叫你“柳大小姐”啰。", "41219");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(2, "C08", 1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：……我知道了，菱纱。", "41220");
        giPlayerEndAction(2);
        giPlayerDoAction(1, "J05", 1, false);
        giSetPortrait("103M", false);
        giTalk("韩菱纱：这才是嘛，别这么拘谨～", "41221");
        giSetPortrait("103M", false);
        giTalk("韩菱纱：好了，不用多说，<colour red=255 green=187 blue=0 alpha=255>快点赶去女萝岩吧！</colour>", "41222");
        giWait(0.4);
        giFlashOutBlack(1.5, true, true);
        giCameraWait();
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giMonsterSetHide("m05-02-01", true);
        giMonsterSetHide("m05-01-02", true);
        giMonsterSetHide("m05-02-03", true);
        giSetObjectVisible("item009", true);
        global_mvar = 30500; // 0x00007724, 北门出城
        giIMMEnd();
        giPlayerCurrentSetPos(1101.9, -315.7, 565.0);
        giPlayerCurrentSetAng(212.0);
        giPlayerCurrentSetVisible(true);
        giCameraSetCollide(true);
        giCameraAutoSeek(true);
        giCameraSetMode(0, true);
        giCameraSeekToPlayer();
        giTimeScript(180.0, "func9001");
        giPlayerUnLock();
        giFlashInBlack(1.5, true);
    }
}

void func2002()
{
    if (global_mvar == 31200 /* 第一章 / 2-5-5.女萝平妖 / 土灵遁地 */)
    {
        giPlayerLock();
        giTimeScriptTerminate();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerCurrentSetVisible(false);
        giPlayerSetPos(0, -2618.7, 869.4, -2280.8);
        giPlayerSetAng(0, 254.0);
        giPlayerSetPos(1, -2710.0, 869.4, -2298.8);
        giPlayerSetAng(1, 280.0);
        giPlayerSetPos(2, -2656.1, 869.4, -2347.9);
        giPlayerSetAng(2, 311.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giCameraPrepare("MC002");
        giArenaReady();
        giCameraRunSingle("003", true);
        giFlashInBlack(1.5, true);
        giCameraRunSingle("005", false);
        giWait(1.5);
        giPlayerSetDir(1, 82.0, true);
        giPlayerDoAction(1, "J16", -1, false);
        giSetPortrait("103B", false);
        giTalk("韩菱纱：太棒了，土灵珠果然不同凡响！", "41351");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraWait();
        giCameraRunSingle("012", true);
        giPlayerDoAction(0, "J16", 1, false);
        giSetPortrait("101K", true);
        giTalk("云天河：呵呵，这个好玩～“嗖”的一下就到了！", "41352");
        giPlayerEndAction(1);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：……不过，小猫说这是它们唯一的宝贝，送给我们真的可以吗？", "41353");
        giPlayerDoAction(2, "C08", 1, false);
        giSetPortrait("106F", true);
        giTalk("柳梦璃：嗯，没关系，它们报恩是一心一意的，要是我们不收，反而很失礼了。", "41354");
        giPlayerEndAction(1);
        giPlayerSetDir(0, 212.0, false);
        giPlayerSetDir(1, 144.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "C08", 1, false);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：梦璃，你的想法真是与众不同～", "41355");
        giPlayerEndAction(1);
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("106F", true);
        giTalk("柳梦璃：我觉得……渺渺世间，不独有人，人要活下去，妖也是一样，为何彼此之间不能多一些理解呢？", "41356");
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("106F", true);
        giTalk("柳梦璃：至少我并不会认为妖都是狰狞可恨的，万物皆是生灵，又哪里有天注定的贵贱善恶之分？", "41357");
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101B", false);
        giTalk("云天河：话这么说没错，我爹就常常这样说！", "41358");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：……", "41359");
        giCameraRunSingle("001", true);
        giScriptMusicPlay("P57", 2, 0.0, 2.5);
        giEffectPlayWithNPC("H_090", 1, "MN001");
        giNpcBlendIn("MN001", 1.0, false);
        giEffectPlayWithNPC("H_090", 1, "MN002");
        giNpcBlendIn("MN002", 1.0, true);
        giPlayerSetDir(1, 280.0, true);
        giPlayerSetDir(2, 285.0, true);
        giPlayerSetDir(0, 273.0, true);
        giWait(1.0);
        giNpcSetDir("MN002", 93.0, true);
        giNpcSetDir("MN001", 78.0, true);
        giWait(1.0);
        giNpcDoAction("MN002", "J01", -1, false);
        giSetPortrait("203B", true);
        giTalk("怀朔：二位，又见面了。", "41360");
        giNpcUnHoldAct("MN002");
        giNpcEndAction("MN002", true);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103D", false);
        giTalk("韩菱纱：咦？真是巧！", "41361");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giIMMBegin();
        giNpcSetAng("MN001", 49.0);
        giCameraRunSingle("007", true);
        giIMMEnd();
        giSetPortrait("202A", false);
        giTalk("璇玑：师兄，他们是谁？", "41362");
        giWait(0.3);
        giNpcSetDir("MN002", 219.0, true);
        giWait(0.3);
        giSetPortrait("203B", true);
        giTalk("怀朔：你不记得了？那夜在巢湖边遇见的……", "41363");
        giSetPortrait("202D", false);
        giTalk("璇玑：下山以后天天见那么多人，每个都要记住，人家还不早早累死？", "41364");
        giSetPortrait("202D", false);
        giTalk("璇玑：不管这些了～既然寿阳附近有妖怪，我们就快把妖怪打跑，好去找紫英师叔！", "41365");
        giIMMBegin();
        giPlayerSetPos(0, -2774.2, 869.4, -2367.8);
        giPlayerSetAng(0, 327.0);
        giPlayerSetPos(1, -2728.5, 869.4, -2329.7);
        giPlayerSetAng(1, 297.0);
        giPlayerSetPos(2, -2744.8, 869.4, -2267.1);
        giPlayerSetAng(2, 244.0);
        giIMMEnd();
        giCameraRunSingle("011", true);
        giWait(0.3);
        giSetPortrait("106G", true);
        giTalk("柳梦璃：……！！", "41366");
        giPlayerDoAction(0, "J17", -1, false);
        giSetPortrait("101J", false);
        giTalk("云天河：哦……原来你们也是慢一步的，有人早把妖怪砍光了。", "41367");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giNpcSetDir("MN001", 121.0, false);
        giNpcSetDir("MN002", 144.0, true);
        giWait(0.5);
        giNpcDoAction("MN001", "J02", 1, false);
        giSetPortrait("202C", true);
        giTalk("璇玑：骗人！我不信！你说！哪有人这么厉害？！", "41368");
        giNpcEndAction("MN001", false);
        giWait(0.5);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：小妹妹，云公子没有骗你。", "41369");
        giSetPortrait("106A", true);
        giTalk("柳梦璃：我们也是来女萝岩探查妖伤人之事，进入洞中才发现所有槐妖都被一剑穿心而死……说不定是剑仙所为呢。", "41370");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giCameraRunSingle("007", true);
        giIMMBegin();
        giPlayerSetAng(0, 325.0);
        giPlayerSetAng(1, 303.0);
        giPlayerSetAng(2, 268.0);
        giIMMEnd();
        giNpcSetDir("MN002", 219.0, true);
        giSetPortrait("203B", true);
        giTalk("怀朔：哈哈，璇玑，看样子紫英师叔总比我们快上半步，这辈子是别想追上了。", "41371");
        giNpcSetDir("MN001", 49.0, false);
        giSetPortrait("202A", false);
        giTalk("璇玑：真的？是师叔做的？", "41372");
        giNpcDoAction("MN002", "C08", 1, false);
        giSetPortrait("203B", true);
        giTalk("怀朔：听这位姑娘所言，如此凌厉的手法，恐怕不做第二人想。", "41373");
        giSetPortrait("202A", false);
        giTalk("璇玑：嗯嗯～这就难怪了，紫英师叔就是厉害，他的剑法在同辈弟子中可是无人能及！", "41374");
        giSetPortrait("203A", true);
        giTalk("怀朔：谨慎起见，你我还是进入女萝岩，再看看有无妖类余孽。", "41375");
        giWait(0.4);
        giCameraRunSingle("002", true);
        giWait(0.3);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", true);
        giTalk("云天河：……哈哈～哈哈哈～", "41376");
        giIMMBegin();
        giNpcSetAng("MN001", 120.0);
        giNpcSetAng("MN002", 143.0);
        giCameraRunSingle("006", true);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("203A", false);
        giTalk("怀朔：嗯？怎么了？", "41377");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101K", true);
        giTalk("云天河：哈哈…………不、不用了吧？", "41378");
        giSetPortrait("101F", true);
        giTalk("云天河：我们才刚从里面出来，除了尸体，我保证啥都没有。", "41379");
        giPlayerEndAction(0);
        giIMMBegin();
        giNpcSetAng("MN001", 43.0);
        giCameraRunSingle("004", true);
        giIMMEnd();
        giSetPortrait("202C", true);
        giTalk("璇玑：对啊，师兄，人家要生气啰！紫英师叔你都信不过吗？", "41380");
        giNpcSetDir("MN002", 219.0, true);
        giWait(0.3);
        giNpcDoAction("MN002", "C09", 1, false);
        giSetPortrait("203A", false);
        giTalk("怀朔：当然不是，只不过——", "41381");
        giSetPortrait("202C", true);
        giTalk("璇玑：还“不过”什么？师叔他都赶去陈州了，我们也要快点追上，你别总慢慢吞吞的啦！", "41382");
        giEffectPlayWithNPC("H_089", 1, "MN001");
        giNpcBlendOut("MN001", 1.5, true);
        giNpcDoAction("MN002", "C07", -1, false);
        giSetPortrait("203A", false);
        giTalk("怀朔：小师妹——！", "41383");
        giNpcUnHoldAct("MN002");
        giNpcEndAction("MN002", true);
        giEffectPlayWithNPC("H_089", 1, "MN002");
        giNpcBlendOut("MN002", 1.5, true);
        giWait(1.0);
        giIMMBegin();
        giPlayerSetPos(0, -2786.5, 869.4, -2361.3);
        giPlayerSetAng(0, 56.0);
        giPlayerSetPos(2, -2768.3, 869.4, -2279.8);
        giPlayerSetAng(2, 148.0);
        giCameraRunSingle("010", true);
        giIMMEnd();
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：等一下啊！喂——！！", "41384");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.4);
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("103E", true);
        giTalk("韩菱纱：…………唉，这两个人还是风风火火的，连拜入他们师门的事情都没机会说。", "41385");
        giSetPortrait("103E", true);
        giTalk("韩菱纱：不过也好，他们居然也还没去陈州……", "41386");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraRunSingle("013", true);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", true);
        giTalk("云天河：呵呵，菱纱，那个女孩和你有点像呢，都喜欢生气～", "41387");
        giPlayerSetDir(1, 249.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "J17", -1, false);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：谁喜欢生气了！", "41388");
        giSetPortrait("103F", false);
        giTalk("韩菱纱：云、天、河，你一定要分清楚爱生气和被人气是两回事！", "41389");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", true);
        giTalk("云天河：呵呵，知道了。", "41390");
        giPlayerEndAction(0);
        giSetPortrait("103G", false);
        giTalk("韩菱纱：哼！亏你还笑得出来……", "41391");
        giCameraRunSingle("009", true);
        giWait(0.5);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("106A", false);
        giTalk("柳梦璃：你们……想要去修仙吗？", "41392");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giIMMBegin();
        giPlayerSetDir(1, 323.0, false);
        giPlayerSetDir(0, 5.0, false);
        giIMMEnd();
        giWait(0.8);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103M", true);
        giTalk("韩菱纱：哎？是我要去啦，这家伙只想学御剑术偷懒，不过探访他老爹来历的事也很重要就对了。", "41393");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("106D", false);
        giTalk("柳梦璃：云叔？", "41394");
        giSetPortrait("101B", true);
        giTalk("云天河：因为那个……爹活着的时候都没有交代什么，可是菱纱又说他留下的这把剑怪怪的——", "41395");
        giPlayerSetDir(2, 190.0, false);
        giPlayerSetDir(1, 249.0, true);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：什么我说怪，本来就怪……", "41396");
        giCameraRunSingle("014", false);
        giSetPortrait("101B", false);
        giTalk("云天河：哦……话是这么说没错……", "41397");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", false);
        giTalk("云天河：我想知道爹以前是做什么的，好像和那个修仙门派有关，所以就……呵呵。", "41398");
        giSetPortrait("106A", true);
        giTalk("柳梦璃：唔……我也跟你们一起去行吗？", "41399");
        giSetPortrait("101K", false);
        giTalk("云天河：啊？真、真的吗？！", "41400");
        giSetPortrait("103F", true);
        giTalk("韩菱纱：（白痴，干嘛一脸期待的样子……）", "41401");
        giIMMBegin();
        giPlayerSetAng(1, 323.0);
        giCameraRunSingle("015", true);
        giIMMEnd();
        giCameraRunSingle("019", false);
        giSetPortrait("103M", true);
        giTalk("韩菱纱：这、你爹他答应吗？", "41402");
        giPlayerSetDir(2, 151.0, true);
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("103B", true);
        giTalk("韩菱纱：而且……那个……如果我没猜错，要不是我厚着脸皮和你讲话，你应该也不怎么喜欢我和天河吧？", "41403");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("106F", false);
        giTalk("柳梦璃：……对不起，我从小到大几乎没离开过柳府，对世情知道的很少，对人都很有戒心……", "41404");
        giSetPortrait("106F", false);
        giTalk("柳梦璃：一开始确实像你说的，可是后来我知道你们都是心地很好的人，就觉得是自己不应该…… ", "41405");
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103A", true);
        giTalk("韩菱纱：（……原来如此，再怎么厉害稳重，也还是个养在深闺的大小姐，她连个朋友都没有……）", "41406");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101K", true);
        giTalk("云天河：梦璃你对我们很好啊，把菱纱画得那么像，还夸我爹是大英雄，爹要是知道，肯定开心死了！", "41407");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giPlayerDoAction(1, "C08", 1, false);
        giSetPortrait("103M", true);
        giTalk("韩菱纱：…………对、对啊，连我的亲人都画不到那么传神呢！", "41408");
        giSetPortrait("103B", true);
        giTalk("韩菱纱：再说你还帮了我一个大忙！虽然我长得也挺好看，但是我可不想一直被四处贴头像缉拿，俗话说“民不与官斗”嘛！", "41409");
        giPlayerSetEmotion(2, "106_wx");
        giCameraRunSingle("016", true);
        giWait(0.5);
        giPlayerDoAction(2, "C08", 1, false);
        giSetPortrait("106A", false);
        giTalk("柳梦璃：嗯，谢谢～爹和娘那边我会跟他们好好说的。", "41410");
        giPlayerEndAction(2);
        giPlayerDoAction(2, "J07", 1, false);
        giSetPortrait("106C", false);
        giTalk("柳梦璃：今后就麻烦你们了。", "41411");
        giPlayerEndAction(2);
        giWait(1.1);
        giCameraRunSingle("020", true);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：（……笑、她笑了……）", "41412");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetAng(2, 168.0);
        giCameraRunSingle("021", false);
        giWait(1.5);
        giPlayerSetEmotion(2, "106_zc");
        giPlayerSetDir(1, 249.0, true);
        giSetPortrait("101F", true);
        giTalk("云天河：…………", "41413");
        giSetPortrait("103C", false);
        giTalk("韩菱纱：（这猪头，看得发痴了……）", "41414");
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103E", false);
        giTalk("韩菱纱：（可恶……有种被比下去的感觉……我的眉毛、鼻子、眼睛应该也不差吧……）", "41415");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraRunSingle("017", false);
        giWait(1.5);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("106C", false);
        giTalk("柳梦璃：<colour red=255 green=187 blue=0 alpha=255>我们回寿阳吧，</colour><dc0>让爹和娘知道这里的情况。</dc0>", "41416");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giWait(0.5);
        giPlayerSetDir(1, 323.0, true);
        giWait(0.5);
        giPlayerWalkTo(2, -2894.5, 881.9, -2222.2, false);
        giWait(2.5);
        giPlayerSetDir(0, 334.0, true);
        giCameraRunSingle("018", true);
        giWait(1.5);
        giPlayerSetDir(1, 249.0, true);
        giSetPortrait("103E", false);
        giTalk("韩菱纱：发什么呆！哼，男人都是见色心起！", "41417");
        giPlayerSetDir(0, 56.0, true);
        giSetPortrait("101C", true);
        giTalk("云天河：什么意思？", "41418");
        giSetPortrait("103E", false);
        giTalk("韩菱纱：不懂算了。", "41419");
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：说起来，连我都被你的外表给蒙住了，你这家伙竟然也会骗人，还跟怀朔他们说女萝岩里没妖怪了……", "41420");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101F", true);
        giTalk("云天河：我没说错啊，那几只小妖怪都已经离开了，不、不算骗人！", "41421");
        giSetPortrait("103J", false);
        giTalk("韩菱纱：少来，你表情那么心虚干嘛？大～傻～瓜～", "41422");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giPlayerRunTo(1, -2865.2, 873.2, -2225.9, false);
        giCameraRunSingle("022", false);
        giWait(1.0);
        giPlayerSetDir(0, 318.0, true);
        giWait(0.5);
        giSetPortrait("101E", true);
        giTalk("云天河：（……干嘛说我傻瓜……）", "41423");
        giFlashOutBlack(1.0, true, true);
        giCameraWait();
        giPlayerEndMove(1);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerCurrentSetVisible(true);
        giCameraSetCollide(true);
        giCameraAutoSeek(true);
        giCameraSetMode(0, true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        global_mvar = 31300; // 0x00007A44, 第一章 / 2-5-6.女萝平妖 / 回府交代 / 女萝槐妖
        giIMMEnd();
        giScriptMusicStop(1, 2.5);
        giTimeScript(180.0, "func9001");
        giFlashInBlack(1.5, true);
        giPlayerUnLock();
    }
}

void func2003()
{
    if (global_mvar == 40300 /* 第一章 / 3-1-2.少年行 / 启程往陈州 */)
    {
        giMonsterStopPursuit();
        giTimeScriptTerminate();
        giPlayerLock();
        giFlashOutBlack(0.5, true, true);
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerCurrentSetVisible(false);
        giIMMBegin();
        giPlayerSetPos(0, 2054.1, 834.0, -1675.8);
        giPlayerSetAng(0, 77.0);
        giPlayerSetPos(1, 2109.2, 870.6, -1696.4);
        giPlayerSetAng(1, 96.0);
        giPlayerSetPos(2, 2083.2, 852.7, -1742.3);
        giPlayerSetAng(2, 92.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giHideGASkillObject();
        giIMMEnd();
        giCameraPrepare("MC003");
        giCameraRunSingle("002", true);
        giFlashInBlack(3.5, false);
        giCameraRunSingle("004", false);
        giWait(0.5);
        giPlayerWalkTo(1, 2240.7, 896.9, -1705.8, false);
        giWait(0.7);
        giPlayerWalkTo(2, 2200.1, 896.9, -1746.0, false);
        giPlayerWalkTo(0, 2203.6, 896.9, -1667.3, false);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 95.0, true);
        giPlayerEndMove(2);
        giPlayerSetDir(2, 94.0, true);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 87.0, true);
        giCameraWait();
        giWait(0.5);
        giNpcWalkTo("MN004", 2319.8, 896.9, -1643.4, false);
        giNpcWalkTo("MN003", 2329.2, 896.9, -1738.6, false);
        giNpcEndMove("MN003");
        giNpcEndMove("MN004");
        giNpcSetDir("MN003", 292.0, true);
        giNpcSetDir("MN004", 229.0, true);
        giNpcDoAction("MN004", "J03", -1, false);
        giNpcDoAction("MN003", "J03", -1, false);
        giWait(0.4);
        giTalk("卫兵甲：什么人？！此地不可通行！", "41636");
        giIMMBegin();
        giPlayerSetDir(1, 50.0, false);
        giPlayerSetDir(0, 78.0, false);
        giPlayerSetDir(2, 44.0, false);
        giIMMEnd();
        giWait(0.8);
        giCameraRunSingle("011", true);
        giTalk("卫兵乙：没错！快滚！", "41637");
        giPlayerDoAction(1, "C07", 1, false);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：大胆！你们可知我身后的这位姑娘是谁？！", "41638");
        giNpcUnHoldAct("MN004");
        giNpcEndAction("MN004", true);
        giNpcUnHoldAct("MN003");
        giNpcEndAction("MN003", true);
        giNpcWalkTo("MN003", 2281.2, 896.9, -1771.7, false);
        giNpcWalkTo("MN004", 2299.3, 896.9, -1722.4, false);
        giWait(0.5);
        giCameraRunSingle("010", false);
        giPlayerSetDir(1, 158.0, true);
        giPlayerSetDir(2, 96.0, true);
        giPlayerSetDir(0, 146.0, true);
        giNpcEndMove("MN003");
        giNpcSetDir("MN003", 295.0, false);
        giNpcEndMove("MN004");
        giNpcSetDir("MN004", 255.0, false);
        giWait(0.7);
        giTalk("卫兵乙：这……长得倒是不错！", "41639");
        giTalk("卫兵甲：再漂亮也就是个女人，难不成她还是天仙？", "41640");
        giPlayerDoAction(1, "J17", -1, false);
        giSetPortrait("103F", true);
        giTalk("韩菱纱：哼，这位姑娘乃是寿阳县令的千金，代父巡查此地，你们两个有眼不识泰山的家伙，还不快快让开！", "41641");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giTalk("卫兵甲：我就说嘛，真是天仙还能来这鬼地方！", "41642");
        giCameraRunSingle("015", true);
        giWait(0.3);
        giNpcDoAction("MN003", "J01", 1, false);
        giTalk("卫兵乙：走开走开！长得再漂亮，这儿也不能让你过！还是说……你想留下来陪大爷玩儿～", "41643");
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("106E", true);
        giTalk("柳梦璃：你——！", "41644");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giPlayerDoAction(1, "J01", -1, false);
        giSetPortrait("103I", false);
        giTalk("韩菱纱：闭上你的臭嘴！连县令千金也敢冒犯！", "41645");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giIMMBegin();
        giNpcSetDir("MN004", 295.0, false);
        giNpcSetDir("MN003", 317.0, false);
        giIMMEnd();
        giWait(0.8);
        giTalk("卫兵乙：县令千金？！那又怎样！她爹办事不力，前阵子这儿竟出了盗墓贼，如今这前朝王陵已归京中直接管辖，不干县令什么事了！", "41646");
        giTalk("卫兵甲：听说那毛贼是个女的，不知长啥样，我呸！要不是那婆娘害的，我们兄弟几个又怎会来守这鬼地方，不但没油水捞，最近连妖怪都冒出来了，真是苦差！", "41647");
        giPlayerDoAction(0, "J18", 1, false);
        giSetPortrait("101I", false);
        giTalk("云天河：你们！不许骂人！！", "41648");
        giPlayerEndAction(0);
        giNpcSetDir("MN004", 295.0, false);
        giNpcSetDir("MN003", 317.0, false);
        giTalk("卫兵甲：怎样？！你小子找死啊？", "41649");
        giSetPortrait("103F", false);
        giTalk("韩菱纱：天河别理他们，跟我过来……", "41650");
        giPlayerWalkTo(1, 2054.1, 834.0, -1675.8, false);
        giWait(0.5);
        giPlayerWalkTo(2, 2082.4, 853.2, -1708.6, false);
        giWait(0.5);
        giPlayerSetDir(0, 242.0, true);
        giPlayerDoAction(0, "J14", 1, true);
        giPlayerWalkTo(0, 2082.4, 853.2, -1708.6, false);
        giWait(1.5);
        giNpcSetDir("MN004", 277.0, false);
        giNpcSetDir("MN003", 292.0, false);
        giCameraRunSingle("014", false);
        giTalk("卫兵乙：算你们识相！再多废话，全给大爷抓回去关起来！！", "41651");
        giCameraWait();
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giPlayerSetPos(1, 1462.3, 433.4, -1763.8);
        giPlayerSetPos(2, 1462.3, 433.4, -1763.8);
        giPlayerSetPos(0, 1462.3, 433.4, -1763.8);
        giCameraRunSingle("020", false);
        giIMMEnd();
        giCameraRunSingle("021", false);
        giPlayerWalkTo(0, 1234.3, 341.5, -1674.9, false);
        giWait(0.7);
        giPlayerWalkTo(1, 1262.3, 361.6, -1717.4, false);
        giWait(0.7);
        giPlayerWalkTo(2, 1331.0, 353.1, -1671.4, false);
        giFlashInBlack(0.5, false);
        giPlayerEndMove(0);
        giPlayerEndMove(1);
        giPlayerEndMove(2);
        giIMMBegin();
        giPlayerSetDir(0, 142.0, false);
        giPlayerSetDir(1, 47.0, false);
        giPlayerSetDir(2, 241.0, false);
        giIMMEnd();
        giWait(1.0);
        giPlayerDoAction(1, "J15", -1, false);
        giSetPortrait("103I", true);
        giTalk("韩菱纱：气死我了！那两个人，满口胡言！！", "41652");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("106B", false);
        giTalk("柳梦璃：……都是些疯话，又何必跟他们计较。", "41653");
        giSetPortrait("103F", true);
        giTalk("韩菱纱：最可恨的是，如今失了先机，又不能直接动手打晕他们！", "41654");
        giPlayerDoAction(0, "J17", -1, false);
        giSetPortrait("101C", true);
        giTalk("云天河：为什么不能？那两个人看起来一点都不厉害……", "41655");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giIMMBegin();
        giPlayerSetDir(1, 345.0, false);
        giPlayerSetDir(2, 267.0, false);
        giIMMEnd();
        giWait(0.8);
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：笨笨笨！他们已经知道了梦璃的来历，万一以后找柳家麻烦怎么办？", "41656");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：……太失算了，本以为说出梦璃的身份就能轻而易举过关……", "41657");
        giPlayerDoAction(0, "C09", 1, false);
        giSetPortrait("101C", true);
        giTalk("云天河：我还是不太懂，柳波波不是老大吗？他手下那么多，根本不用怕这两个～", "41658");
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：你烦不烦呐……这要我怎么说……", "41659");
        giSetPortrait("103F", false);
        giTalk("韩菱纱：总之他们的老大可能比县令老大要厉害，所以县令老大也没办法！", "41660");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("101J", true);
        giTalk("云天河：哦……", "41661");
        giSetPortrait("103F", false);
        giTalk("韩菱纱：看样子只有另找条路绕过去……", "41662");
        giPlayerSetDir(2, 241.0, true);
        giWait(0.5);
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("106B", false);
        giTalk("柳梦璃：……我倒有个办法，不妨试一试……", "41663");
        giWait(0.5);
        giIMMBegin();
        giCameraRunSingle("022", false);
        giPlayerSetAng(1, 52.0);
        giPlayerSetAng(0, 85.0);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：咦？！", "41664");
        giSetPortrait("103M", true);
        giTalk("韩菱纱：好梦璃！你有办法怎么不早说～", "41665");
        giWait(0.5);
        giPlayerDoAction(2, "J05", 1, true);
        giWait(0.8);
        giCameraRunSingle("020", false);
        giPlayerWalkTo(2, 1462.3, 433.4, -1763.8, false);
        giWait(0.7);
        giPlayerWalkTo(1, 1462.3, 433.4, -1763.8, false);
        giWait(0.7);
        giPlayerWalkTo(0, 1462.3, 433.4, -1763.8, false);
        giWait(0.7);
        giFlashOutBlack(1.5, true, true);
        giPlayerEndMove(2);
        giPlayerEndMove(1);
        giPlayerEndMove(0);
        giIMMBegin();
        giPlayerSetPos(0, 2054.1, 834.0, -1675.8);
        giPlayerSetAng(0, 77.0);
        giPlayerSetPos(2, 2109.2, 870.6, -1696.4);
        giPlayerSetAng(2, 72.0);
        giPlayerSetPos(1, 2083.2, 852.7, -1742.3);
        giPlayerSetAng(1, 94.0);
        giNpcSetPos("MN004", 2301.8, 896.9, -1747.0);
        giNpcSetPos("MN003", 2291.7, 896.9, -1782.3);
        giNpcSetAng("MN004", 283.0);
        giNpcSetAng("MN003", 290.0);
        giIMMEnd();
        giCameraRunSingle("026", true);
        giPlayerWalkTo(2, 2201.0, 896.9, -1715.1, false);
        giWait(0.7);
        giPlayerWalkTo(1, 2162.2, 896.9, -1762.8, false);
        giWait(0.7);
        giPlayerWalkTo(0, 2164.9, 896.9, -1670.8, false);
        giFlashInBlack(1.5, false);
        giPlayerEndMove(2);
        giPlayerSetDir(2, 112.0, true);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 92.0, true);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 119.0, true);
        giWait(0.9);
        giNpcDoAction("MN003", "J03", -1, false);
        giTalk("卫兵乙：你们还在？！真活得不耐烦了？！", "41666");
        giWait(0.5);
        giCameraRunSingle("026", true);
        giWait(0.5);
        giPlayerDoAction(2, "J12", 1, false);
        giEffectAttachToPlayer(2, "H_TL03.2", false);
        giWait(3.5);
        giEffectDetachFromPlayer(2);
        giIMMBegin();
        giSetObjectVisible("Jeffect001", true);
        giSetObjectVisible("Jeffect002", true);
        giIMMEnd();
        giWait(0.5);
        giTalk("卫兵甲：你做什——啊…………", "41667");
        giNpcDoAction("MN003", "J02", -1, false);
        giWait(0.8);
        gi2DSoundPlay("WJ065", 1);
        giNpcDoAction("MN004", "J02", -1, false);
        giWait(0.8);
        gi2DSoundPlay("WJ065", 1);
        giWait(2.0);
        giCameraRunSingle("027", true);
        giPlayerWalkTo(0, 2264.9, 896.9, -1696.9, false);
        giWait(0.5);
        giPlayerWalkTo(1, 2239.9, 896.9, -1792.0, false);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 173.0, true);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 41.0, true);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101D", true);
        giTalk("云天河：……这样就晕了？原来人不一定是用打的才会晕啊？长见识了。", "41668");
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：……他们中了法术，要过一会儿才能清醒，醒来以后也不会记得刚才发生的事，当然也不记得我们了。", "41669");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giPlayerSetDir(0, 231.0, true);
        giPlayerSetDir(1, 325.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "J16", -1, false);
        giSetPortrait("103B", false);
        giTalk("韩菱纱：真的？竟有这种法术？！太厉害了！！嘻嘻！果然力敌不如智取～不像某人，就只知道用蛮力砸人……", "41670");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetDir(0, 250.0, false);
        giPlayerSetDir(2, 139.0, true);
        giWait(0.5);
        giSetPortrait("106B", true);
        giTalk("柳梦璃：也没有你说的那样厉害，这个法术只对寻常人有用，若是稍有修炼或是精神力强的人，就一点用处也没有了。", "41671");
        giWait(0.3);
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：……更何况…………", "41672");
        giSetPortrait("103C", false);
        giTalk("韩菱纱：什么？", "41673");
        giSetPortrait("101C", true);
        giTalk("云天河：……？", "41674");
        giSetPortrait("106F", true);
        giTalk("柳梦璃：……人心里的记忆本是最重要的东西，这样随随便便夺取，未免过于残忍……", "41675");
        giSetPortrait("103A", false);
        giTalk("韩菱纱：…………梦璃，你的心真好。不过这两个家伙一看就知道平时作威作福惯了，根本不算什么好人——", "41676");
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101B", true);
        giTalk("云天河：对对对！所以你做的也不算坏事！", "47001");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("103M", false);
        giTalk("韩菱纱：嗯，天河说的对！", "41677");
        giWait(0.7);
        giPlayerDoAction(2, "J07", 1, false);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：……嗯，谢谢你们，我心里好受多了～", "41678");
        giPlayerEndAction(2);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：趁卫兵还没醒，我们快走吧。", "41679");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：慢～～～", "41680");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetDir(0, 190.0, true);
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：依我看呢～这两个家伙刚才说了不少梦璃和我的坏话，连县令大人也被他们羞辱，不教训一下也太说不过去了！", "41681");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("101D", true);
        giTalk("云天河：那，要怎么做……？", "41682");
        giPlayerSetDir(1, 6.0, true);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：看我的！", "41683");
        giScriptMusicPlay("P70", 2, 2.5, 0.0);
        giPlayerDoAction(1, "J03", -1, true);
        giWait(1.5);
        giSetPortrait("101K", true);
        giTalk("云天河：……！！这个好玩～我也要！", "41684");
        giPlayerDoAction(0, "J03", -1, true);
        giWait(0.5);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：哈哈，来来来！见者有份！", "41685");
        giSetPortrait("103J", false);
        giTalk("韩菱纱：梦璃要不要？", "41686");
        giPlayerDoAction(2, "J14", 1, true);
        giWait(0.5);
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("106B", true);
        giTalk("柳梦璃：不用了，谢谢……", "41687");
        giWait(1.5);
        giPlayerEndAction(2);
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("103J", false);
        giTalk("韩菱纱：天河，你画的有趣～比我的好～", "41688");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("101K", true);
        giTalk("云天河：是吗？我对它最熟悉了～很像吧？哈哈！", "41689");
        giPlayerDoAction(1, "J16", -1, false);
        giSetPortrait("103B", false);
        giTalk("韩菱纱：嘻～大功告成，我们走！", "41690");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giAddMoney(100, true);
        giWait(2.5);
        giSetPortrait("106A", true);
        giTalk("柳梦璃：嗯……", "41691");
        giPlayerWalkTo(1, 2449.3, 896.9, -1778.3, false);
        giWait(0.5);
        giPlayerWalkTo(0, 2429.2, 896.9, -1732.9, false);
        giWait(0.7);
        giPlayerWalkTo(2, 2430.4, 896.9, -1691.8, false);
        giWait(0.5);
        giFlashOutBlack(1.0, true, true);
        giPlayerEndMove(1);
        giPlayerEndMove(0);
        giPlayerEndMove(2);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giIMMEnd();
        giWait(1.3);
        giCameraRunSingle("028", true);
        giFlashInBlack(1.0, true);
        giWait(1.6);
        giTalk("卫兵甲：……唔……", "41692");
        giTalk("卫兵甲：……我、我怎么躺在这里……", "41693");
        giWait(0.5);
        giTalk("卫兵乙：……到底什么时候……睡着的……", "41694");
        giNpcUnHoldAct("MN004");
        giNpcEndAction("MN004", false);
        giNpcUnHoldAct("MN003");
        giNpcEndAction("MN003", true);
        giWait(0.6);
        giNpcSetDir("MN003", 345.0, false);
        giNpcSetDir("MN004", 182.0, false);
        giWait(0.8);
        giTalk("卫兵甲：…………", "41695");
        giTalk("卫兵甲：哈、哈哈哈哈！你、你的衣服上怎么有只王八！", "41696");
        giTalk("卫兵乙：……！！你还不是一样！衣服上有只山猪，画的还真像！", "41697");
        giTalk("卫兵甲：……糟糕！钱袋好像不见了，昨天才发的饷银！", "41698");
        giTalk("卫兵乙：这荒郊野外的，难道有……鬼？！", "41699");
        giTalk("卫兵甲：光天化日！你别自己吓自己！", "41700");
        giTalk("卫兵乙：可、可是……前天夜里你不也听见王陵里传出的鬼叫！那、那个时候你还说我听错了……", "41701");
        giTalk("卫兵甲：妈呀～～～有鬼！！我们快走，去报告大人！", "41702");
        giCameraRunSingle("029", false);
        giNpcRunTo("MN004", 2055.9, 834.8, -1654.6, false);
        giWait(1.1);
        giNpcSetDir("MN003", 295.0, true);
        giTalk("卫兵乙：你别跑那么快呀！等我！", "41703");
        giNpcRunTo("MN003", 2047.8, 829.9, -1679.3, false);
        giFlashOutBlack(1.5, true, true);
        giCameraWait();
        giNpcEndMove("MN004");
        giNpcEndMove("MN003");
        giIMMBegin();
        giSetNpcVisible("MN003", false);
        giSetNpcVisible("MN004", false);
        giPlayerCurrentSetVisible(true);
        giShowSignpost();
        giIMMEnd();
        giPlayerCurrentSetPos(2654.2, 896.9, -1666.8);
        giPlayerCurrentSetAng(83.0);
        giCameraSetCollide(true);
        giCameraAutoSeek(true);
        giCameraSetMode(0, true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        global_mvar = 40400; // 0x00009DD0, 进入王陵
        giScriptMusicStop(0, 2.5);
        giSetObjectVisible("Jeffect001", false);
        giSetObjectVisible("Jeffect002", false);
        giTimeScript(180.0, "func9001");
        giPlayerUnLock();
        giFlashInBlack(1.5, true);
    }
}

void func2004()
{
    if (global_mvar == 40400 /* 进入王陵 */)
    {
        giMonsterStopPursuit();
        giTimeScriptTerminate();
        giPlayerLock();
        giScriptMusicPlay("P24", 2, 0.0, 2.5);
        giFlashOutBlack(1.5, true, true);
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giIMMBegin();
        giHideGASkillObject();
        giPlayerCurrentSetVisible(false);
        giPlayerSetPos(0, 2699.3, 911.0, -1905.8);
        giPlayerSetAng(0, 103.0);
        giPlayerSetPos(1, 2774.5, 933.9, -1981.1);
        giPlayerSetAng(1, 354.0);
        giPlayerSetPos(2, 2759.7, 929.6, -1891.3);
        giPlayerSetAng(2, 178.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giIMMEnd();
        giCameraPrepare("MC004");
        giCameraRunSingle("003", true);
        giFlashInBlack(1.5, true);
        giSetPortrait("106A", false);
        giTalk("柳梦璃：……这里似乎并无门户，不知要怎样才能进去？", "41704");
        giSetPortrait("103M", true);
        giTalk("韩菱纱：这简单！跟我来～", "41705");
        giPlayerWalkTo(1, 3069.8, 952.0, -2246.1, false);
        giWait(0.7);
        giPlayerWalkTo(2, 2985.8, 931.9, -2179.0, false);
        giWait(0.7);
        giPlayerWalkTo(0, 3046.0, 932.1, -2142.2, false);
        giWait(1.5);
        giCameraRunSingle("001", true);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 355.0, true);
        giPlayerEndMove(2);
        giPlayerSetDir(2, 125.0, true);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 166.0, true);
        giCameraRunSingle("002", true);
        giWait(0.7);
        giSetPortrait("103B", true);
        giTalk("韩菱纱：呐！接下来就看天河的了！把这块石头推开，我们自然有路进去～", "41706");
        giSetPortrait("106D", false);
        giTalk("柳梦璃：……这么大的石头……我看我们几个还是一起——", "41707");
        giPlayerSetDir(1, 308.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "J06", 1, false);
        giSetPortrait("103B", true);
        giTalk("韩菱纱：有什么关系，男孩子就是力气大嘛，这石头连我都挪得动，不过要多费点工夫，天河那一身蛮力，绝对不在话下！我们在旁边替他呐喊助威就好～", "41708");
        giPlayerEndAction(1);
        giPlayerSetDir(1, 355.0, true);
        giWait(0.5);
        giSetPortrait("103J", true);
        giTalk("韩菱纱：是吧？天河～～", "41709");
        giPlayerDoAction(0, "J18", 1, false);
        giSetPortrait("101K", false);
        giTalk("云天河：呵呵，是啊，包在我身上！", "41710");
        giPlayerEndAction(0);
        giCameraRunSingle("004", false);
        giWait(0.3);
        giPlayerWalkTo(0, 3098.1, 949.2, -2189.4, false);
        giWait(1.7);
        giIMMBegin();
        giPlayerSetDir(1, 49.0, false);
        giPlayerSetDir(2, 99.0, false);
        giIMMEnd();
        giWait(0.7);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 99.0, false);
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giSetObjectVisible("MO001", false);
        giSetObjectVisible("MO002", true);
        giPlayerSetPos(0, 3069.8, 957.2, -2281.5);
        giPlayerSetAng(0, 29.0);
        giPlayerSetPos(1, 3123.3, 949.3, -2189.9);
        giPlayerSetAng(1, 208.0);
        giPlayerSetPos(2, 3028.2, 956.2, -2287.3);
        giPlayerSetAng(2, 43.0);
        giIMMEnd();
        giWait(0.3);
        gi2DSoundPlay("WJ046", 1);
        giWait(2.0);
        giCameraRunSingle("005", false);
        giFlashInBlack(1.5, true);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：就这样吧，不用推得太开，这样还有草丛遮着，就算有人经过，也不容易被发现～", "41711");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101B", true);
        giTalk("云天河：这里的人真怪，好好的大门不开，偏要把门开在石头下面……", "41712");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：……洞就是洞，哪来的门，这洞可是我一铲一铲辛苦挖出来的！", "41713");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("101B", true);
        giTalk("云天河：哦……原来遇到没门的就自己开一个～", "41714");
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101K", true);
        giTalk("云天河：菱纱你真厉害，我之前都没想到这种办法！", "41715");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("103M", false);
        giTalk("韩菱纱：哼，那是当然。", "41716");
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("103M", false);
        giTalk("韩菱纱：别看只是挖个洞，讲究的事情多着呢！挑地点要慎重、下铲要匀，万一挖得不好，把周围弄塌可就惨了……", "41717");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("101K", true);
        giTalk("云天河：……不晓得菱纱和老鼠……哪个打洞更厉害一些？", "41718");
        giPlayerDoAction(2, "J14", 1, false);
        giSetPortrait("106C", true);
        giTalk("柳梦璃：噗～～", "41719");
        giPlayerEndAction(2);
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：啊？？你在嘀咕什么呢？走啦走啦！", "41720");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetDir(1, 147.0, true);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：我走前面，梦璃跟着我，天河在最后好了。", "41721");
        giFlashOutBlack(1.5, true, true);
        global_mvar = 40401; // 0x00009DD1
        giArenaLoad("M07", "1", "", true);
    }
}

void func2005()
{
    if (global_mvar < 40300 /* 第一章 / 3-1-2.少年行 / 启程往陈州 */)
    {
        giPlayerLock();
        giPlayerSetLeader(0);
        giPlayerWalkTo(0, 1093.0, -60.2, -467.3, true);
        giPlayerSetDir(0, 263.0, true);
        giSetPortrait("101C", true);
        giTalk("云天河：听菱纱说，那里好像不能随便过去的。", "");
        giPlayerUnLock();
    }
}

void func4001()
{
    giPlayerLock();
    giNpcPauseBeh("4001");
    giNpcFaceToCurrentPlayer("4001", true);
    giCurrentPlayerFaceToNpc("4001", true);
    giRandTalkRelease();
    giRandTalkPush("卫兵丙：前方官道被山上大石阻塞！绕道、绕道！");
    giRandTalkPush("卫兵丙：比起去山上守王陵，这份差事还算悠闲。");
    giRandTalk();
    giRandTalkRelease();
    giNpcResetDir("4001");
    giNpcResumeBeh("4001");
    giPlayerUnLock();
}
