// Structured PAL4 reconstruction for M13.csb
// Only simple if / if-else candidates backed by CFG evidence are folded.

void M13_1_init()
{
    giTimeScript(180.0, "func9001");
    if (global_mvar > 90500 /* 隐香寻人 */)
    {
        giSetNpcVisible("MN006", false);
        giSetNpcVisible("MN009", false);
        giSetNpcVisible("MN010", false);
    }
    if (global_mvar <= 140100 && npc_e == 1 /* 第三章 / 8-3-3.心愿 / 前往妖界 / 亘古神陵 */)
    {
        func3001();
    }
    if (npc_g == 2)
    {
        func3002();
    }
    if ((global_mvar < 120100 && global_mvar >= 100200 || global_mvar < 91300 && global_mvar >= 90100) && npc_g == 4 /* 第二章 / 7-2-3.相争难休 / 送寒器回琼华 */)
    {
        giSetObjectVisible("SO003", true);
        giSetObjectVisible("SO002", true);
        giSetObjectVisible("Jeffect003", true);
        giSetObjectVisible("Jeffect004", true);
        giSetObjectVisible("Jeffect005", true);
        giSetObjectVisible("Jeffect006", true);
        giSetObjectVisible("Jeffect007", true);
    }
    if (global_mvar == 90300 /* 第二章 / 6-1-1.为祸一方 / 书生寻女 */)
    {
        func2001();
    }
    giArenaReadyRestore();
}

void EarthBall()
{
    giPlayerLock();
    giFlashOutBlack(1.0, true, true);
    giPlayerCurrentSetPos(-1995.0, -182.0, 4668.0);
    giPlayerCurrentSetAng(180.0);
    giCameraSetMode(5, true);
    giFlashInBlack(1.0, true);
    giArenaReady();
    giPlayerUnLock();
}

void func1001()
{
    giArenaLoad("M13", "N01", "", true);
    giPlayerCurrentSetPos(-160.0, 6.0, 48.0);
    giPlayerCurrentSetAng(0.0);
    giCameraSetMode(5, true);
    giArenaReady();
}

void func1002()
{
    giArenaLoad("M13", "M13", "", true);
    giPlayerCurrentSetPos(-590.0, 60.0, -491.0);
    giPlayerCurrentSetAng(0.0);
    giCameraSetMode(5, true);
    giArenaReady();
}

void func1003()
{
    int select_dialog_last_select = 0;
    int leader_player_id = 0;

    if (global_mvar != 90800 /* 第二章 / 6-1-3.为祸一方 / 回到即墨 */)
    {
        giMonsterStopPursuit();
        giPlayerLock();
        giSelectDialogAddItem("1.去即墨    ");
        giSelectDialogAddItem("2.御剑飞行  ");
        giSelectDialogAddItem("3.什么都不做");
        giSelectDialogSetDefaultSelect(2);
        giShowSelectDialog("     准备<colour red=255 green=102 blue=0 alpha=255>去即墨</colour><dc0>还是</dc0><colour red=255 green=102 blue=0 alpha=255>御剑飞行</colour><dc0>？</dc0>");
        select_dialog_last_select = giSelectDialogGetLastSelect();
        if (select_dialog_last_select != 0)
        {
            if (select_dialog_last_select != 1)
            {
                leader_player_id = giPlayerGetLeader();
                giPlayerWalkTo(leader_player_id, -1995.0, -182.0, 4668.0, true);
                giPlayerSetDir(leader_player_id, 180.0, true);
                giCameraAutoSeek(true);
                giCameraSetMode(5, true);
                giPlayerUnLock();
            }
            else
            {
                giShowWorldMap();
            }
        }
        else
        {
            giArenaLoad("Q09", "Q09", "", true);
            giPlayerCurrentSetPos(2411.6, 568.2, -2215.6);
            giPlayerCurrentSetAng(306.0);
            giCameraSetMode(0, true);
            giArenaReady();
        }
        giPlayerUnLock();
    }
    else
    {
        giPlayerLock();
        giFlashOutBlack(0.5, true, true);
        giArenaLoad("Q09", "Q09", "", true);
    }
}

void func2001()
{
    if (global_mvar == 90300 /* 第二章 / 6-1-1.为祸一方 / 书生寻女 */)
    {
        giMonsterStopPursuit();
        giTimeScriptTerminate();
        giPlayerLock();
        giFlashOutBlack(1.5, true, true);
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giIMMBegin();
        giPlayerCurrentSetVisible(false);
        giMonsterSetHide("m13-01-03", false);
        giMonsterSetHide("m13-01-02", false);
        giMonsterSetHide("m13-01-05", false);
        giMonsterSetHide("m13-08-09", false);
        giMonsterSetHide("m13-01-06", false);
        giMonsterSetHide("m13-04-01", false);
        giMonsterSetHide("m13-04-02", false);
        giMonsterSetHide("m13-01-08", false);
        giMonsterSetHide("m13-01-09", false);
        giMonsterSetHide("m13-01-04", false);
        giMonsterSetHide("trans05", false);
        giMonsterSetHide("trans02", false);
        giMonsterSetHide("trans03", false);
        giMonsterSetHide("trans04", false);
        giPlayerSetPos(0, 1253.8, -5.0, 1643.8);
        giPlayerSetAng(0, 325.0);
        giPlayerSetPos(1, 1178.7, -10.3, 1662.4);
        giPlayerSetAng(1, 346.0);
        giPlayerSetPos(2, 1247.4, -6.2, 1579.6);
        giPlayerSetAng(2, 343.0);
        giPlayerSetPos(3, 1181.7, -14.0, 1594.2);
        giPlayerSetAng(3, 4.0);
        giSetNpcVisible("MN001", true);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giPlayerSetVisible(3, true);
        giIMMEnd();
        giCameraPrepare("MC001");
        giCameraRunSingle("002", true);
        giCameraSetDistOptEnable(false);
        giFlashInBlack(2.0, false);
        giArenaReady();
        giWait(1.0);
        giCameraRunSingle("001", false);
        giWait(0.5);
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("104A", false);
        giTalk("韩菱纱：那个什么狐仙竟住在这样的好地方，还蛮会享受的嘛！", "43563");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraWait();
        giIMMBegin();
        giPlayerSetPos(3, 1189.6, -12.0, 1598.5);
        giCameraSetDistOptEnable(true);
        giCameraRunSingle("003", true);
        giIMMEnd();
        giWait(0.8);
        giNpcSetDir("MN001", 59.0, true);
        giWait(1.5);
        giNpcSetDir("MN001", 303.0, true);
        giWait(1.5);
        giSetPortrait("220C", false);
        giTalk("夏元辰：莲宝！", "43564");
        giWait(0.4);
        giNpcSetDir("MN001", 149.0, true);
        giWait(0.5);
        giSetPortrait("220C", false);
        giTalk("夏元辰：我听见莲宝的声音！", "43565");
        giNpcWalkTo("MN001", 1220.3, -1.3, 1849.0, false);
        giWait(1.0);
        giPlayerDoAction(2, "J01", -1, false);
        giSetPortrait("107E", true);
        giTalk("柳梦璃：等一下！", "43566");
        giSetNpcVisible("MN001", false);
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giCameraRunSingle("005", true);
        giPlayerDoAction(0, "J13", -1, false);
        giSetPortrait("102D", false);
        giTalk("云天河：咦？山里又没雾，那个人怎么一下就不见了？", "43567");
        giCameraRunSingle("004", false);
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giWait(0.8);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：那位夏公子怕也不简单，不然又怎会一听“昆仑琼华派”，便知是修仙的……", "43568");
        giCameraWait();
        giIMMBegin();
        giPlayerSetDir(1, 166.0, false);
        giPlayerSetDir(2, 320.0, false);
        giPlayerSetDir(0, 250.0, false);
        giIMMEnd();
        giWait(1.0);
        giSetPortrait("105C", false);
        giTalk("慕容紫英：……这山中不寻常，我们务必要谨慎些！", "43569");
        giWait(0.5);
        giFlashOutBlack(1.5, true, true);
        giCameraWait();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerSetVisible(3, false);
        giCameraSetCollide(true);
        giPlayerCurrentSetVisible(true);
        giPlayerCurrentSetPos(-2031.5, -182.8, 4602.2);
        giPlayerCurrentSetAng(180.0);
        giIMMBegin();
        giMonsterSetHide("m13-01-03", true);
        giMonsterSetHide("m13-01-02", true);
        giMonsterSetHide("m13-01-05", true);
        giMonsterSetHide("m13-08-09", true);
        giMonsterSetHide("m13-01-06", true);
        giMonsterSetHide("m13-04-01", true);
        giMonsterSetHide("m13-04-02", true);
        giMonsterSetHide("m13-01-08", true);
        giMonsterSetHide("trans05", true);
        giMonsterSetHide("trans02", true);
        giMonsterSetHide("trans03", true);
        giMonsterSetHide("trans04", true);
        giIMMEnd();
        giCameraSetMode(5, true);
        global_mvar = 90500; // 0x00016184, 隐香寻人
        giTimeScript(180.0, "func9001");
        giPlayerUnLock();
        giFlashInBlack(1.5, true);
    }
}

void func2002()
{
    int random_0_5 = 0;

    if (global_mvar == 90500 /* 隐香寻人 */)
    {
        giMonsterStopPursuit();
        giTimeScriptTerminate();
        giPlayerLock();
        giScriptMusicPlay("P07", 2, 0.0, 0.0);
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giHideGASkillObject();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerCurrentSetVisible(false);
        giPlayerSetPos(0, 2176.2, 741.1, -3851.3);
        giPlayerSetAng(0, 40.0);
        giPlayerSetPos(1, 2140.6, 741.1, -3794.0);
        giPlayerSetAng(1, 51.0);
        giPlayerSetPos(2, 2193.4, 741.1, -3786.5);
        giPlayerSetAng(2, 45.0);
        giPlayerSetPos(3, 2162.5, 741.1, -3728.9);
        giPlayerSetAng(3, 62.0);
        giNpcSetAng("MN009", 265.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giPlayerSetVisible(3, true);
        giMonsterSetHide("m13-07-01", false);
        giMonsterSetHide("trans13", false);
        giSetObjectVisible("save3", false);
        giCameraPrepare("MC002");
        giIMMEnd();
        giCameraRunSingle("001", true);
        giFlashInBlack(1.5, true);
        giWait(0.5);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：那孩子……就是莲宝？！", "43570");
        giWait(0.5);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("104I", true);
        giTalk("韩菱纱：夏书生！他怎么了？", "43571");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraRunSingle("002", true);
        giWait(0.8);
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：哈哈，没怎么，不过就是昏了～", "43572");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetPos(0, 2204.6, 741.1, -3848.9);
        giPlayerSetAng(0, 41.0);
        giPlayerSetPos(1, 2185.3, 741.1, -3786.7);
        giPlayerSetAng(1, 68.0);
        giPlayerSetPos(2, 2224.7, 741.1, -3799.0);
        giPlayerSetAng(2, 59.0);
        giPlayerSetPos(3, 2209.5, 741.1, -3742.7);
        giPlayerSetAng(3, 80.0);
        giCameraRunSingle("003", false);
        giIMMEnd();
        giWait(0.8);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：你既是仙兽，自当庇护凡人，为何反要伤人？！", "43573");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giIMMBegin();
        giCameraRunSingle("002", false);
        giNpcSetAng("MN009", 261.0);
        giIMMEnd();
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：有意思，今天管闲事的人还真不少～", "43574");
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：你这问题问得也笨，都已经做了仙，要是还不能随心所欲捉弄凡人，那有什么意思～", "43575");
        giWait(0.5);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：……！", "43576");
        giWait(0.5);
        giCameraRunSingle("003", true);
        giWait(0.8);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：兽类修仙不易，动辄便要上千年，你如此行事，难道不怕遭天谴吗？！", "43577");
        giWait(0.5);
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：天谴？哈哈，可笑！我已是仙，难道还能将我打回兽形？", "43578");
        giWait(0.5);
        giPlayerDoAction(1, "J01", -1, false);
        giSetPortrait("104F", true);
        giTalk("韩菱纱：哎，说那么多干嘛！直接教训这臭狐狸，把夏书生和他女儿抢回来不就行了！", "43579");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giIMMBegin();
        giNpcSetAng("MN009", 244.0);
        giPlayerSetVisible(2, false);
        giCameraRunSingle("004", true);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：想抢？没那么容易～", "43580");
        giWait(0.5);
        giNpcSetDir("MN009", 170.0, true);
        giCameraRunSingle("005", false);
        giWait(0.8);
        giNpcDoAction("MN009", "X03", 1, false);
        giWait(0.5);
        giCameraWait();
        giEffectPlayWithNPC("H_099", 1, "MN006");
        giIMMBegin();
        giEffectPlayWithNPC("H_099", 1, "MN002");
        giEffectPlayWithNPC("H_099", 1, "MN003");
        giEffectPlayWithNPC("H_099", 1, "MN004");
        giEffectPlayWithNPC("H_099", 1, "MN005");
        giEffectPlayWithNPC("H_099", 1, "MN008");
        giNpcBlendOut("MN006", 2.0, false);
        giNpcBlendIn("MN002", 2.0, false);
        giNpcBlendIn("MN003", 2.0, false);
        giNpcBlendIn("MN004", 2.0, false);
        giNpcBlendIn("MN005", 2.0, false);
        giNpcBlendIn("MN008", 2.0, false);
        giIMMEnd();
        giWait(1.0);
        giNpcSetDir("MN009", 244.0, true);
        giWait(1.0);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：幻术？！", "43581");
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：我正闲着无聊，这下倒好，有人自己送上门来～", "43582");
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：可别说本大爷欺负人，要是你们能从这五个里面认出真的那一个，我就二话不说，放了夏元辰和他女儿！", "43583");
        giIMMBegin();
        giPlayerSetPos(1, 2186.3, 741.1, -3769.1);
        giPlayerSetAng(1, 80.0);
        giPlayerSetPos(2, 2215.7, 741.1, -3816.3);
        giPlayerSetAng(2, 74.0);
        giPlayerSetAng(0, 66.0);
        giPlayerSetAng(3, 88.0);
        giPlayerSetVisible(2, true);
        giCameraRunSingle("030", true);
        giIMMEnd();
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("102J", false);
        giTalk("云天河：要是认错了呢？", "43584");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：放心，最多变得和这蠢书生一般下场，被法术吞噬了～", "43585");
        giCameraRunSingle("009", true);
        giPlayerDoAction(1, "J15", -1, false);
        giSetPortrait("104I", false);
        giTalk("韩菱纱：可恶的臭狐狸！干脆把他打倒，法术自然破了！", "43586");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraRunSingle("008", false);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：等等……", "43587");
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：他再怎么说也是一方散仙，我们不知底细，不如……就先按他的规矩来。", "43588");
        giPlayerEndAction(2);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102C", false);
        giTalk("云天河：可是……这些人看起来都一模一样……", "43589");
        giPlayerEndAction(0);
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：哈哈～还是这小姑娘明事理。", "43590");
        giSetPortrait("B11A", true);
        giTalk("狐三太爷：我先说好，你们可别想和蠢书生的女儿讲话，这小鬼是个痴儿，笨得一塌糊涂，何况我给她施了定身术，她全身都动不了了～", "43591");
        giSetPortrait("105A", false);
        giTalk("慕容紫英：……", "43592");
        giPlayerDoAction(1, "J17", -1, false);
        giSetPortrait("104F", false);
        giTalk("韩菱纱：卑鄙！", "43593");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerWalkTo(2, 2292.1, 741.1, -3765.5, false);
        giWait(1.0);
        giIMMBegin();
        giNpcSetAng("MN009", 238.0);
        giCameraRunSingle("031", true);
        giIMMEnd();
        giPlayerEndMove(2);
        giPlayerSetAng(2, 56.0);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：狐仙，夏家公子到底和你有什么深仇大恨，你要这样害他？", "43594");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：此话差矣～我哪里害过他，不过是捉弄几下，谁让他把我们散仙的脸都丢光了！", "43595");
        giSetPortrait("105C", true);
        giTalk("慕容紫英：散仙？", "43596");
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：你们还不知？也难怪～这蠢书生太没用了，谁能想到他还是个山神～", "43597");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetPos(1, 2237.8, 741.1, -3769.0);
        giPlayerSetAng(1, 62.0);
        giPlayerSetPos(0, 2266.5, 741.1, -3834.6);
        giPlayerSetAng(0, 37.0);
        giPlayerSetPos(3, 2235.9, 741.1, -3729.2);
        giPlayerSetAng(3, 74.0);
        giPlayerSetPos(2, 2278.3, 741.1, -3773.7);
        giPlayerSetAng(2, 50.0);
        giNpcSetAng("MN009", 242.0);
        giCameraRunSingle("032", true);
        giIMMEnd();
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("104D", true);
        giTalk("韩菱纱：什么？！夏书生不是凡人？", "43598");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：你看，你也觉得吃惊吧？", "43599");
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：夏元辰明明是个山神，偏要装成凡人，和其他蠢老百姓混在一起，还收养了一个女儿，竟是白痴，岂不成了所有散仙的笑柄？", "43600");
        giSetPortrait("107A", true);
        giTalk("柳梦璃：他要如何过，却是他自己的事，和你无关吧！", "43601");
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：非也非也～他比我弱，又不自量力，每次都要坏我好事，我要捉弄谁，他偏要去替那人消灾，摆明是和我做对！", "43602");
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：今天我大寿，更是要教训教训他，才觉得说不出的舒心～", "43603");
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：山神身为地仙，庇护凡人，本是常理！你怎可如此？", "43604");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：少跟大爷我谈什么大道理，反正这书生又蠢又笨，养了个女儿也和他一样白痴，我就是看他不顺眼！", "43605");
        giWait(0.8);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：你才是愚不可及……", "43606");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giIMMBegin();
        giPlayerSetPos(1, 2236.3, 741.1, -3800.7);
        giPlayerSetAng(1, 89.0);
        giPlayerSetPos(2, 2281.5, 741.1, -3774.1);
        giPlayerSetAng(2, 104.0);
        giPlayerSetAng(0, 86.0);
        giPlayerSetAng(3, 112.0);
        giNpcSetAng("MN009", 242.0);
        giCameraRunSingle("033", true);
        giIMMEnd();
        giIMMBegin();
        giEffectAttachToPlayer(2, "H_TL03.2", false);
        giPlayerDoAction(2, "J12", 1, true);
        giIMMEnd();
        giEffectDetachFromPlayer(2);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(2, false);
        giCameraRunSingle("039", true);
        giIMMEnd();
        giWait(2.0);
        giNpcSetDir("MN009", 157.0, true);
        giWait(0.5);
        giIMMBegin();
        giEffectPlayWithNPC("H_TL03", 1, "MN002");
        giEffectPlayWithNPC("H_TL03", 1, "MN003");
        giEffectPlayWithNPC("H_TL03", 1, "MN004");
        giEffectPlayWithNPC("H_TL03", 1, "MN005");
        giEffectPlayWithNPC("H_TL03", 1, "MN008");
        giNpcBlendOut("MN002", 3.0, false);
        giNpcBlendOut("MN003", 3.0, false);
        giNpcBlendOut("MN004", 3.0, false);
        giNpcBlendOut("MN005", 3.0, false);
        giNpcBlendOut("MN008", 3.0, false);
        giNpcBlendIn("MN006", 3.0, true);
        giIMMEnd();
        giWait(2.0);
        giScriptMusicStop(0, 2.5);
        giScriptMusicPlay("P45", 2, 0.0, 2.5);
        giSetPortrait("B11B", false);
        giTalk("狐三太爷：……！", "43607");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(3, false);
        giPlayerSetVisible(2, true);
        giPlayerSetPos(2, 2292.1, 741.1, -3765.5);
        giPlayerSetAng(2, 56.0);
        giNpcSetAng("MN009", 250.0);
        giCameraRunSingle("031", true);
        giIMMEnd();
        giSetPortrait("B11B", false);
        giTalk("狐三太爷：不可能！你、你乱猜的？！", "43608");
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：我自然看不出来，是莲宝自己告诉我的。", "43609");
        giSetPortrait("B11B", false);
        giTalk("狐三太爷：这痴儿……她……", "43610");
        giSetPortrait("107A", true);
        giTalk("柳梦璃：我引你闲谈，不过是想看看你会不会露出破绽。没料到当你辱骂夏公子时，莲宝的眼里全是愤怒……她或许不如其他孩子聪明，但父女之情，却和旁人没有分别！", "43611");
        giSetPortrait("B11B", false);
        giTalk("狐三太爷：你使诈！这不算！", "43612");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetPos(0, 2266.5, 741.1, -3834.6);
        giPlayerSetAng(0, 37.0);
        giPlayerSetPos(1, 2237.8, 741.1, -3769.0);
        giPlayerSetAng(1, 62.0);
        giPlayerSetPos(2, 2278.3, 741.1, -3773.7);
        giPlayerSetAng(2, 50.0);
        giPlayerSetPos(3, 2235.9, 741.1, -3729.2);
        giPlayerSetAng(3, 74.0);
        giNpcSetAng("MN009", 242.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giCameraRunSingle("032", true);
        giIMMEnd();
        giWait(0.8);
        giPlayerDoAction(1, "J17", -1, false);
        giSetPortrait("104I", true);
        giTalk("韩菱纱：是你耍赖好不好！还不快把定身术解了！", "43613");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("B11A", false);
        giTalk("狐三太爷：休想！看本大爷收拾你们！", "43614");
        giSetFullHP();
        giSetFullMP();
        giFlashOutBlack(1.5, true, true);
        random_0_5 = giGetRandnum(0, 5);
        giAddCombatMonster(2589, random_0_5);
        giAddCombatMonster(2600, 0);
        giAddCombatMonster(2600, 0);
        giAddCombatMonster(2600, 0);
        giAddCombatMonster(2600, 0);
        giAddCombatMonster(2600, 0);
        giConfigCombatBgm("P45");
        giConfigCombatCamera("CA6");
        giConfigCombatGroundCamera("CA10");
        giConfigCombatParam(true, 0, 0, 0);
        giStartCombat("M13A");
        giScriptMusicPlay("P57", 2, 0.0, 0.0);
        giIMMBegin();
        giPlayerSetPos(1, 2236.9, 741.1, -3789.1);
        giPlayerSetAng(1, 58.0);
        giPlayerSetPos(0, 2266.5, 741.1, -3834.6);
        giPlayerSetAng(0, 57.0);
        giPlayerSetPos(2, 2272.5, 741.1, -3768.0);
        giPlayerSetAng(2, 79.0);
        giPlayerSetPos(3, 2240.2, 741.1, -3714.0);
        giPlayerSetAng(3, 107.0);
        giCameraRunSingle("034", true);
        giIMMEnd();
        giFlashInBlack(1.5, true);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("102J", false);
        giTalk("云天河：你输了！该听我们的话，把人放了吧？", "43615");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("B11C", true);
        giTalk("狐三太爷：凭、凭什么？！", "43616");
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("104J", false);
        giTalk("韩菱纱：嘻～那要不要再过两招？", "43617");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(1.2);
        giSetPortrait("B11C", true);
        giTalk("狐三太爷：慢～放就放！君子动口不动手！", "43618");
        giIMMBegin();
        giPlayerSetPos(1, 2228.7, 741.1, -3777.9);
        giPlayerSetAng(1, 35.0);
        giPlayerSetAng(0, 30.0);
        giPlayerSetAng(2, 31.0);
        giPlayerSetAng(3, 53.0);
        giNpcSetAng("MN009", 342.0);
        giCameraRunSingle("035", true);
        giIMMEnd();
        giWait(0.8);
        giNpcDoAction("MN009", "X03", 1, true);
        giIMMBegin();
        giSetObjectVisible("Jeffect001", true);
        giSetObjectVisible("Jeffect002", true);
        gi2DSoundPlay("WD001", 1);
        giIMMEnd();
        giWait(1.5);
        giIMMBegin();
        giSetObjectVisible("Jeffect001", false);
        giSetObjectVisible("Jeffect002", false);
        giIMMEnd();
        giWait(1.3);
        giIMMBegin();
        giPlayerSetPos(1, 2236.9, 741.1, -3789.1);
        giPlayerSetAng(1, 58.0);
        giPlayerSetPos(0, 2266.5, 741.1, -3834.6);
        giPlayerSetAng(0, 57.0);
        giPlayerSetPos(2, 2272.5, 741.1, -3768.0);
        giPlayerSetAng(2, 79.0);
        giPlayerSetPos(3, 2240.2, 741.1, -3714.0);
        giPlayerSetAng(3, 107.0);
        giNpcSetAng("MN009", 265.0);
        giCameraRunSingle("034", false);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("B11C", true);
        giTalk("狐三太爷：没、没我的事，我要走了……", "43619");
        giWait(0.5);
        giSetPortrait("105F", false);
        giTalk("慕容紫英：……念你乃是仙兽，千年修行不易，今日便放你一马，日后若再为恶，我定会散去你的功力，将你打回原形！", "43620");
        giWait(0.5);
        giSetPortrait("B11C", true);
        giTalk("狐三太爷：…………知、知道了……", "43621");
        giWait(0.5);
        giEffectPlayWithNPC("H_079", 1, "MN009");
        giNpcBlendOut("MN009", 1.5, true);
        giWait(0.8);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(2, false);
        giPlayerSetPos(1, 2170.7, 741.1, -3770.6);
        giPlayerSetAng(1, 32.0);
        giPlayerSetPos(3, 2190.2, 741.1, -3715.0);
        giPlayerSetAng(3, 189.0);
        giCameraRunSingle("036", true);
        giIMMEnd();
        giWait(1.0);
        giPlayerDoAction(1, "J16", 1, false);
        giWait(0.7);
        giSetPortrait("104B", false);
        giTalk("韩菱纱：小紫英，你好厉害哦！那只臭狐狸被你吓得浑身发抖呢。", "43622");
        giPlayerEndAction(1);
        giPlayerDoAction(3, "C09", 1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：……那不过是危言耸听，以防他再度为恶，其实仙兽纳日月之精华，炼成独一无二的内丹护体，又岂是我等凡人可以轻易将它打回原形的？", "43623");
        giPlayerEndAction(3);
        giNpcEndAction("MN010", true);
        giIMMBegin();
        giNpcSetAng("MN010", 222.0);
        giCameraRunSingle("022", true);
        giIMMEnd();
        giSetPortrait("220A", false);
        giTalk("夏元辰：这、这是……", "43624");
        giNpcWalkTo("MN006", 2366.0, 741.1, -3689.1, true);
        giNpcSetDir("MN006", 306.0, true);
        giSetPortrait("219A", true);
        giTalk("莲宝：爹爹……", "43625");
        giNpcSetDir("MN010", 138.0, true);
        giWait(0.5);
        giSetPortrait("220C", false);
        giTalk("夏元辰：莲宝！你让爹担心死了，有没有怎么样啊？", "43626");
        giWait(0.5);
        giSetPortrait("219A", true);
        giTalk("莲宝：爹爹……", "43627");
        giIMMBegin();
        giPlayerSetPos(0, 2235.0, 741.1, -3812.0);
        giPlayerSetAng(0, 16.0);
        giPlayerSetPos(3, 2193.8, 741.1, -3756.8);
        giPlayerSetAng(3, 43.0);
        giPlayerSetPos(1, 2251.5, 741.1, -3755.8);
        giPlayerSetAng(1, 36.0);
        giPlayerSetPos(2, 2301.2, 741.1, -3804.9);
        giPlayerSetAng(2, 2.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(2, true);
        giNpcSetPos("MN010", 2314.9, 741.1, -3683.5);
        giNpcSetAng("MN010", 113.0);
        giNpcSetPos("MN006", 2379.1, 741.1, -3709.1);
        giNpcSetAng("MN006", 290.0);
        giCameraRunSingle("023", true);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("107B", true);
        giTalk("柳梦璃：你放心，我们已经把狐仙赶跑了，莲宝她没受伤。", "43628");
        giNpcSetDir("MN010", 213.0, true);
        giSetPortrait("220B", false);
        giTalk("夏元辰：你们……太谢谢了！", "43629");
        giWait(0.5);
        giPlayerDoAction(1, "J16", 1, false);
        giSetPortrait("104M", true);
        giTalk("韩菱纱：嘻～想不到你还是个山神呢，真了不起！", "43630");
        giPlayerEndAction(1);
        giSetPortrait("220A", false);
        giTalk("夏元辰：……山神又如何……我连自己的女儿都保护不了……", "43631");
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("104A", true);
        giTalk("韩菱纱：哪有啊，我们都听臭狐狸说了，你就是因为帮过许多人，才会被他怨恨的！", "43632");
        giSetPortrait("104E", true);
        giTalk("韩菱纱：只可惜……等到真的出事了，那些人都不愿意帮忙……", "43633");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giNpcDoAction("MN010", "C09", 1, false);
        giSetPortrait("220A", false);
        giTalk("夏元辰：……不能怪他们，他们都是善良的好人，只不过人力有穷极之时，又怎能斗得过天地鬼神，会心生畏惧也在情理之中。", "43634");
        giNpcEndAction("MN010", true);
        giCameraRunSingle("024", true);
        giWait(0.5);
        giSetPortrait("219A", true);
        giTalk("莲宝：爹爹～", "43635");
        giWait(0.5);
        giSetPortrait("107B", true);
        giTalk("柳梦璃：夏公子，你女儿真的很依恋你呢，多亏有她，我们才能看穿狐仙的诡计。", "43636");
        giWait(0.5);
        giSetPortrait("220A", false);
        giTalk("夏元辰：…………", "43637");
        giWait(0.5);
        giIMMBegin();
        giNpcSetAng("MN010", 189.0);
        giCameraRunSingle("025", true);
        giIMMEnd();
        giCameraRunSingle("026", false);
        giWait(0.8);
        giSetPortrait("220A", false);
        giTalk("夏元辰：……你们也知道了吧，莲宝她和别的孩子不太一样，我只想让她少受些委屈……", "43638");
        giSetPortrait("220A", false);
        giTalk("夏元辰：原本我就打算带她离开即墨，游历五湖四海，但又放不下狐三的事……", "43639");
        giSetPortrait("220A", false);
        giTalk("夏元辰：如今狐三被你们打跑，我也可以安心离开了。", "43640");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("104A", true);
        giTalk("韩菱纱：我看那臭狐狸一副不甘心的样子，万一他再跑回来……", "43641");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giNpcDoAction("MN010", "C09", 1, false);
        giSetPortrait("220A", false);
        giTalk("夏元辰：狐三的性格就是欺软怕硬，如今吃了大亏，定会收敛许多。", "43642");
        giCameraRunSingle("037", true);
        giNpcEndAction("MN010", true);
        giSetPortrait("220A", false);
        giTalk("夏元辰：多谢各位相助，我这就带莲宝回去收拾收拾，明天一早动身。", "43643");
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：请等一下！", "43644");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giNpcSetDir("MN010", 253.0, true);
        giWait(0.6);
        giCameraRunSingle("038", false);
        giPlayerWalkTo(3, 2272.4, 741.1, -3697.2, true);
        giPlayerSetAng(3, 85.0);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：我们有一事请教，请问你是否知道光纪寒图这个东西？", "43645");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("220B", false);
        giTalk("夏元辰：……！你们为何要找那样东西？其质阴寒，对人并无益处……", "43646");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102A", true);
        giTalk("云天河：这个，一时也说不清，反正是要用来救人的～", "43647");
        giPlayerEndAction(0);
        giNpcSetDir("MN010", 214.0, true);
        giSetPortrait("220B", false);
        giTalk("夏元辰：……实不相瞒，光纪寒图正在我手中，诸位今日救我和莲宝，大恩大德，无以为报，那东西就送给你们好了。", "43648");
        giPlayerDoAction(1, "J02", 1, false);
        giSetPortrait("104A", true);
        giTalk("韩菱纱：真的吗？！", "43649");
        giPlayerEndAction(1);
        giNpcDoAction("MN010", "C08", 1, false);
        giSetPortrait("220A", false);
        giTalk("夏元辰：当然。", "43650");
        giSetPortrait("104B", true);
        giTalk("韩菱纱：多谢！嘻嘻，这真是好人有好报～", "43651");
        giWait(0.5);
        giSetPortrait("220A", false);
        giTalk("夏元辰：<colour red=255 green=187 blue=0 alpha=255>寒舍在即墨狐仙庙西南，</colour><dc0>诸位可走海边栈桥到达，我恭候各位到访。</dc0>", "43652");
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：好～～", "43653");
        giWait(0.5);
        giNpcDoAction("MN010", "J02", 1, true);
        giWait(0.8);
        giNpcWalkTo("MN010", 2360.2, 741.1, -3614.6, false);
        giNpcWalkTo("MN006", 2394.5, 741.1, -3617.8, true);
        giWait(2.0);
        giIMMBegin();
        giPlayerSetPos(3, 2314.1, 741.1, -3702.7);
        giPlayerSetAng(3, 194.0);
        giPlayerSetAng(1, 150.0);
        giPlayerSetAng(0, 79.0);
        giSetNpcVisible("MN010", false);
        giSetNpcVisible("MN006", false);
        giPlayerSetVisible(3, false);
        giCameraRunSingle("027", true);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：他们父女俩感情真好……", "43654");
        giPlayerDoAction(1, "J04", 1, false);
        giSetPortrait("104M", true);
        giTalk("韩菱纱：柳伯伯、柳伯母跟你不也很好～", "43655");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetDir(2, 325.0, true);
        giWait(0.6);
        giPlayerDoAction(2, "J13", 1, false);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：是啊，只要感情深笃，任何事情也不能妨碍心意相通。", "43656");
        giPlayerEndAction(2);
        giIMMBegin();
        giPlayerSetPos(0, 2289.2, 741.1, -3762.1);
        giPlayerSetAng(0, 29.0);
        giPlayerSetPos(1, 2242.5, 741.1, -3743.7);
        giPlayerSetAng(1, 85.0);
        giPlayerSetPos(2, 2278.3, 741.1, -3816.0);
        giPlayerSetAng(2, 30.0);
        giPlayerSetVisible(3, true);
        giCameraRunSingle("028", true);
        giIMMEnd();
        giSetPortrait("105A", true);
        giTalk("慕容紫英：我们下山去吧，早一刻拿到光纪寒图，便能早一刻安心。", "43657");
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("102B", false);
        giTalk("云天河：好。", "43658");
        giFlashOutBlack(1.5, true, true);
        giPlayerEndAction(0);
        giIMMBegin();
        giSetNpcVisible("MN010", false);
        giSetNpcVisible("MN006", false);
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerSetVisible(3, false);
        giMonsterSetHide("m13-07-01", true);
        giMonsterSetHide("trans13", true);
        giPlayerCurrentSetVisible(true);
        giPlayerCurrentSetPos(2289.2, 741.1, -3762.1);
        giPlayerCurrentSetAng(270.0);
        giCameraSetCollide(true);
        giCameraAutoSeek(true);
        giCameraSetMode(5, true);
        global_mvar = 90800; // 0x000162B0, 第二章 / 6-1-3.为祸一方 / 回到即墨
        giScriptMusicStop(1, 2.5);
        giShowSignpost();
        giSetObjectVisible("save3", true);
        giIMMEnd();
        giTimeScript(180.0, "func9001");
        giFlashInBlack(1.5, true);
        giPlayerUnLock();
    }
}

void func3001()
{
    if (global_mvar <= 140100 && npc_e == 1 /* 第三章 / 8-3-3.心愿 / 前往妖界 / 亘古神陵 */)
    {
        giMonsterStopPursuit();
        giTimeScriptTerminate();
        giHideGASkillObject();
        giPlayerLock();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giIMMBegin();
        giPlayerCurrentSetVisible(false);
        giMonsterSetHide("m13-01-03", false);
        giMonsterSetHide("m13-01-02", false);
        giMonsterSetHide("m13-01-05", false);
        giMonsterSetHide("m13-08-09", false);
        giMonsterSetHide("m13-01-06", false);
        giMonsterSetHide("m13-04-01", false);
        giMonsterSetHide("m13-04-02", false);
        giMonsterSetHide("m13-01-08", false);
        giMonsterSetHide("m13-01-09", false);
        giMonsterSetHide("m13-01-04", false);
        giMonsterSetHide("m13-01-07", false);
        giMonsterSetHide("trans05", false);
        giMonsterSetHide("trans02", false);
        giMonsterSetHide("trans03", false);
        giMonsterSetHide("trans04", false);
        giPlayerSetPos(0, 1256.6, 1.1, 1963.5);
        giPlayerSetAng(0, 32.0);
        giPlayerSetPos(1, 1236.9, -0.2, 1884.7);
        giPlayerSetAng(1, 44.0);
        giPlayerSetPos(3, 1175.5, 1.0, 1939.0);
        giPlayerSetAng(3, 42.0);
        giNpcSetPos("SN001", 1385.4, 1.1, 2115.4);
        giNpcSetAng("SN001", 314.0);
        giNpcSetPos("SN002", 1297.4, 1.1, 2197.6);
        giNpcSetAng("SN002", 138.0);
        giNpcSetPos("SN003", 1251.3, 1.1, 2212.1);
        giNpcSetAng("SN003", 130.0);
        giSetNpcVisible("SN001", true);
        giSetNpcVisible("SN002", true);
        giSetNpcVisible("SN003", true);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giIMMEnd();
        giCameraPrepare("ZI001");
        giCameraRunSingle("001", true);
        giCameraSetDistOptEnable(false);
        giArenaReady();
        giNpcDoAction("SN001", "J02", -1, false);
        giFlashInBlack(1.5, true);
        giCameraRunSingle("002", true);
        giTalk("道臻：道闰，你竟然还是执迷不悟！今日我便将这女妖投入锁妖塔中，令其魂飞魄散！！", "");
        giTalk("道闰：大哥，我求你！道闰这条命是你给的，如今还你，死不足惜！但是求你放过我的妻儿——", "");
        giWait(0.5);
        giCameraRunSingle("003", true);
        giWait(0.5);
        giTalk("道臻：混帐！！死到临头还念着这个妖孽！", "");
        giNpcDoAction("SN002", "C09", 1, false);
        giTalk("道闰：……她是妖也好，是什么也好，都是我的妻子！", "");
        giNpcSetDir("SN003", 112.0, true);
        giWait(0.3);
        giTalk("殷芙萝：相公，你不要丢下我和睿儿……合你我二人之力，未必不是他的对手——", "");
        giWait(0.5);
        giNpcSetDir("SN002", 272.0, false);
        giCameraRunSingle("004", true);
        giWait(0.5);
        giTalk("道闰：芙萝，不许胡言！你记得答应过我什么？！", "");
        giTalk("殷芙萝：我……", "");
        giTalk("道闰：即使我死了，你也不可伤害大哥、不可伤害任何蜀山弟子！", "");
        giTalk("殷芙萝：相公，你……你为什么要这样傻，你对他们有义，他们却对你无情……", "");
        giNpcSetDir("SN002", 140.0, true);
        giNpcWalkTo("SN002", 1324.2, 1.1, 2175.4, false);
        giCameraRunSingle("005", true);
        giNpcEndMove("SN002");
        giNpcDoAction("SN002", "J01", -1, false);
        giCameraRunSingle("006", false);
        giTalk("道闰：……大哥，我为一己私欲，起意盗取赤雪流珠丹，自知罪无可赦，能死在你手中，道闰并无怨怼，只求你念在昔日手足之情，放过芙萝和睿儿……", "");
        giTalk("道闰：芙萝虽是花妖，但从未害过人，睿儿尚且年幼，更是何辜……", "");
        giCameraRunSingle("007", true);
        giWait(0.5);
        giTalk("道臻：不争气的东西！你被这女妖迷得神魂颠倒，连孽种都有了，处处信她一面之辞！妖若不害人，那爹娘又是如何死的！", "");
        giTalk("道闰：大哥，人有善恶之分，妖也一样，芙萝不是你想的那样！", "");
        giWait(0.5);
        giNpcSetDir("SN001", 160.0, true);
        giTalk("道闰：我自幼受师父和你教诲，知道绝不可以不辨是非，芙萝若是心性邪恶，我一定已经亲手将她斩于剑下！盗取丹药也是我一人的主意，全部都是我的过错！", "");
        giTalk("道臻：………………", "");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giNpcSetPos("SN003", 1265.4, 1.1, 2201.1);
        giCameraRunSingle("008", true);
        giIMMEnd();
        giWait(0.5);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101H", false);
        giTalk("云天河：等一下！他叫你“大哥”，你们就是兄弟，兄弟怎么能杀来杀去！", "");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giNpcSetDir("SN001", 224.0, false);
        giNpcSetDir("SN003", 176.0, false);
        giCameraRunSingle("009", false);
        giPlayerWalkTo(1, 1292.9, -0.2, 1985.2, false);
        giPlayerWalkTo(3, 1228.0, 1.1, 2031.8, false);
        giWait(0.6);
        giPlayerWalkTo(0, 1272.1, 1.1, 2032.0, true);
        giPlayerSetAng(0, 52.0);
        giPlayerEndMove(3);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 44.0, false);
        giPlayerSetDir(3, 58.0, true);
        giTalk("道臻：是你们……", "");
        giPlayerDoAction(1, "C09", 1, false);
        giSetPortrait("103F", false);
        giTalk("韩菱纱：……其他门派的事，我们本来不该插手，可是……他是你的弟弟啊，难道人的性命还比不过一颗丹药？一定要他以死赎罪才罢休？", "");
        giWait(0.6);
        giTalk("道臻：…………", "");
        giSetPortrait("103F", false);
        giTalk("韩菱纱：……他和妖相恋，就算不容于世，只要不害到别人，又算什么大恶……", "");
        giTalk("道臻：到此为止！此事不须他人置喙！", "");
        giWait(0.5);
        giNpcSetDir("SN001", 306.0, true);
        giWait(0.5);
        giCameraRunSingle("010", true);
        giWait(0.6);
        giTalk("道臻：……起来。", "");
        giTalk("道闰：大哥？", "");
        giIMMBegin();
        giNpcSetPos("SN003", 1277.1, 1.1, 2175.1);
        giNpcSetAng("SN003", 130.0);
        giCameraRunSingle("011", true);
        giIMMEnd();
        giWait(0.5);
        giTalk("道臻：站起来！你自小脾气倔强，就算受师父的责骂也多半不肯低头，哼，今日竟为了一个女妖屈膝！", "");
        giNpcUnHoldAct("SN002");
        giNpcEndAction("SN002", true);
        giNpcSetAng("SN002", 148.0);
        giTalk("道闰：……", "");
        giTalk("道臻：接好！", "");
        giScriptMusicPlay("P26", 2, 0.0, 2.5);
        giOBJBlendIn("SO001", 1.5, true);
        giObjectDoAction("SO001", "OJ34", -1, false);
        giSetObjectVisible("SO001_J", true);
        giTalk("道闰：这是……", "");
        giTalk("殷芙萝：赤雪流珠丹！！", "");
        giWait(1.0);
        giSetObjectVisible("SO001_J", false);
        giOBJBlendOut("SO001", 1.5, true);
        giNpcSetDir("SN001", 184.0, true);
        giWait(0.5);
        giNpcDoAction("SN001", "J02", -1, false);
        giTalk("道臻：你当初胆大包天，想要盗取赤雪流珠丹，不正是因为那个孽种天生带毒，唯此丹药能解？！", "");
        giIMMBegin();
        giSetNpcVisible("SN002", false);
        giCameraRunSingle("012", true);
        giIMMEnd();
        giWait(0.5);
        giTalk("道臻：你盗丹未成，逃出门派，师父命我下山捉拿，却也给了我一颗赤雪流珠丹。", "");
        giTalk("道臻：他老人家吩咐，你若顽抗，则杀无赦，若是仍有悔心，知道自己错了……毕竟师徒一场，便将丹药给你，但你从此被逐出门墙，不再是蜀山弟子！", "");
        giTalk("道闰：怎么会……赤雪流珠丹……如此贵重之物，师父他老人家怎能作主？……", "");
        giNpcSetDir("SN001", 324.0, true);
        giWait(0.5);
        giTalk("道臻：放肆！师父自是禀明掌门，再交代于我，他为你煞费苦心，你竟心有怀疑！", "");
        giIMMBegin();
        giSetNpcVisible("SN002", true);
        giCameraRunSingle("013", true);
        giIMMEnd();
        giTalk("道闰：……不，大哥……我有愧于你和师父，有愧于其他同门，辜负你们对我的期许……", "");
        giTalk("道臻：住口！不许再喊我大哥，我没有你这样的弟弟！日后偶遇，只当不识！", "");
        giTalk("道臻：我今日信你之言，你最好从此隐姓埋名度日，若敢与这女妖有为恶之举，我定会亲手将你们杀了！", "");
        giTalk("道闰：……道闰不敢！道闰此生已经愧对太多人，唯有心怀感激、多行善事，才能对得起这番恩赐……", "");
        giWait(0.5);
        giNpcWalkTo("SN001", 1216.2, 1.1, 2097.0, false);
        giWait(1.7);
        giNpcSetDir("SN002", 214.0, false);
        giNpcSetDir("SN003", 202.0, false);
        giNpcEndMove("SN001");
        giNpcSetPos("SN001", 1145.2, 0.3, 1980.7);
        giIMMBegin();
        giPlayerSetAng(0, 224.0);
        giPlayerSetAng(1, 248.0);
        giPlayerSetAng(3, 222.0);
        giNpcWalkTo("SN001", 1132.9, -1.5, 1916.8, false);
        giCameraRunSingle("014", true);
        giIMMEnd();
        giTalk("道闰：……大哥——！", "");
        giNpcEndMove("SN001");
        giWait(2.3);
        giNpcWalkTo("SN001", 1147.6, 0.3, 1815.8, true);
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：……想不到……他虽然口口声声说要铲除叛徒，最后却是这样的结果……", "");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giTalk("道闰：……大哥他……从小就很疼我，小时候家中被妖袭击，要不是大哥挡在我面前，自己却受了重伤，我早就没命了……师父也很护着我，我闯了祸，他总是在掌门面前说情开脱……", "");
        giWait(0.5);
        giPlayerSetDir(1, 22.0, false);
        giPlayerSetDir(0, 28.0, false);
        giWait(0.5);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：……", "42783; 42993; 43015; 43178; 43305; 43307; 43312; 43592; 43697; 43822; 43865; 44083; 44108; 44113; 44175; 44552; 44633; 44896; 44975; 45086; 45373; 45403; 45502; 45522; 45748; 46353; 46355; 46372; 46379");
        giPlayerRunTo(3, 1147.6, 0.3, 1815.8, true);
        giPlayerSetVisible(3, false);
        giIMMBegin();
        giPlayerSetPos(0, 1239.4, 1.1, 2094.1);
        giPlayerSetAng(0, 28.0);
        giPlayerSetPos(1, 1292.0, 1.1, 2095.4);
        giPlayerSetAng(1, 22.0);
        giNpcSetPos("SN003", 1282.6, 1.1, 2212.0);
        giNpcSetAng("SN003", 154.0);
        giCameraRunSingle("015", true);
        giIMMEnd();
        giTalk("道闰：是我……是我欠他们太多太多了……", "");
        giTalk("殷芙萝：相公……", "");
        giWait(0.5);
        giNpcSetDir("SN002", 314.0, true);
        giWait(0.5);
        giNpcDoAction("SN002", "C09", 1, false);
        giTalk("道闰：……芙萝，我没有后悔，不管受再多的苦，我都不后悔和你在一起的……", "");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103A", true);
        giTalk("韩菱纱：你们……要是愿意的话，可以去巢湖水下的居巢国定居，在那儿人和妖也能共处，不像其他地方，总有那么多的争斗……", "");
        giPlayerDoAction(0, "C08", 1, false);
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giNpcSetDir("SN002", 214.0, false);
        giNpcSetDir("SN003", 194.0, false);
        giWait(0.8);
        giTalk("道闰：居巢国吗？……谢谢这位姑娘告知，我和芙萝正是想找一处远离尘世之地，把睿儿抚养长大。", "");
        giWait(1.0);
        giShowSignpost();
        giTimeScript(180.0, "func9001");
        giFlashOutBlack(1.5, true, true);
        giCameraRunSingle("001", true);
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giSetNpcVisible("SN002", false);
        giSetNpcVisible("SN003", false);
        npc_e = 2;
        giArenaLoad("Q09", "Q09", "", true);
    }
}

void func3002()
{
    giScriptMusicPlay("P35", 0, 0.0, 0.0);
    giMonsterStopPursuit();
    giHideGASkillObject();
    giTimeScriptTerminate();
    giPlayerLock();
    giCameraSetCollide(false);
    giCameraAutoSeek(false);
    giNpcSetPos("SN006", -2641.6, 11.3, 2471.6);
    giNpcSetAng("SN006", 162.0);
    giNpcSetPos("SN007", -2625.7, 8.4, 2435.4);
    giNpcSetAng("SN007", 338.0);
    giSetNpcVisible("SN006", true);
    giSetNpcVisible("SN007", true);
    giPlayerCurrentSetVisible(false);
    giPlayerSetPos(2, -2558.6, 0.1, 2649.7);
    giPlayerSetAng(2, 210.0);
    giSetObjectVisible("save1", false);
    giArenaReady();
    giMonsterSetHide("trans06", false);
    giMonsterSetHide("m13-04-05", false);
    giMonsterSetHide("m13-04-03", false);
    giMonsterSetHide("m13-08-06", false);
    giMonsterSetHide("m13-02-02", false);
    giCameraPrepare("ming001");
    giCameraRunSingle("001", true);
    giCGEffPlay(5);
    giFlashInWhite(1.5, true);
    giWait(1.0);
    giCameraRunSingle("002", false);
    giWait(6.0);
    giCameraRunSingle("003", true);
    giCameraRunSingle("004", false);
    giWait(0.5);
    giTalk("欧阳明珠：……相公，我爹和我娘真的是被山贼害死的？为什么……我总觉得这不是真的……", "");
    giTalk("厉江流：明珠，你怎么了？是身体不舒服吗？怎么又在胡思乱想呢？", "");
    giWait(0.5);
    giNpcDoAction("SN007", "C09", 1, false);
    giTalk("欧阳明珠：我……我做了一个梦，梦见有个人身上爬满了虫子，那些虫子都在吃他的身体，好可怕……最可怕的是，那个人……他好像是我爹……虽然我不记得见过他的脸……", "");
    giWait(0.5);
    giTalk("厉江流：明珠，那只是一个梦啊，不要想那么多了……我当初从山贼手中救下你时，你已经惊吓过度，失了记忆，又怎么还会梦见从前的事呢？", "");
    giNpcDoAction("SN007", "C09", 1, false);
    giTalk("欧阳明珠：我……我真的是欧阳明珠？为什么我每次想回忆一些事情，头就好痛，脾气也变得暴躁起来……", "");
    giWait(0.5);
    giTalk("厉江流：唉，小傻瓜，你胸口的玉佩上不是刻着这个名字吗？就算你不是她，那也只是一个称呼，你永远都是我的妻子，我会永远保护你的。", "");
    giTalk("欧阳明珠：相公……", "");
    giWait(1.2);
    giNpcSetDir("SN006", 32.0, false);
    giNpcSetDir("SN007", 18.0, false);
    giWait(0.5);
    giTalk("厉江流：什么人？！出来！", "");
    giIMMBegin();
    giPlayerSetVisible(2, true);
    giPlayerSetPos(2, -2599.3, 5.6, 2576.3);
    giCameraRunSingle("005", true);
    giIMMEnd();
    giSetPortrait("106A", true);
    giTalk("柳梦璃：……", "41250; 41592; 41824; 41879; 41939; 42103; 42309; 42571; 42820; 46024; 46044; 46111; 46119");
    giTalk("欧阳明珠：咦？真是难得……相公，我和你隐居在此，还从来没有外人来过呢。", "");
    giTalk("厉江流：你是谁？！为何会来这里？", "");
    giNpcSetDir("SN007", 346.0, true);
    giTalk("欧阳明珠：相公，你不要这么凶嘛，会吓着这位姑娘的……", "");
    giWait(0.6);
    giIMMBegin();
    giNpcSetPos("SN006", -2657.7, 13.5, 2467.7);
    giNpcSetAng("SN006", 48.0);
    giNpcSetAng("SN007", 330.0);
    giPlayerSetPos(2, -2610.5, 5.6, 2516.1);
    giPlayerSetAng(2, 196.0);
    giCameraRunSingle("006", true);
    giIMMEnd();
    giPlayerDoAction(2, "J01", -1, false);
    giSetPortrait("106A", false);
    giTalk("柳梦璃：……你，不知道自己在梦里吗？", "");
    giPlayerUnHoldAct(2);
    giPlayerEndAction(2);
    giNpcSetDir("SN007", 6.0, true);
    giTalk("欧阳明珠：什么？", "");
    giWait(0.5);
    giCameraRunSingle("007", true);
    giWait(0.5);
    giTalk("厉江流：住口！", "");
    giWait(0.5);
    giNpcSetDir("SN006", 152.0, true);
    giWait(0.3);
    giTalk("厉江流：明珠，天色不早，我们也该回家了。", "");
    giTalk("欧阳明珠：可是这位姑娘……", "");
    giTalk("厉江流：只是一个外人，不必理会。", "");
    giWait(0.5);
    giNpcSetDir("SN007", 330.0, true);
    giWait(0.3);
    giTalk("欧阳明珠：我……", "");
    giTalk("厉江流：你不听我的话了？", "");
    giNpcDoAction("SN006", "C08", 1, false);
    giTalk("欧阳明珠：好吧，我知道了，相公你做什么事，一向都有道理的。", "");
    giNpcEndAction("SN006", true);
    giCameraRunSingle("008", false);
    giNpcWalkTo("SN007", -2620.4, 6.2, 2317.3, false);
    giWait(0.8);
    giPlayerDoAction(2, "C07", -1, false);
    giSetPortrait("106A", false);
    giTalk("柳梦璃：等一下——", "");
    giNpcSetDir("SN006", 14.0, true);
    giTalk("厉江流：给我退——！！", "");
    giNpcDoAction("SN006", "J01", 1, false);
    giWait(0.5);
    giCameraRunSingle("009", false);
    gi2DSoundPlay("WE219", 1);
    giWait(0.25);
    giFlashOutWhite(0.4, true, false);
    giShowSignpost();
    giTimeScript(180.0, "func9001");
    giCameraWait();
    giCGEffStop();
    giPlayerUnHoldAct(2);
    giPlayerEndAction(2);
    giNpcEndAction("SN006", true);
    giSetNpcVisible("SN006", false);
    giSetNpcVisible("SN007", false);
    giPlayerSetVisible(2, false);
    giSetObjectVisible("save1", true);
    npc_g = 3;
    giArenaLoad("Q04", "CN22", "", true);
}

void func3003()
{
    if ((global_mvar < 120100 && global_mvar >= 100200 || global_mvar < 91300 && global_mvar >= 90100) && npc_g == 4 /* 第二章 / 7-2-3.相争难休 / 送寒器回琼华 */)
    {
        giPlayerLock();
        giMonsterStopPursuit();
        giFlashOutBlack(1.5, true, true);
        giTimeScriptTerminate();
        giIMMBegin();
        giHideGASkillObject();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerCurrentSetVisible(false);
        giPlayerSetPos(0, 2933.4, 1.1, 2029.8);
        giPlayerSetAng(0, 162.0);
        giPlayerSetPos(2, 2900.0, 1.1, 2019.3);
        giPlayerSetAng(2, 168.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(2, true);
        giMonsterSetHide("trans01", false);
        giMonsterSetHide("m13-04-05", false);
        giMonsterSetHide("trans07", false);
        giMonsterSetHide("trans06", false);
        giMonsterSetHide("m13-02-02", false);
        giMonsterSetHide("m13-04-08", false);
        giMonsterSetHide("m13-08-12", false);
        giSetObjectVisible("sound003", false);
        giIMMEnd();
        giCameraPrepare("ming002");
        giCameraRunSingle("001", true);
        giPlayerWalkTo(0, 2989.4, 1.1, 1874.1, false);
        giPlayerWalkTo(2, 2952.8, 1.1, 1855.5, false);
        giCameraRunSingle("002", false);
        giFlashInBlack(0.5, false);
        giPlayerEndMove(0);
        giPlayerDoAction(0, "J13", 1, true);
        giFlashOutBlack(0.5, true, true);
        giIMMBegin();
        giPlayerSetPos(0, 3083.0, 1.1, 1247.3);
        giPlayerSetAng(0, 136.0);
        giPlayerSetPos(2, 3065.2, 1.1, 1195.1);
        giPlayerSetAng(2, 128.0);
        giCameraRunSingle("004", true);
        giIMMEnd();
        giFlashInBlack(0.5, true);
        giWait(0.6);
        giSetPortrait("107G", false);
        giTalk("柳梦璃：这个法阵……我记得这种感觉，就是让欧阳小姐坠入沉睡的咒术！", "");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102C", true);
        giTalk("云天河：……？也就是说，我们把它打烂，那个女的就能醒过来？", "");
        giWait(0.5);
        giPlayerWalkTo(2, 3121.7, 1.1, 1161.1, false);
        giWait(0.6);
        giCameraRunSingle("005", true);
        giPlayerEndMove(2);
        giPlayerSetAng(2, 128.0);
        giWait(1.2);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：……这竟是极其罕见的“同殇”之阵！连施法之人自身都坠于梦中……做到如此地步，究竟是为了什么……", "");
        giWait(0.5);
        giPlayerSetDir(2, 316.0, true);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：云公子，此阵持有霸道咒力，惟有令施术之人露出一丝破绽，方有可能破解。", "");
        giPlayerDoAction(0, "J14", 1, false);
        giWait(0.3);
        giSetPortrait("102C", false);
        giTalk("云天河：那，到底要怎么做？", "");
        giWait(0.5);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：待我神体分离，魂魄入此咒术之中，用言语相激施术之人，他若是心有动摇，法阵就会出现些许异状，到那时，你便立刻以兵刃毁去漂浮的“咒珠”！", "");
        giWait(0.3);
        giCameraRunSingle("006", false);
        giSetPortrait("102A", false);
        giTalk("云天河：咒珠？是说这些圆球吗？好！我记下了。", "");
        giPlayerDoAction(2, "C08", 1, true);
        giWait(0.3);
        giPlayerSetDir(2, 106.0, true);
        giWait(0.6);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：梦影雾花，尽是虚空，因心想念动，方化生幻境，令吾～往～梦～之～中——", "");
        giEffectAttachToPlayer(2, "H_TL03.2", false);
        giPlayerDoAction(2, "J12", 1, true);
        giEffectDetachFromPlayer(2);
        giFlashOutWhite(2.5, true, true);
        giScriptMusicPlay("P35", 2, 0.0, 0.0);
        giIMMBegin();
        giPlayerSetPos(2, -944.2, 1.1, 2636.8);
        giPlayerSetAng(2, 238.0);
        giPlayerSetVisible(2, false);
        giNpcSetPos("SN006", -1028.4, 1.1, 2585.5);
        giNpcSetAng("SN006", 222.0);
        giNpcSetPos("SN007", -1176.0, 0.3, 2531.9);
        giNpcSetAng("SN007", 64.0);
        giSetNpcVisible("SN006", true);
        giCGEffPlay(5);
        giIMMEnd();
        giCameraRunSingle("007", true);
        giFlashInWhite(1.5, true);
        giCameraRunSingle("008", false);
        gi2DSoundPlay("WE219", 1);
        giWait(4.5);
        giCameraRunSingle("009", true);
        giPlayerBlendIn(2, 1.5, true);
        giWait(0.8);
        giNpcSetDir("SN006", 38.0, true);
        giTalk("厉江流：你，究竟何人？竟一再侵入此地？", "");
        giWait(0.5);
        giSetPortrait("107G", false);
        giTalk("柳梦璃：法阵环绕的凶煞之力与你周身的气如出一辙，是你……将欧阳小姐的魂识禁锢于梦中？", "");
        giPlayerDoAction(2, "J01", -1, false);
        giSetPortrait("107G", false);
        giTalk("柳梦璃：你可知自己施为之术诡异凶险，稍有不慎便会将她的身体一并毁去？！", "");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giNpcDoAction("SN006", "J03", -1, false);
        giWait(0.7);
        giSetObjectVisible("Jeffect008", true);
        gi2DSoundPlay("WE066", 0);
        giCameraRunSingle("010", false);
        giTalk("厉江流：不答我所问，是否想尝一尝万蚁噬体之苦？！", "");
        giCameraWait();
        giSetPortrait("107G", false);
        giTalk("柳梦璃：……万蚁噬体？欧阳老爷身故，是你所为？！", "");
        giTalk("厉江流：……！知道的似乎不少，留你不得！", "");
        giSetNpcVisible("SN007", true);
        giTalk("欧阳明珠：相公！住手！", "");
        giWait(0.3);
        gi2DSoundStop();
        giSetObjectVisible("Jeffect008", false);
        giWait(0.2);
        giNpcUnHoldAct("SN006");
        giNpcEndAction("SN006", true);
        giNpcSetDir("SN006", 252.0, true);
        giCameraRunSingle("011", true);
        giWait(0.8);
        giTalk("厉江流：明珠……", "");
        giNpcWalkTo("SN007", -1096.0, 0.3, 2564.6, false);
        giWait(0.6);
        giTalk("欧阳明珠：相公，你在做什么？是不是、是不是有事瞒我？", "");
        giNpcWalkTo("SN006", -1052.8, 1.1, 2577.9, false);
        giCameraRunSingle("012", true);
        giNpcEndMove("SN006");
        giNpcSetAng("SN006", 256.0);
        giTalk("厉江流：明珠，怎么又在胡思乱想了？你近来身体不适，还是多歇息为好。", "");
        giNpcDoAction("SN007", "C09", 1, false);
        giTalk("欧阳明珠：不对……我们在这里住了这么久，除了这位姑娘，从来也没有见过外人，这……这未免太不寻常……", "");
        giNpcEndAction("SN007", true);
        giNpcSetDir("SN007", 28.0, true);
        giWait(0.5);
        giTalk("欧阳明珠：还有，她刚才说的欧阳老爷是谁？是我爹爹对吗？！", "");
        giWait(0.5);
        giTalk("厉江流：明珠听话，你先回去歇下——", "");
        giNpcSetDir("SN007", 60.0, true);
        giTalk("欧阳明珠：……我不去，相公，你告诉我，是不是有什么东西……你一直在骗我？", "");
        giTalk("厉江流：……！！", "");
        giWait(0.5);
        giGOMTouch("Jeffect011");
        giCGEffPlay(1);
        giWait(0.05);
        giCGEffStop();
        giCGEffPlay(1);
        giWait(0.05);
        giCGEffStop();
        giCGEffPlay(1);
        giWait(0.05);
        giCGEffStop();
        giCGEffPlay(1);
        giWait(0.05);
        giCGEffStop();
        giCGEffPlay(1);
        giWait(3.5);
        giCGEffPlay(5);
        giNpcSetDir("SN006", 36.0, true);
        giTalk("厉江流：你——！！指使何人毁我法阵！", "");
        giNpcBlendOut("SN006", 1.5, true);
        giTalk("欧阳明珠：相公！我——", "");
        giNpcBlendOut("SN007", 1.5, true);
        giFlashOutWhite(1.5, true, true);
        giCGEffStop();
        giPlayerSetPos(2, 3104.5, 1.1, 1136.7);
        giPlayerSetAng(2, 100.0);
        giPlayerSetPos(0, 3080.6, 1.1, 1181.0);
        giPlayerSetAng(0, 92.0);
        giNpcSetPos("SN006", 3333.4, 1.1, 1149.4);
        giNpcSetAng("SN006", 168.0);
        giSetNpcVisible("SN006", true);
        giNpcSetPos("SN007", 3281.1, 1.1, 1100.2);
        giNpcSetAng("SN007", 204.0);
        giNpcDoAction("SN006", "J04", 0, false);
        giPlayerDoAction(0, "Z01", 0, false);
        giSetObjectVisible("SO003", false);
        giSetObjectVisible("Jeffect003", false);
        giSetObjectVisible("Jeffect004", false);
        giSetObjectVisible("Jeffect005", false);
        giSetObjectVisible("Jeffect006", false);
        giSetObjectVisible("Jeffect007", false);
        giWait(2.0);
        giCameraRunSingle("013", true);
        giFlashInWhite(1.5, true);
        giSetObjectVisible("Jeffect012", true);
        giWait(7.0);
        giSetObjectVisible("Jeffect012", false);
        giTalk("厉江流：可恨！", "");
        giWait(0.3);
        giPlayerEndAction(0);
        giWait(0.5);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：好霸道的咒术，咒珠毁了，竟然也只是有损法阵，却并没有将其彻底毁去…… ", "");
        giWait(0.5);
        giNpcBlendIn("SN007", 2.0, false);
        giWait(0.5);
        giNpcSetDir("SN007", 168.0, true);
        giWait(0.7);
        giNpcSetDir("SN007", 248.0, true);
        giWait(0.5);
        giTalk("欧阳明珠：…………这……这是哪里？……相公呢？……", "");
        giWait(0.5);
        giNpcEndAction("SN006", true);
        giNpcSetDir("SN006", 236.0, true);
        giWait(0.5);
        giTalk("厉江流：明珠……", "");
        giNpcSetDir("SN007", 46.0, true);
        giTalk("欧阳明珠：相公……", "");
        giTalk("欧阳明珠：不、不对！你不是……你的脸我见过……", "");
        giScriptMusicStop(0, 2.5);
        giScriptMusicPlay("P34", 2, 0.0, 0.0);
        giIMMBegin();
        giNpcSetPos("SN006", 3360.2, 1.1, 1160.7);
        giNpcSetAng("SN006", 240.0);
        giNpcSetPos("SN007", 3321.5, 1.1, 1115.2);
        giNpcSetAng("SN007", 46.0);
        giCameraRunSingle("014", true);
        giIMMEnd();
        giTalk("厉江流：…………", "");
        giWait(0.5);
        giTalk("欧阳明珠：……你……你是那一夜杀死爹爹的人！", "");
        giTalk("厉江流：明珠，莫要惊惶——", "");
        giNpcWalkTo("SN006", 3347.8, 1.1, 1147.1, true);
        giNpcSetAng("SN006", 243.0);
        giNpcBackTo("SN007", 3307.6, 1.1, 1104.4, true);
        giWait(0.5);
        giNpcDoAction("SN007", "C09", 1, false);
        giTalk("欧阳明珠：你到底是谁？怎可如此唤我？！", "");
        giTalk("欧阳明珠：……我的头、头好痛……", "");
        giPlayerWalkTo(2, 3175.1, 1.1, 1140.2, true);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("107A", false);
        giTalk("柳梦璃：欧阳小姐，你且定一定心神，过去九年你一直沉眠于梦境之中，如今初醒，神思难免混乱……", "");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giNpcSetDir("SN007", 278.0, true);
        giWait(0.5);
        giTalk("欧阳明珠：……沉眠于梦境？", "");
        giWait(0.3);
        giTalk("欧阳明珠：我……见过你，你又是谁？……", "");
        giSetPortrait("107A", false);
        giTalk("柳梦璃：……是钟伯托付我将你救醒——", "");
        giNpcWalkTo("SN007", 3291.0, 1.1, 1108.4, true);
        giTalk("欧阳明珠：钟伯？……他好吗？还有我娘，我娘怎么样了？", "");
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("107F", false);
        giTalk("柳梦璃：欧阳老爷过世，你又长眠不醒，令堂伤心过度，已经去了……", "");
        giTalk("欧阳明珠：……！娘……", "");
        giTalk("欧阳明珠：……这九年之间，我究竟做了什么……为什么、为什么会和杀父仇人在一起……", "");
        giWait(0.5);
        giTalk("厉江流：明珠，莫要乱了心神，你我如今皆是魂识之态，但你不明法术，切不可六神涣散，也不可步出法阵！", "");
        giNpcSetDir("SN007", 66.0, true);
        giCameraRunSingle("015", true);
        giPlayerSetVisible(2, false);
        giTalk("欧阳明珠：你、你是我杀父仇人！我为何要听你的？", "");
        giTalk("厉江流：……明珠，我杀你父亲是真，与你举案齐眉亦是真，对你情意若有半点虚假，但叫我受万蛊噬心而亡！", "");
        giTalk("欧阳明珠：…………厉江流……我记得在梦中你叫这个名字，你原原本本告诉我……这一切究竟是怎么回事？！为什么……最恨的仇人，却成了我最亲的枕边人！", "");
        giCameraRunSingle("016", false);
        giTalk("厉江流：……明珠，可还记得陈州城外的关帝庙？你曾经在那里帮过一个重伤之人……", "");
        giNpcDoAction("SN007", "C09", 1, false);
        giTalk("欧阳明珠：我……记不清了……", "");
        giWait(0.5);
        giTalk("厉江流：你自然记不清，那个时候的我蓬头垢面，身上满是脓疮，比最臭的乞丐还要脏。", "");
        giTalk("欧阳明珠：……！！", "");
        giNpcSetDir("SN006", 312.0, true);
        giWait(0.5);
        giTalk("厉江流：我从南疆来到中原，不慎被仇家暗算，侥幸逃脱却潦倒落魄，路人只当我快死了，偶尔扔下一些残羹冷炙。", "");
        giIMMBegin();
        giNpcSetAng("SN007", 50.0);
        giCameraRunSingle("017", true);
        giIMMEnd();
        giWait(0.5);
        giTalk("厉江流：哼，我厉江流是人，不是等着施舍的猪狗，“巫祝”的黑巫之术能咒杀活人于千里之外，怎堪受此羞辱？！", "");
        giTalk("欧阳明珠：难道你……！", "");
        giTalk("厉江流：不错，我将那些人全都杀了，一个不留！", "");
        giIMMBegin();
        giPlayerSetVisible(2, true);
        giPlayerSetAng(2, 96.0);
        giNpcSetAng("SN007", 60.0);
        giCameraRunSingle("018", true);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("107G", false);
        giTalk("柳梦璃：你怎能如此残忍？！他们不过是好心相助，何罪之有！", "");
        giTalk("厉江流：好心？在我看来，却是伪善，一样任我自生自灭！", "");
        giWait(0.5);
        giCameraRunSingle("019", false);
        giTalk("厉江流：……那么多人里，只有一个路过的女孩子，虽是千金小姐打扮，却不计较脏污，替我上药，还说要带我回家疗伤……", "");
        giTalk("厉江流：后来，她果然请人驾了马车前来……但我无论如何不想再以那副模样见她，于是藏身树后，心中默默记下这份恩德。", "");
        giWait(0.5);
        giTalk("欧阳明珠：……我……想起来了，钟伯驾了马车去关帝庙，你却已经不在了……我没有救到你，不必说什么恩德，但你、你为何要杀死爹爹？害我家破人亡！", "");
        giTalk("厉江流：……我修养半年，伤好了大半，有个中原人请我降蛊杀死他生意场上的对头，对方死得越痛苦，他付的报酬越高。", "");
        giTalk("欧阳明珠：难道、他要杀的人是爹爹？！", "");
        giTalk("厉江流：我对这种仇杀早已司空见惯，蛊毒附于人身，夜半催动，只消片刻便能让对方受尽苦楚而亡。", "");
        giTalk("欧阳明珠：…………", "");
        giTalk("厉江流：只因那次所用之蛊十分珍稀，我才会接近尸体想将之收回，即将功成，你却进到屋内——", "");
        giTalk("欧阳明珠：是啊，我看见爹爹死得那样惨……厉江流！你好狠的心肠、好毒辣的手段！", "");
        giWait(0.5);
        giNpcSetDir("SN006", 248.0, true);
        giWait(0.7);
        giTalk("厉江流：……那一刻，我已明白，念念不忘的女孩，永远不会再原谅我，永远都会将我当作她的仇人……", "");
        giWait(0.3);
        giTalk("厉江流：不能真正消去你的记忆，只好将你的魂魄禁于梦中，在梦里做一对恩爱夫妻，岂非胜过这许多仇怨？", "");
        giIMMBegin();
        giNpcSetPos("SN007", 3305.7, 1.1, 1126.6);
        giNpcSetAng("SN007", 60.0);
        giNpcSetAng("SN006", 224.0);
        giCameraRunSingle("020", true);
        giIMMEnd();
        giWait(0.3);
        giTalk("欧阳明珠：……恩爱不渝、缱绻情深……不过都是一场骗局，你骗得我好苦！", "");
        giTalk("厉江流：明珠，你不必如此看轻自己，我已说过，梦虽是幻，对你情意却绝无虚假。只恨我一时大意，竟让人损及此阵！", "");
        giNpcDoAction("SN007", "C09", 1, false);
        giTalk("欧阳明珠：你错了！就算梦醒之后再痛苦，我也感激这位姑娘让我不必在自欺中过一辈子！假的永远不可能变成真的！", "");
        giWait(0.5);
        giTalk("厉江流：……明珠，你若恨我，尽管杀了我，但你魂魄骤然被驱离梦中，须得尽快合于身体，否则会性命不保……让我帮你。", "");
        giWait(0.5);
        giTalk("欧阳明珠：……是了，你说过我们都是魂识之态，我不懂法术，千万不要踏出这个法阵，踏出了……又会怎样呢？", "");
        giWait(0.8);
        giNpcWalkTo("SN007", 3275.0, 1.1, 1088.8, true);
        giNpcSetDir("SN006", 220.0, true);
        giTalk("厉江流：明珠！你想做什么？！", "");
        giCameraRunSingle("021", false);
        giWait(0.5);
        giTalk("欧阳明珠：……厉江流，我虽恨你入骨，但不会杀你。你说自己是巫祝，咒杀别人易如反掌，如今，轮到你也尝一尝那种生不如死的滋味！", "");
        giSetPortrait("107E", false);
        giTalk("柳梦璃：……！", "41895; 44194; 46150");
        giWait(0.5);
        giNpcWalkTo("SN007", 3244.9, 1.1, 1052.9, false);
        gi2DSoundPlay("WE160", 1);
        giSetObjectVisible("Jeffect009", true);
        giWait(0.15);
        giFlashOutWhite(0.5, true, true);
        giNpcEndMove("SN007");
        giSetObjectVisible("Jeffect009", false);
        giTalk("欧阳明珠：唔…………", "");
        giTalk("厉江流：明珠——！！", "");
        giNpcSetPos("SN006", 3175.3, 1.1, 991.7);
        giNpcSetAng("SN006", 162.0);
        giNpcDoAction("SN006", "J02", 0, false);
        giNpcSetPos("SN007", 3172.7, 1.1, 990.5);
        giNpcSetAng("SN007", 154.0);
        giNpcDoAction("SN007", "J02", 0, false);
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(2, false);
        giCameraRunSingle("022", true);
        giFlashInWhite(1.5, false);
        giWait(0.5);
        giCameraRunSingle("023", false);
        giWait(5.9);
        giCameraRunSingle("024", true);
        giCameraRunSingle("025", false);
        giWait(0.5);
        giTalk("欧阳明珠：……我的魂……很快就要散了吧……", "");
        giTalk("厉江流：你、你为何要这么傻？！", "");
        giWait(0.5);
        giTalk("欧阳明珠：……这样……岂非比杀了你，更让你痛心百倍千倍！", "");
        giTalk("厉江流：这是何苦？！你死了，我一样不能独活，我们成亲之时，曾发誓定要同年同月同日死……", "");
        giWait(0.5);
        giTalk("欧阳明珠：……那都是梦，如今想来……不觉得可笑吗？", "");
        giTalk("厉江流：对我来说，却是真的，我厉江流一生只娶欧阳明珠一人。", "");
        giWait(0.5);
        giTalk("欧阳明珠：……厉江流……你想得太好了，我……不许你死，我要你活到阳寿尽时……每当想起这一刻，就受心如刀绞之苦……这……就是我对你最大的报复……", "");
        giTalk("厉江流：……！！", "");
        giWait(0.5);
        giTalk("欧阳明珠：……也不许……伤害那位姑娘和她的朋友……你我之事，不用牵扯他人…………", "");
        giWait(0.8);
        giTalk("厉江流：……好，明珠……我答应你不寻死，也不向别人寻仇，你可满意了？", "");
        giWait(0.8);
        giTalk("欧阳明珠：我……就要死了，一想到你还留在世间……日夜备受煎熬……我…………", "");
        giWait(0.8);
        giTalk("厉江流：……明珠，你如此决绝，论及心狠，我比不上你……", "");
        giWait(0.8);
        giTalk("欧阳明珠：………………相公…………", "");
        giTalk("厉江流：……你……叫我什么？！", "");
        giTalk("欧阳明珠：……轮回井边……我会等到你，才去投胎……这一辈子，究竟是恨你多一点、还是爱你多一点……到那个时候……我再……说与你听…………", "");
        giNpcSetEmotion("SN007", "306_by");
        giWait(0.8);
        giSetObjectVisible("Jeffect010", true);
        giNpcBlendOut("SN007", 1.5, true);
        giSetObjectVisible("Jeffect010", false);
        giIMMBegin();
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(2, true);
        giPlayerSetPos(0, 3090.7, 1.1, 1111.6);
        giPlayerSetAng(0, 148.0);
        giPlayerSetPos(2, 3110.5, 1.1, 1143.8);
        giPlayerSetAng(2, 160.0);
        giIMMEnd();
        giWait(0.5);
        giCameraRunSingle("028", true);
        giTalk("厉江流：…………", "");
        giPlayerDoAction(2, "C09", 1, false);
        giSetPortrait("107F", false);
        giTalk("柳梦璃：…………", "41148; 41280; 41565; 41633; 41841; 42212; 42587; 42590; 42914; 44013; 45478; 45540; 45975; 46103; 46152");
        giWait(0.6);
        giIMMBegin();
        giNpcDoAction("SN006", "C01", 1, false);
        giCameraRunSingle("029", true);
        giIMMEnd();
        giWait(1.0);
        giNpcSetDir("SN006", 326.0, true);
        giWait(1.2);
        giTalk("厉江流：…………", "");
        giWait(0.6);
        giPlayerWalkTo(0, 3102.5, 1.1, 1094.8, true);
        giPlayerDoAction(0, "Z01", 0, false);
        giSetPortrait("102I", false);
        giTalk("云天河：你想做什么？！", "");
        giTalk("厉江流：哼！虽恨不得将你们锉骨扬灰，但答应明珠的事，我一定会做到。", "");
        giNpcDoAction("SN006", "J01", 1, false);
        giTalk("厉江流：不过你二人此生若敢涉足南疆半步，休怪我无情！", "");
        giNpcEndAction("SN006", true);
        giNpcBlendOut("SN006", 2.5, true);
        giSetObjectVisible("SO002", false);
        giWait(0.8);
        giSetPortrait("102J", false);
        giTalk("云天河：……", "40185; 40365; 40671; 40744; 41093; 41330; 42664; 42960; 43288; 43444; 44023; 44283; 44290; 44345; 44415; 44425; 44554; 45013; 45223; 45349; 45372; 45391; 45948; 45978; 45980; 46135; 46191; 46199; 46270; 46336; 46450; 46587; 46787");
        giWait(0.5);
        giPlayerDoAction(0, "C01", 1, false);
        giWait(0.5);
        giCameraRunSingle("030", true);
        giSetPortrait("107F", false);
        giTalk("柳梦璃：……云公子，这一次我是否……做错了？若是让欧阳小姐继续沉于梦中，眼前这些也就不会发生……", "");
        giWait(0.5);
        giPlayerSetDir(0, 358.0, true);
        giWait(0.6);
        giSetPortrait("102J", true);
        giTalk("云天河：……梦璃，为什么喜欢一个人，还会恨他……这种事情，我不懂……可是，那个女的不是说要谢谢你吗？", "");
        giPlayerDoAction(2, "C09", 1, true);
        giPlayerSetDir(2, 200.0, true);
        giSetPortrait("107F", false);
        giTalk("柳梦璃：人死不能复生……无论欧阳小姐说了什么，她都不会再活过来了……", "");
        giSetPortrait("102J", true);
        giTalk("云天河：…………", "40120; 40328; 41095; 41282; 41413; 41449; 41494; 41759; 42155; 42164; 42425; 42728; 43233; 44244; 44326; 44347; 44623; 44642; 44661; 44834; 44838; 44921; 44966; 45198; 45224; 45230; 45272; 45274; 45353; 45356; 45358; 45360; 45827; 45897; 45928; 45982; 45986; 46003; 46010; 46016; 46220; 46407; 46505; 46507; 46538; 46776; 46778; 46868");
        giWait(0.5);
        giSetPortrait("107F", false);
        giTalk("柳梦璃：云公子，<colour red=255 green=187 blue=0 alpha=255>我想去陈州探望一下钟伯，</colour><dc0>欧阳小姐过世，他一定比任何人都来得伤心……</dc0>", "");
        giFlashOutBlack(1.5, true, true);
        giPlayerEndAction(0);
        giIMMBegin();
        giMonsterSetHide("trans01", true);
        giMonsterSetHide("m13-04-05", true);
        giMonsterSetHide("trans07", true);
        giMonsterSetHide("trans06", true);
        giMonsterSetHide("m13-02-02", true);
        giMonsterSetHide("m13-04-08", true);
        giMonsterSetHide("m13-08-12", true);
        giSetObjectVisible("sound003", true);
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(2, false);
        giPlayerCurrentSetVisible(true);
        giPlayerCurrentSetPos(2900.3, 1.1, 1409.6);
        giPlayerCurrentSetAng(346.0);
        giCameraSetCollide(true);
        giCameraAutoSeek(true);
        giCameraSetMode(5, true);
        npc_g = 5;
        giShowSignpost();
        giIMMEnd();
        giTimeScript(180.0, "func9001");
        giFlashInBlack(1.5, true);
        giScriptMusicStop(1, 2.5);
        giPlayerUnLock();
    }
}

void func7001()
{
    int leader_player_id = 0;
    int random_1_5 = 0;
    float random_1_360 = 0.0;
    int random_1_4 = 0;
    int local_6 = 0;

    giPlayerLock();
    giIMMBegin();
    var_wu = giPlayerCurrentGetPosX();
    var_feng = giPlayerCurrentGetPosY();
    var_zi = giPlayerCurrentGetPosZ();
    giIMMEnd();
    giCGEffPlay(9);
    giWait(1.5);
    giEffectPlayWithCurrentPlayer("H_121", 1);
    gi2DSoundPlay("wc005", 1);
    leader_player_id = giPlayerGetLeader();
    giPlayerBlendOut(leader_player_id, 0.5, true);
    giWait(0.5);
    giFlashOutBlack(1.5, true, true);
    giIMMBegin();
    random_1_5 = giGetRandnum(1, 5);
    if (random_1_5 <= 5)
    {
        if (random_1_360 >= 1)
        {
            giPlayerCurrentSetPos(16098.0, 0.3, -1179.4);
        }
    }
    random_1_360 = giGetRandnum(1, 360);
    giPlayerCurrentSetAng(random_1_360);
    random_1_4 = giGetRandnum(1, 4);
    if (random_1_4 <= 4)
    {
        if (local_6 >= 1)
        {
            giMonsterSetVisible("key01", true);
        }
    }
    giCameraSetMode(5, true);
    giCameraAutoSeek(true);
    giCameraSeekToPlayer();
    giFlushTailYAngle();
    giSetObjectVisible("calculagraphMst", true);
    giSetObjectVisible("calculagraphTheOne", true);
    giIMMEnd();
    giWait(1.0);
    giFlashInBlack(1.5, false);
    giWait(0.5);
    giEffectPlayWithCurrentPlayer("H_122", 1);
    gi2DSoundPlay("wc006", 1);
    giWait(0.2);
    giPlayerBlendIn(leader_player_id, 0.5, false);
    giWait(1.2);
    giCGEffStop();
    if (giGetVisibleObject("flag"))
    {
        giShowCommonDialog("洞中的传送阵被特殊妖怪控制，杀死它能够重新打开传送阵，返回地面。", 0.5, 0.5);
    }
    giPlayerUnLock();
}

void func7002()
{
    int leader_player_id = 0;
    float random_1_360 = 0.0;

    if (giGetVisibleObject("eff01"))
    {
        giPlayerLock();
        giCGEffPlay(9);
        giWait(1.5);
        leader_player_id = giPlayerGetLeader();
        giPlayerBlendOut(leader_player_id, 0.5, false);
        giEffectPlayWithCurrentPlayer("H_121", 1);
        gi2DSoundPlay("wc005", 1);
        giWait(1.0);
        giFlashOutWhite(1.5, true, true);
        giIMMBegin();
        giPlayerCurrentSetPos(var_wu, var_feng, var_zi);
        random_1_360 = giGetRandnum(1, 360);
        giPlayerCurrentSetAng(random_1_360);
        giCameraSetMode(5, true);
        giCameraAutoSeek(true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        giIMMEnd();
        giWait(1.0);
        giFlashInWhite(1.5, false);
        giIMMBegin();
        giSetObjectVisible("eff02", false);
        giSetObjectVisible("eff04", false);
        giSetObjectVisible("eff03", false);
        giSetObjectVisible("eff01", false);
        giMonsterSetVisible("key01", false);
        giMonsterSetVisible("key02", false);
        giMonsterSetVisible("key03", false);
        giMonsterSetVisible("key04", false);
        giSetObjectVisible("calculagraphMst", false);
        giSetObjectVisible("calculagraphTheOne", false);
        giIMMEnd();
        giWait(0.5);
        giEffectPlayWithCurrentPlayer("H_122", 1);
        gi2DSoundPlay("wc006", 1);
        giWait(0.2);
        giPlayerBlendIn(leader_player_id, 0.5, false);
        giWait(1.2);
        giCGEffStop();
        giPlayerUnLock();
    }
}

void func7003()
{
    bool key01_visible = false;
    bool key02_visible = false;
    bool key03_visible = false;
    bool key04_visible = false;
    bool flag_visible = false;

    giIMMBegin();
    key01_visible = giGetVisibleMonster("key01");
    key02_visible = giGetVisibleMonster("key02");
    key03_visible = giGetVisibleMonster("key03");
    key04_visible = giGetVisibleMonster("key04");
    flag_visible = giGetVisibleObject("flag");
    giSetObjectVisible("calculagraphTheOne", false);
    giIMMEnd();
    if (!flag_visible || giGetVisibleMonster("key01") || key02_visible || key03_visible || key04_visible)
    {
        if (!flag_visible)
        {
            giIMMBegin();
            giSetObjectVisible("eff02", true);
            giSetObjectVisible("eff04", true);
            giSetObjectVisible("eff03", true);
            giSetObjectVisible("eff01", true);
            giIMMEnd();
            gi2DSoundPlay("we044", 1);
            giWait(3.0);
            gi2DSoundPlay("we170", 1);
        }
    }
    else
    {
        giPlayerLock();
        giCameraPrepare("viewwEff");
        giCameraRunSingle("viewEff_1", true);
        giCameraRunSingle("viewEff_2", false);
        gi2DSoundPlay("we044", 1);
        giSetObjectVisible("eff02", true);
        giWait(0.8);
        giSetObjectVisible("eff04", true);
        giWait(0.8);
        giSetObjectVisible("eff03", true);
        giWait(1.4);
        gi2DSoundPlay("we170", 1);
        giSetObjectVisible("eff01", true);
        giSetObjectVisible("flag", false);
        giWait(3.0);
        giIMMBegin();
        giCameraSetMode(5, true);
        giCameraAutoSeek(true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        giIMMEnd();
        giPlayerUnLock();
    }
}

void func7004()
{
    bool m13_09_01_visible = false;
    bool m13_09_02_visible = false;
    bool m13_09_03_visible = false;
    bool m13_09_04_visible = false;

    m13_09_01_visible = giGetVisibleMonster("m13-09-01");
    m13_09_02_visible = giGetVisibleMonster("m13-09-02");
    m13_09_03_visible = giGetVisibleMonster("m13-09-03");
    m13_09_04_visible = giGetVisibleMonster("m13-09-04");
    if (!giGetVisibleMonster("m13-09-01"))
    {
        giMSTBlendIn("m13-09-01", 1.5, false);
    }
    if (!m13_09_02_visible)
    {
        giMSTBlendIn("m13-09-02", 1.5, false);
    }
    if (!m13_09_03_visible)
    {
        giMSTBlendIn("m13-09-03", 1.5, false);
    }
    if (!m13_09_04_visible)
    {
        giMSTBlendIn("m13-09-04", 1.5, false);
    }
}

void func7005()
{
    bool key01_visible = false;
    bool key02_visible = false;
    bool key03_visible = false;
    bool key04_visible = false;
    int random_1_4 = 0;
    int local_7 = 0;

    key01_visible = giGetVisibleMonster("key01");
    key02_visible = giGetVisibleMonster("key02");
    key03_visible = giGetVisibleMonster("key03");
    key04_visible = giGetVisibleMonster("key04");
    if (giGetVisibleMonster("key01"))
    {
        giMSTBlendOut("key01", 1.5, false);
    }
    if (!key02_visible)
    {
        giMSTBlendOut("key02", 1.5, false);
    }
    if (!key03_visible)
    {
        giMSTBlendOut("key03", 1.5, false);
    }
    if (!key04_visible)
    {
        giMSTBlendOut("key04", 1.5, false);
    }
    giWait(5.0);
    random_1_4 = giGetRandnum(1, 4);
    if (random_1_4 <= 4)
    {
        if (local_7 >= 1)
        {
            giMSTBlendIn("key01", 1.5, false);
        }
    }
}

void func9001()
{
    string local_1 = "";
    int local_3 = 0;
    bool item202_visible = false;
    string local_5 = "";

    local_1 = "item";
    giIMMBegin();
    while (local_3 <= 99)
    {
        local_1 = "item";
        if (local_3 >= 10)
        {
            local_1 = "item" + "20" + "2";
        }
        else
        {
            local_1 = "item" + "20";
        }
        local_5 = "item" + "20" + "2";
        item202_visible = giGetVisibleObject("item" + "20" + "2");
        if (!giGetVisibleObject(local_5))
        {
            local_5 = "item" + "20" + "2";
            giGOBReset("item" + "20" + "2");
            local_5 = "item" + "20" + "2";
            giSetObjectVisible("item" + "20" + "2", true);
        }
        local_3 = local_3 + 1;
    }
    giIMMEnd();
}
