// Structured PAL4 reconstruction for Q08.csb
// Only simple if / if-else candidates backed by CFG evidence are folded.

void Q08_Q08_init()
{
    if (global_mvar != 160200 /* 第四章 / 9-3-2.君莫思归 / 再访长老 / 生离之痛 */)
    {
        giArenaReadyRestore();
    }
    else
    {
        giSetNpcVisible("MN001", true);
        giSetNpcVisible("MN002", true);
        giNpcSetPos("MN001", 210.0, -2.2, -361.5);
        giNpcSetAng("MN001", 320.0);
        giNpcSetPos("MN002", 154.6, -2.2, -305.0);
        giNpcSetAng("MN002", 216.0);
        giNpcDoAction("MN002", "J02", 0, false);
        giArenaReadyRestore();
    }
    if (global_mvar < 90100 /* 第二章 / 5-3-3.三寒器 / 前往即墨 / 三件寒器 */)
    {
        giSetObjectVisible("entrance0", false);
        giSetObjectVisible("entrance1", true);
        giArenaReadyRestore();
    }
    else
    {
        giSetObjectVisible("entrance0", true);
        giSetObjectVisible("entrance1", false);
        giArenaReadyRestore();
    }
}

void func1001()
{
    int select_dialog_last_select = 0;
    int leader_player_id = 0;

    if (global_mvar < 90100 /* 第二章 / 5-3-3.三寒器 / 前往即墨 / 三件寒器 */)
    {
        giArenaLoad("M12", "1", "", true);
        giPlayerCurrentSetPos(-2759.4, 0.2, -1534.2);
        giPlayerCurrentSetAng(85.0);
        giCameraSetMode(5, true);
        giArenaReady();
    }
    else
    {
        giPlayerLock();
        giSelectDialogAddItem("1.去醉花荫  ");
        giSelectDialogAddItem("2.御剑飞行  ");
        giSelectDialogAddItem("3.什么都不做");
        giSelectDialogSetDefaultSelect(2);
        giShowSelectDialog("   准备<colour red=255 green=102 blue=0 alpha=255>去醉花荫</colour><dc0>还是</dc0><colour red=255 green=102 blue=0 alpha=255>御剑飞行</colour><dc0>？</dc0>");
        select_dialog_last_select = giSelectDialogGetLastSelect();
        if (select_dialog_last_select != 0)
        {
            if (select_dialog_last_select != 1)
            {
                leader_player_id = giPlayerGetLeader();
                giPlayerWalkTo(leader_player_id, 487.5, -516.4, 1706.7, true);
                giPlayerSetDir(leader_player_id, 136.0, true);
                giCameraAutoSeek(true);
                giCameraSetMode(0, true);
                giPlayerUnLock();
            }
            else
            {
                giShowWorldMap();
            }
        }
        else
        {
            giArenaLoad("M12", "1", "", true);
            giPlayerCurrentSetPos(-2759.4, 0.2, -1534.2);
            giPlayerCurrentSetAng(85.0);
            giCameraSetMode(5, true);
            giArenaReady();
        }
        giPlayerUnLock();
    }
}

void func1002()
{
    giPlayerLock();
    giPlayerWalkTo(0, 651.5, -0.7, -536.6, true);
    giPlayerCurrentSetAng(270.0);
    giSetPortrait("102A", true);
    giTalk("云天河：房门锁住了……", "");
    giPlayerUnLock();
}

void func1003()
{
    giPlayerLock();
    giPlayerWalkTo(0, 236.9, -0.7, -411.2, true);
    giPlayerCurrentSetAng(180.0);
    giSetPortrait("102A", true);
    giTalk("云天河：房门锁住了……", "");
    giPlayerUnLock();
}

void func2004()
{
    if (global_mvar >= 160400 /* 第四章 / 9-4-1.步虚词终 / 重回青鸾峰 */)
    {
        giPlayerLock();
        giPlayerWalkTo(0, -26.0, -21.0, -9.8, true);
        giPlayerCurrentSetAng(0.0);
        giSetPortrait("101C", true);
        giTalk("云天河：不要去打扰青阳长老了……", "");
        giPlayerUnLock();
    }
    else
    {
        func2001();
        func2002();
        func2003();
    }
}

void func2001()
{
    if (global_mvar == 81100 /* 寻访长老 */)
    {
        giPlayerLock();
        giSetObjectVisible("sound004", false);
        giFlashOutBlack(1.5, true, true);
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerSetPos(0, 90.8, -2.3, -223.8);
        giPlayerSetAng(0, 131.0);
        giPlayerSetPos(1, 26.4, -2.2, -228.0);
        giPlayerSetAng(1, 106.0);
        giPlayerSetPos(2, 95.9, -2.6, -151.1);
        giPlayerSetAng(2, 111.0);
        giPlayerSetPos(3, 120.0, -2.6, -176.1);
        giPlayerSetAng(3, 131.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(2, true);
        giPlayerSetVisible(3, true);
        giCameraPrepare("MC001");
        giCameraRunSingle("001", true);
        giPlayerWalkTo(0, 178.7, -2.2, -316.0, false);
        giWait(0.5);
        giPlayerWalkTo(3, 228.3, -2.2, -259.5, false);
        giCameraRunSingle("003", false);
        giWait(0.5);
        giPlayerWalkTo(1, 163.2, -2.2, -273.2, false);
        giWait(0.5);
        giPlayerWalkTo(2, 197.6, -2.2, -211.2, false);
        giFlashInBlack(1.5, false);
        giPlayerEndMove(0);
        giPlayerEndMove(3);
        giPlayerSetDir(0, 114.0, false);
        giPlayerSetDir(3, 168.0, false);
        giPlayerEndMove(1);
        giPlayerEndMove(2);
        giPlayerSetDir(1, 138.0, false);
        giPlayerSetDir(2, 160.0, true);
        giCameraWait();
        giPlayerDoAction(0, "J13", -1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：喂～～这里有人吗？", "43447");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giCameraRunSingle("004", false);
        giPlayerSetDir(3, 204.0, true);
        giWait(0.6);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：不得失礼。", "43448");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giPlayerSetDir(3, 169.0, true);
        giWait(1.0);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：弟子慕容紫英，有要事前来求见二位长老。", "43449");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giCameraRunSingle("002", true);
        giWait(1.5);
        giTalk("青阳：是掌门夙瑶命你来的？", "43450");
        giWait(0.3);
        giTalk("青阳：掌门治派有方，我二人又隐退已久，再没有任何事情能够帮她，你回去吧。", "43451");
        giSetPortrait("105A", false);
        giTalk("慕容紫英：并非掌门，而是玄霄师叔命我们来的。", "43452");
        giTalk("重光：玄霄？！", "43453");
        giScriptMusicPlay("P26", 2, 0.0, 0.0);
        giCameraRunSingle("005", true);
        giEffectPlayWithNPC("H_097", 1, "MN002");
        giNpcBlendIn("MN002", 1.5, false);
        giEffectPlayWithNPC("H_097", 1, "MN001");
        giNpcBlendIn("MN001", 1.5, true);
        giWait(1.0);
        giSetPortrait("218A", false);
        giTalk("重光：你！刚才说的的确是玄霄？", "43454");
        giIMMBegin();
        giPlayerSetPos(0, 171.8, -2.2, -382.3);
        giPlayerSetAng(0, 140.0);
        giPlayerSetPos(1, 161.7, -2.2, -339.6);
        giPlayerSetAng(1, 150.0);
        giPlayerSetPos(2, 229.0, -2.2, -291.6);
        giPlayerSetAng(2, 182.0);
        giPlayerSetPos(3, 220.1, -2.2, -337.3);
        giPlayerSetAng(3, 182.0);
        giIMMEnd();
        giCameraRunSingle("007", true);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：是，弟子不敢有所欺瞒！", "43455");
        giSetPortrait("217A", false);
        giTalk("青阳：你们这些后辈弟子，又如何会见到玄霄？", "43456");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102A", true);
        giTalk("云天河：是我……我们偷偷跑去禁地，然后就认识他了～", "43457");
        giPlayerEndAction(0);
        giNpcSetDir("MN001", 354.0, false);
        giNpcSetDir("MN002", 319.0, true);
        giSetPortrait("217A", false);
        giTalk("青阳：天青？！你怎么……", "43458");
        giSetPortrait("218A", false);
        giTalk("重光：青阳，你看清楚，他并非云天青，不过是容貌相似罢了。", "43459");
        giIMMBegin();
        giNpcSetAng("MN001", 20.0);
        giNpcSetAng("MN002", 358.0);
        giPlayerSetAng(3, 166.0);
        giCameraRunSingle("013", true);
        giIMMEnd();
        giSetPortrait("107A", true);
        giTalk("柳梦璃：二位长老也认识云叔……云天青吗？", "43460");
        giWait(0.5);
        giNpcDoAction("MN001", "C08", 1, false);
        giSetPortrait("217A", false);
        giTalk("青阳：派中弟子，我们怎会不识……", "43461");
        giNpcEndAction("MN001", false);
        giSetPortrait("218A", false);
        giTalk("重光：闲话休提，玄霄差你们前来，必是有大事，快快说出！", "43462");
        giIMMBegin();
        giNpcSetAng("MN001", 353.0);
        giNpcSetAng("MN002", 305.0);
        giPlayerSetVisible(3, false);
        giCameraRunSingle("009", true);
        giIMMEnd();
        giSetPortrait("102A", true);
        giTalk("云天河：哦……玄霄他被封在冰里，现在想要出来了。", "43463");
        giSetPortrait("217A", false);
        giTalk("青阳：……！！", "43464");
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("102A", true);
        giTalk("云天河：不过还需要三件天下最阴寒的东西帮他抑制身体阳气，他说只有长老才知道哪里能找到。", "43465");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("218A", false);
        giTalk("重光：……玄霄看来如何？他竟有十足把握能破冰而出？！", "43466");
        giSetPortrait("102C", true);
        giTalk("云天河：啊？什么如何？", "43467");
        giPlayerDoAction(0, "J17", -1, false);
        giSetPortrait("102A", true);
        giTalk("云天河：好好一个人，被关上那么多年，肯定很郁闷，要是我的话，一个月也受不了……", "43468");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("218A", false);
        giTalk("重光：玄霄体内烈阳纵横，单靠几件寒器，怎可能压得住？", "43469");
        giSetPortrait("102A", true);
        giTalk("云天河：他说练了一种叫作“凝冰诀”的功夫，已经好很多了，要那三样东西，也是为了以防万一。", "43470");
        giSetPortrait("218A", false);
        giTalk("重光：……凝冰诀…………", "43471");
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：嗯，凝冰诀！我也练了一点点。", "43472");
        giPlayerEndAction(0);
        giSetObjectVisible("Jeffect002", true);
        giSetPortrait("218A", false);
        giTalk("重光：……", "43473");
        giNpcDoAction("MN002", "C07", -1, false);
        giWait(1.0);
        giNpcUnHoldAct("MN002");
        giNpcEndAction("MN002", true);
        giSetPortrait("218A", false);
        giTalk("重光：初学凝冰诀便有此等阴寒之气，玄霄修练多年，看来的确有把握！", "43474");
        giSetPortrait("218A", false);
        giTalk("重光：……只是你不似玄霄体内烈阳纵横，修练凝冰诀竟不会觉得阴寒难耐？", "43475");
        giSetObjectVisible("Jeffect002", false);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：不觉得……", "43476");
        giSetPortrait("218A", false);
        giTalk("重光：嗯……", "43477");
        giSetPortrait("217A", false);
        giTalk("青阳：这委实太过惊人……以短短十九年，便能抑制体内阳气，玄霄当真是个不世出的奇才，可叹造化弄人，当年偏偏落到被冰封的下场…", "43478");
        giWait(0.3);
        giPlayerSetDir(0, 153.0, true);
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：他个性素来孤傲，从不向人求助，今日既已相托，我和重光自当尽力帮忙。", "43479");
        giIMMBegin();
        giPlayerSetVisible(3, true);
        giPlayerSetAng(3, 184.0);
        giCameraRunSingle("007", true);
        giIMMEnd();
        giSetPortrait("217A", false);
        giTalk("青阳：……这位小兄弟，你可是云天青和夙玉的儿子？", "43480");
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：是啊。", "43481");
        giPlayerEndAction(0);
        giWait(0.3);
        giSetPortrait("217A", false);
        giTalk("青阳：……这，或许都是天意吧……", "43482");
        giSetPortrait("102A", true);
        giTalk("云天河：……？", "43483");
        giNpcSetDir("MN001", 20.0, true);
        giSetPortrait("217A", false);
        giTalk("青阳：看你背上剑匣，你可是宗炼的传人？", "43484");
        giWait(0.5);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：宗炼长老乃是弟子师公。", "43485");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("217A", false);
        giTalk("青阳：果然，想必你的铸剑秘术已尽得宗炼真传，假以时日，或许又是一个可以铸就羲和剑、望舒剑之人。", "43486");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：羲和、望舒……？", "43487");
        giSetPortrait("217A", false);
        giTalk("青阳：望舒便是这位小兄弟所持之剑，而羲和则是玄霄佩剑。", "43488");
        giSetPortrait("105D", true);
        giTalk("慕容紫英：……！天河的剑，竟是本门之物？！还是由师公所铸？！", "43489");
        giSetPortrait("217A", false);
        giTalk("青阳：……也不算他一人所铸……你还是莫要再多问了，不过是些烟云旧事罢了。", "43490");
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：……弟子不明，既然望舒剑是本门之物，掌门为何不索回？", "43491");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("218A", false);
        giTalk("重光：她上回不拿，并不表示永远不拿。", "43492");
        giSetPortrait("102E", true);
        giTalk("云天河：哦……她果然就是小气……", "43493");
        giWait(0.5);
        giIMMBegin();
        giNpcSetAng("MN002", 338.0);
        giNpcSetAng("MN001", 12.0);
        giPlayerSetAng(3, 166.0);
        giPlayerSetAng(0, 134.0);
        giPlayerSetAng(1, 138.0);
        giPlayerSetAng(2, 160.0);
        giCameraRunSingle("013", false);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：……这位紫衣姑娘气色不佳，灵力又是你们之中最弱的……", "43494");
        giNpcSetDir("MN001", 86.0, true);
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：重光，我看不如由你传授她一套心法，让她自行修炼吧。", "43495");
        giWait(0.5);
        giNpcDoAction("MN002", "C08", 1, false);
        giSetPortrait("218A", false);
        giTalk("重光：……也好。", "43496");
        giNpcEndAction("MN002", false);
        giNpcSetDir("MN001", 28.0, false);
        giPlayerDoAction(1, "J16", -1, false);
        giSetPortrait("104B", true);
        giTalk("韩菱纱：是说我吗？要教我心法？嘻嘻，太谢谢了！", "43497");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("218A", false);
        giTalk("重光：口诀我只说一遍，你听好！", "43498");
        giWait(0.5);
        giFlashOutBlack(1.5, true, true);
        giPlayerSetPos(1, 224.5, -2.2, -391.5);
        giPlayerSetAng(1, 153.0);
        giPlayerSetPos(0, 165.7, -2.2, -388.2);
        giPlayerSetAng(0, 131.0);
        giPlayerSetPos(2, 274.4, -2.2, -350.8);
        giPlayerSetAng(2, 189.0);
        giPlayerSetPos(3, 224.9, -2.2, -347.5);
        giPlayerSetAng(3, 162.0);
        giWait(2.0);
        giFlashInBlack(1.5, true);
        giCameraRunSingle("006", false);
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("104M", true);
        giTalk("韩菱纱：身上……暖暖的？", "43499");
        giSetPortrait("104B", true);
        giTalk("韩菱纱：琼华派的道法真是厉害，我上山前动不动就头晕，后来练了紫英教的心法，也好了许多～", "43500");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("218A", false);
        giTalk("重光：……", "43501");
        giSetPortrait("217A", false);
        giTalk("青阳：……", "43502");
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：二位长老，看二位神色凝重，可是有什么不对？", "43503");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217A", false);
        giTalk("青阳：没什么……你们听好，天下至阴至寒之物虽不多，但也不少于五件，只是踪迹难觅，能寻到三件，已属不易。", "43504");
        giSetPortrait("217A", false);
        giTalk("青阳：我也只是听过一些传言，其中之一<colour red=255 green=187 blue=0 alpha=255>“光纪寒图”</colour><dc0>曾于数百年前在海边——如今的</dc0><colour red=255 green=187 blue=0 alpha=255>即墨</colour><dc0>现身，而</dc0><colour red=255 green=187 blue=0 alpha=255>“鲲鳞”</colour><dc0>则是北方大鱼的鳞片，那条鱼数年前曾游曳至</dc0><colour red=255 green=187 blue=0 alpha=255>巢湖</colour><dc0>附近，至于第三件，我却也不知是什么，只知道藏在传说中的</dc0><colour red=255 green=187 blue=0 alpha=255>炎帝神农洞</colour><dc0>。</dc0>", "43505");
        giSetPortrait("217A", false);
        giTalk("青阳：这些地方，我们不妨过去一探。", "43506");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("102H", true);
        giTalk("云天河：“我们”？……可是，我答应玄霄要帮他，我想自己试试……", "43507");
        giPlayerEndAction(0);
        giSetPortrait("218A", false);
        giTalk("重光：哼！有胆识，那便自己去吧。", "43508");
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：请二位长老见谅，天河言辞不当，但绝非拒绝长老好意……", "43509");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("217A", false);
        giTalk("青阳：……无妨，年轻人多些历练也是好事，如遇困难再来清风涧，我们必定相助。", "43510");
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：多谢长老！", "43511");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("218A", true);
        giTalk("重光：都去吧。", "43512");
        giWait(0.8);
        giPlayerWalkTo(0, 90.8, -2.3, -223.8, false);
        giPlayerWalkTo(1, 26.4, -2.2, -228.0, false);
        giPlayerWalkTo(2, 96.0, -2.2, -151.6, false);
        giPlayerWalkTo(3, 120.0, -2.6, -176.1, false);
        giWait(0.6);
        giCameraRunSingle("015", true);
        giWait(4.0);
        giSetPortrait("217A", true);
        giTalk("青阳：……年光飞逝，转眼又是十九年了。", "43513");
        giSetPortrait("218A", false);
        giTalk("重光：十九年、三十八年，亦或是昆仑、妖界之争再多少次地往复轮回，又有分别吗？世间除了“玄霄”，还有什么是与你我相关的？", "43514");
        giSetPortrait("217A", true);
        giTalk("青阳：……你说的对，他若能破冰而出，你我终可放下愧疚，安心离世了。", "43515");
        giSetPortrait("218A", false);
        giTalk("重光：…………", "43516");
        giWait(0.5);
        giFlashOutBlack(1.0, true, true);
        giIMMBegin();
        giPlayerSetPos(1, -107.3, -232.8, 389.6);
        giPlayerSetAng(1, 101.0);
        giPlayerSetPos(0, -110.8, -232.8, 465.1);
        giPlayerSetAng(0, 172.0);
        giPlayerSetPos(2, -52.8, -232.8, 469.9);
        giPlayerSetAng(2, 199.0);
        giPlayerSetPos(3, -18.9, -232.8, 396.9);
        giPlayerSetAng(3, 273.0);
        giIMMEnd();
        giScriptMusicStop(0, 2.5);
        giCameraRunSingle("022", true);
        giFlashInBlack(1.7, false);
        giWait(1.0);
        giCameraRunSingle("021", false);
        giSetPortrait("104M", false);
        giTalk("韩菱纱：那个重光长老，是不是已经修成仙身了？头发、眉毛虽是白的，脸却好年轻！", "43517");
        giPlayerDoAction(3, "C09", 1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：那只是他修炼的道法所至。两位长老的寿命自是比寻常人久上二十年、三十年，但也并非长生不老。", "43518");
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("104E", false);
        giTalk("韩菱纱：……无聊，我翻遍书库里所有典籍，也没见琼华派哪个人是修成仙身的……", "43519");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("105C", true);
        giTalk("慕容紫英：书库？典籍？", "43520");
        giPlayerDoAction(1, "J05", 1, false);
        giSetPortrait("104B", false);
        giTalk("韩菱纱：没、没有啦……我是说，我们什么时候动身去找那三样东西？", "43521");
        giPlayerEndAction(1);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("102B", true);
        giTalk("云天河：当然是马上就去！", "43522");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giPlayerSetDir(1, 17.0, false);
        giPlayerSetDir(2, 263.0, false);
        giPlayerSetDir(3, 305.0, true);
        giWait(0.5);
        giPlayerDoAction(2, "C07", -1, false);
        giSetPortrait("107A", true);
        giTalk("柳梦璃：那，要从哪一样开始找呢？", "43523");
        giPlayerUnHoldAct(2);
        giPlayerEndAction(2);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：既然都不简单，任何一样也没有差别了，不如就<colour red=255 green=187 blue=0 alpha=255>先从光纪寒图开始找吧</colour><dc0>。</dc0>", "43524");
        giWait(0.5);
        giPlayerSetDir(1, 91.0, false);
        giPlayerSetDir(0, 130.0, false);
        giPlayerSetDir(2, 155.0, false);
        giWait(0.8);
        giPlayerDoAction(1, "C07", 1, false);
        giSetPortrait("104A", false);
        giTalk("韩菱纱：好啊，去<colour red=255 green=187 blue=0 alpha=255>即墨</colour><dc0>，我可以带路，我认识～就在</dc0><colour red=255 green=187 blue=0 alpha=255>东北方、靠海的边上</colour><dc0>。</dc0>", "43525");
        giPlayerEndAction(1);
        giFlashOutBlack(1.5, true, true);
        giCameraRunSingle("001", true);
        giIMMBegin();
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerSetVisible(3, false);
        giSetNpcVisible("MN001", false);
        giSetNpcVisible("MN002", false);
        giSetObjectVisible("entrance0", true);
        giSetObjectVisible("entrance1", false);
        giIMMEnd();
        giCameraSetMode(0, true);
        global_mvar = 90100; // 0x00015FF4, 第二章 / 5-3-3.三寒器 / 前往即墨 / 三件寒器
        giSetObjectVisible("sound004", true);
        giPlayerUnLock();
        giFlashInBlack(1.5, true);
    }
}

void func2002()
{
    if (global_mvar == 121100 /* 第三章 / 7-5-2.往事 / 向长老求助 / 禁地生变 */)
    {
        giPlayerLock();
        giScriptMusicPlay("P26", 2, 0.0, 0.0);
        giSetObjectVisible("sound004", false);
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerSetPos(0, 151.7, -2.2, -337.2);
        giPlayerSetAng(0, 140.0);
        giPlayerSetPos(1, 195.4, -2.2, -293.4);
        giPlayerSetAng(1, 165.0);
        giPlayerSetPos(3, 268.2, -2.6, -312.7);
        giPlayerSetAng(3, 197.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giCameraPrepare("MC002");
        giCameraRunSingle("005", true);
        giNpcSetAng("MN002", 12.0);
        giNpcSetAng("MN001", 26.0);
        giIMMEnd();
        giFlashInBlack(1.5, true);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：青阳、重光二位长老，弟子慕容紫英求见！", "44665");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(1.0);
        giEffectPlayWithNPC("H_097", 1, "MN002");
        giNpcBlendIn("MN002", 1.5, false);
        giEffectPlayWithNPC("H_097", 1, "MN001");
        giNpcBlendIn("MN001", 1.5, true);
        giWait(0.5);
        giSetPortrait("217A", true);
        giTalk("青阳：已找齐了三件至阴至寒之物？", "44666");
        giWait(0.3);
        giPlayerDoAction(3, "C08", 1, false);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：……不错，弟子等已将三样东西交给师叔，他似乎也已破冰而出。", "44667");
        giPlayerEndAction(3);
        giNpcDoAction("MN001", "C08", 1, false);
        giSetPortrait("217A", true);
        giTalk("青阳：唔……如此甚好、如此甚好啊！", "44668");
        giWait(0.5);
        giSetPortrait("218A", false);
        giTalk("重光：今日来此，可是玄霄还有他事相求？", "44669");
        giCameraRunSingle("002", true);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101H", true);
        giTalk("云天河：长老！我想问你们，我爹和我娘当初真的是带着望舒剑逃走？才会害了大哥、不，害了玄霄，害他被冰封？！", "44670");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giNpcSetDir("MN001", 354.0, false);
        giNpcSetDir("MN002", 329.0, true);
        giSetPortrait("217A", false);
        giTalk("青阳：……！！", "44671");
        giWait(0.3);
        giSetPortrait("217A", false);
        giTalk("青阳：这些话，你从哪里听来的？！", "44672");
        giSetPortrait("101H", true);
        giTalk("云天河：是掌门告诉我的……", "44673");
        giSetPortrait("218A", false);
        giTalk("重光：岂有此理！夙瑶竟如此不知轻重！", "44674");
        giSetPortrait("101H", true);
        giTalk("云天河：长老……这都是真的吗？", "44675");
        giCameraRunSingle("003", false);
        giWait(0.3);
        giSetPortrait("217A", false);
        giTalk("青阳：……唉，孩子，你知道了又能如何呢？当年之事千头万绪，无论其中因果如何，你爹和你娘确实带走了望舒剑，此举令琼华派升仙功亏一篑，那些弟子的死伤也变得毫无价值啊……", "44676");
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：最悲惨之人，莫过于玄霄，他内息失调终致走火入魔，不得不被冰封……", "44677");
        giSetPortrait("101G", true);
        giTalk("云天河：这么说来，真的是我爹娘害了他……", "44678");
        giSetPortrait("218A", false);
        giTalk("重光：世事因果自有天意，十九年后，若不是你帮忙，玄霄又怎能破冰？", "44679");
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103F", true);
        giTalk("韩菱纱：……但是，就算掌门和玄霄想取回望舒剑，也不该骗我们啊！为什么不光明正大说出来呢？！", "44680");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerSetDir(3, 270.0, false);
        giNpcSetDir("MN001", 19.0, false);
        giNpcSetDir("MN002", 1.0, true);
        giWait(0.7);
        giSetPortrait("105C", true);
        giTalk("慕容紫英：菱纱！", "44681");
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：…………夙瑶嘛，她的资质原本也算得上出类拔萃，奈何老掌门的其他几位弟子更是万中选一之人……", "44682");
        giPlayerSetDir(3, 192.0, false);
        giSetPortrait("217A", false);
        giTalk("青阳：夙瑶虽十分刻苦，但若不是大弟子玄震死于十九年前的大战，夙玉、云天青出逃，而玄霄又被冰封，无论如何也轮不到她继任掌门之位。", "44683");
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：所以……她难免患得患失，任何事情都想思虑周全，她这么做，也有不得已的原因啊……", "44684");
        giSetPortrait("103F", true);
        giTalk("韩菱纱：有什么不得已的原因——", "44685");
        giSetPortrait("218A", false);
        giTalk("重光：够了！当年之事不必再多纠缠，许多事情也不会再有改变。你们若是没有其他事，便请回。", "44686");
        giSetPortrait("103D", true);
        giTalk("韩菱纱：可是……", "44687");
        giWait(0.4);
        giCameraRunSingle("001", true);
        giWait(0.5);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老且慢，我们尚有一事相求，如今妖界又临——", "44688");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("217A", false);
        giTalk("青阳：哦？掌门若要报十九年前之仇，应是准备多时了，不必我二人再出手了吧……", "44689");
        giSetPortrait("218A", false);
        giTalk("重光：不错，冰封玄霄，我与青阳心存愧疚，至于其他事，则不会理会。", "44690");
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：二位长老误会了，弟子所言，或许匪夷所思，却又千真万确……弟子有个朋友，不，弟子的师侄柳梦璃，她穿过妖界入口的结界，就此失去了踪影……", "44691");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giSetPortrait("217A", false);
        giTalk("青阳：嗯？！且把当时情形细细说来！", "44692");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：便让天河来说吧，是他亲眼所见……", "44693");
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giNpcSetAng("MN001", 353.0);
        giNpcSetAng("MN002", 324.0);
        giPlayerSetAng(1, 175.0);
        giCameraRunSingle("008", true);
        giIMMEnd();
        giWait(3.0);
        giFlashInBlack(1.0, true);
        giSetPortrait("217A", true);
        giTalk("青阳：奇怪……如此说来，人是不能穿过那结界的，柳梦璃却又毫发无伤，莫非……她是妖？", "44694");
        giWait(0.3);
        giNpcSetDir("MN002", 282.0, true);
        giWait(0.5);
        giSetPortrait("218A", false);
        giTalk("重光：不可能。她的灵力虽比常人高出许多，但若真是妖物，又怎能瞒过你我之眼？", "44695");
        giWait(0.5);
        giSetPortrait("217A", true);
        giTalk("青阳：如此就更奇了……", "44696");
        giWait(0.3);
        giCameraRunSingle("001", true);
        giWait(0.5);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：……看来二位长老也不知究竟是怎么一回事，我们多有打扰了……", "44697");
        giCameraRunSingle("004", false);
        giNpcSetDir("MN001", 359.0, false);
        giNpcSetDir("MN002", 340.0, true);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101H", true);
        giTalk("云天河：等等！长老，你们有没有办法让人穿过那个结界？要是梦璃一直不出来，我们就追进去找她！", "44698");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("101H", true);
        giTalk("云天河：琼华派说不定很快就要和妖界打起来了，她一直待在那里，不是很危险？！", "44699");
        giSetPortrait("218A", false);
        giTalk("重光：荒谬！人入妖界，岂不是如同羊入虎口？！ ", "44700");
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老，弟子知道这想法乃是异想天开，但弟子也一同请求，若是二位有此办法，请一定告诉我们！", "44701");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giPlayerDoAction(1, "C08", 1, false);
        giSetPortrait("103A", true);
        giTalk("韩菱纱：对！就算再难也要试一试！", "44702");
        giPlayerEndAction(1);
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：……你们，真的不怕？妖界可不是儿戏之地，人若闯入，说不定顷刻便会身首异处。", "44703");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老，您这么说就是有办法了？！", "44704");
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：……唉……这世上有种叫“翳影枝”的东西，用它就可以穿过大部分的结界，妖界的结界或许也可以……", "44705");
        giCameraRunSingle("002", true);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：真的吗？那个翳影枝要去哪里才能弄到呢？", "44706");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("217A", false);
        giTalk("青阳：翳影枝为鬼界之物，因为鬼卒几乎要去世间所有地方勾魂，自然也必须穿越某些结界，这翳影枝便由厉害的鬼卒随身携带。", "44707");
        giSetPortrait("103C", true);
        giTalk("韩菱纱：那我们就得找鬼卒抢过来啰？", "44708");
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217A", false);
        giTalk("青阳：不可能、不可能。先不说寻常人能否遇到鬼卒，有些鬼卒也比你们厉害不知多少倍，岂是轻易能够得手？", "44709");
        giSetPortrait("103C", true);
        giTalk("韩菱纱：这可怎么办？", "44710");
        giSetPortrait("217A", false);
        giTalk("青阳：……若是真的想要翳影枝，就只能去鬼界一闯。", "44711");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101C", true);
        giTalk("云天河：鬼界？是什么地方？", "44712");
        giPlayerEndAction(0);
        giSetPortrait("217A", false);
        giTalk("青阳：就是人们所说的阴间，群鬼聚集之地。翳影枝源于鬼界，到那里去找，自然能够找到。", "44713");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：可是自古阴阳相隔，生人想要进去阴间，必定是困难重重吧？", "44714");
        giNpcDoAction("MN001", "C08", 1, false);
        giSetPortrait("217A", false);
        giTalk("青阳：天地既有六界，则六界之间必有往来，从人界入鬼界的方法亦不在少数，最简单的一种，便是由凡间的鬼城酆都所进入，不过进的却是鬼界外围，你们若想取翳影枝，须得去无常殿，那就只有到不周山看看了。", "44715");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：不周山？可是传说在大荒之中、支撑天地的那座山？", "44716");
        giSetPortrait("217A", false);
        giTalk("青阳：不错，相传那里有进入幽冥之国、即是鬼界的入口，但究竟要如何开启，我也并不知晓。", "44717");
        giPlayerDoAction(0, "J18", 1, false);
        giSetPortrait("101J", true);
        giTalk("云天河：不管怎么样，都要去试试看！", "44718");
        giPlayerEndAction(0);
        giCameraRunSingle("009", true);
        giPlayerSetDir(3, 267.0, true);
        giWait(0.4);
        giSetPortrait("105C", true);
        giTalk("慕容紫英：我与你自然能去一试，但菱纱近来身体欠佳，还是不要去了……", "44719");
        giPlayerSetDir(0, 92.0, false);
        giPlayerSetDir(1, 119.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "J05", 1, false);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：我没关系的，不过就是有点累，睡一觉醒来什么都好了！", "44720");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraRunSingle("001", true);
        giSetPortrait("217A", false);
        giTalk("青阳：……我见这位姑娘确实气色不佳，最近……可是时常体虚畏寒？", "44721");
        giPlayerSetDir(0, 138.0, false);
        giPlayerSetDir(1, 165.0, false);
        giPlayerSetDir(3, 193.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "C08", 1, false);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：对啊，长老你怎么知道？", "44722");
        giPlayerEndAction(1);
        giWait(0.5);
        giNpcSetDir("MN001", 80.0, true);
        giWait(0.5);
        giSetPortrait("217A", true);
        giTalk("青阳：重光，我看……不如你将“红魄”送给这位姑娘吧？", "44723");
        giNpcSetDir("MN002", 286.0, true);
        giWait(0.4);
        giSetPortrait("218A", false);
        giTalk("重光：为何？", "44724");
        giWait(0.3);
        giSetPortrait("217A", true);
        giTalk("青阳：唉，你我留着那样东西，又哪里还有什么用处，不如送给她吧，就当是……", "44725");
        giWait(1.0);
        giSetPortrait("218A", false);
        giTalk("重光：不必多说。", "44726");
        giNpcSetDir("MN001", 13.0, true);
        giNpcSetDir("MN002", 315.0, true);
        giWait(1.0);
        giIMMBegin();
        giSetObjectVisible("Jeffect001", true);
        giSetObjectVisible("MO001", true);
        giIMMEnd();
        giWait(1.0);
        giPlayerWalkTo(1, 215.7, -2.2, -403.4, true);
        giCameraRunSingle("006", false);
        giPlayerSetAng(1, 166.0);
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103B", true);
        giTalk("韩菱纱：哇！这么盛的红光，还让人觉得暖暖的，这到底是什么好宝贝？", "44727");
        giWait(0.5);
        giSetPortrait("217A", false);
        giTalk("青阳：此乃红魄，是世间极难寻到的一种暖玉，当初羲和剑也有一部分是以此铸造。你将它配在胸口，体虚之象会好很多。", "44728");
        giWait(0.5);
        giIMMBegin();
        giSetObjectVisible("MO001", false);
        giSetObjectVisible("Jeffect001", false);
        giIMMEnd();
        giWait(0.6);
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.3);
        giAddProperty(3113, 1, true);
        giWait(2.3);
        giSetPortrait("103B", true);
        giTalk("韩菱纱：谢谢长老，你们真是好人！", "44729");
        giSetPortrait("217A", false);
        giTalk("青阳：……", "44730");
        giCameraRunSingle("007", true);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：多谢二位长老指点，弟子等这就去寻访不周山了。", "44731");
        giSetPortrait("217A", true);
        giTalk("青阳：……去吧，若真的无法可施，也不必勉强。", "44732");
        giPlayerDoAction(3, "J07", 1, true);
        giWait(0.5);
        giPlayerWalkTo(0, 90.8, -2.3, -223.8, false);
        giPlayerWalkTo(1, 26.4, -2.2, -228.0, false);
        giPlayerWalkTo(3, 120.0, -2.6, -176.1, false);
        giWait(1.5);
        giIMMBegin();
        giNpcSetAng("MN001", 348.0);
        giNpcSetAng("MN002", 329.0);
        giCameraRunSingle("008", true);
        giIMMEnd();
        giWait(1.5);
        giSetPortrait("218A", false);
        giTalk("重光：何必多管闲事？你让他们去不周山，岂不是凶多吉少？", "44733");
        giSetPortrait("217A", true);
        giTalk("青阳：就算我不说出那个办法，他们也不可能轻言放弃，只会自己乱闯，更加凶险。", "44734");
        giWait(0.5);
        giSetPortrait("218A", false);
        giTalk("重光：这么多年来，你还是老样子，对后辈总存拂照之念……当初捉拿云天青和夙玉时，若不是你心软，又怎会让他二人逃脱？造成今日局面？", "44735");
        giWait(0.5);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217A", true);
        giTalk("青阳：说我心软，你又何尝不是？不然你为何要传授那小姑娘心法，又为何愿意将红魄给她？", "44736");
        giWait(0.5);
        giSetPortrait("218A", false);
        giTalk("重光：……罢了，论口舌我向来不如你，但我心中明白，如今活于世上，我早已算不上一个好人，甚至连人都算不上，我们为赎罪而活，但是否又不断在犯下新的罪……", "44737");
        giWait(0.7);
        giSetPortrait("217A", true);
        giTalk("青阳：…………", "44738");
        giScriptMusicStop(0, 2.5);
        giWait(0.5);
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giPlayerSetPos(1, -106.4, -232.8, 408.9);
        giPlayerSetAng(1, 100.0);
        giPlayerSetPos(0, -89.0, -232.8, 484.5);
        giPlayerSetAng(0, 131.0);
        giPlayerSetPos(3, -19.9, -232.8, 420.1);
        giPlayerSetAng(3, 295.0);
        giIMMEnd();
        giCameraPrepare("MC001");
        giCameraRunSingle("022", true);
        giFlashInBlack(1.5, false);
        giWait(0.7);
        giCameraRunSingle("020", false);
        giWait(1.0);
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101C", true);
        giTalk("云天河：紫英，那个不周山，你知道在哪里吗？", "44739");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：我也只是听师公说起过大致所在，他曾去<colour red=255 green=187 blue=0 alpha=255>不周山</colour><dc0>寻找铸剑之材，总之我们先</dc0><colour red=255 green=187 blue=0 alpha=255>御剑往北方飞</colour><dc0>，应该能找到的。</dc0>", "44740");
        giSetPortrait("101G", true);
        giTalk("云天河：嗯……", "44741");
        giPlayerSetDir(1, 7.0, true);
        giWait(0.5);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：天河，你别心事重重的，事情总要一件件慢慢解决，烦恼再多也没用。你爹娘和玄霄就算有什么恩恩怨怨，但你毕竟帮过他，以后总有机会见面说清楚……", "44742");
        giPlayerSetDir(0, 170.0, true);
        giWait(0.5);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101E", true);
        giTalk("云天河：嗯……", "44743");
        giPlayerDoAction(1, "J14", -1, false);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：现在先想方法找梦璃，急的事先解决，你说对不对呢～", "44744");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("101E", true);
        giTalk("云天河：知道了……<colour red=255 green=187 blue=0 alpha=255>我们马上去不周山！</colour>", "44745");
        giPlayerEndAction(0);
        giFlashOutBlack(1.5, true, true);
        giPlayerSetAng(0, 13.0);
        giCameraRunSingle("001", true);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerSetVisible(3, false);
        giSetNpcVisible("MN001", false);
        giSetNpcVisible("MN002", false);
        giCameraSetMode(0, true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        global_mvar = 130100; // 0x0001FC34, 第三章 / 7-5-3.往事 / 不周山
        giSetObjectVisible("sound004", true);
        giPlayerUnLock();
        giFlashInBlack(1.5, true);
    }
}

void func2003()
{
    if (global_mvar == 160200 /* 第四章 / 9-3-2.君莫思归 / 再访长老 / 生离之痛 */)
    {
        giPlayerLock();
        giScriptMusicPlay("P34", 2, 2.5, 0.0);
        giSetObjectVisible("sound004", false);
        giFlashOutBlack(1.5, true, true);
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giPlayerSetPos(0, -53.8, -2.2, -251.5);
        giPlayerSetAng(0, 94.0);
        giPlayerSetPos(1, -17.1, -2.2, -176.1);
        giPlayerSetAng(1, 123.0);
        giPlayerSetPos(3, 9.2, -2.6, -218.3);
        giPlayerSetAng(3, 118.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giCameraPrepare("MC003");
        giCameraRunSingle("001", true);
        giFlashInBlack(1.5, false);
        giNpcSetEmotion("MN001", "217_3");
        giCameraRunSingle("004", false);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：呀——！那是……重光长老？！", "46237");
        giPlayerRunTo(3, 126.8, -2.2, -288.7, false);
        giWait(0.2);
        giPlayerRunTo(1, 107.0, -2.2, -234.0, false);
        giPlayerRunTo(0, 74.1, -2.2, -287.5, false);
        giPlayerEndMove(3);
        giPlayerSetAng(3, 118.0);
        giPlayerDoAction(3, "J03", -1, false);
        giPlayerEndMove(1);
        giPlayerSetDir(1, 123.0, false);
        giPlayerEndMove(0);
        giPlayerSetDir(0, 94.0, false);
        giSetPortrait("105D", true);
        giTalk("慕容紫英：长老！重光长老！！", "46238");
        giTalk("？？：…………重光他已西去了……", "46239");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giNpcSetPos("MN001", 218.8, -2.2, -397.8);
        giNpcSetAng("MN001", 331.0);
        giPlayerSetDir(0, 114.0, false);
        giPlayerSetDir(1, 140.0, false);
        giPlayerSetDir(3, 133.0, false);
        giCameraRunSingle("002", true);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：你、你是……？！怎么会……？", "46240");
        giSetPortrait("105D", true);
        giTalk("慕容紫英：……青阳……长老？", "46241");
        giCameraRunSingle("005", true);
        giPlayerSetPos(3, 117.4, -2.2, -266.8);
        giWait(0.3);
        giSetPortrait("217B", false);
        giTalk("青阳：不必惊惶，不过是功力尽散，看来垂老矣矣罢了。 ", "46242");
        giWait(1.0);
        giCameraRunSingle("006", true);
        giSetPortrait("105D", true);
        giTalk("慕容紫英：长老……到底、到底发生了什么事？为什么会这样？！", "46243");
        giSetPortrait("217B", false);
        giTalk("青阳：……玄霄才离开不久……咳、咳咳——", "46244");
        giWait(0.5);
        giPlayerDoAction(0, "J30", -1, false);
        giSetPortrait("101H", true);
        giTalk("云天河：玄霄！他！他来这里干什么？！", "46245");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("217B", false);
        giTalk("青阳：……紫英，你先将重光送去屋里吧，不能让他尸骨曝于此地。", "46246");
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105E", true);
        giTalk("慕容紫英：是，弟子遵命……", "46247");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giFlashOutBlack(1.5, true, true);
        giIMMBegin();
        giSetNpcVisible("MN002", false);
        giPlayerSetPos(0, 143.6, -2.2, -254.2);
        giPlayerSetAng(0, 140.0);
        giPlayerSetPos(1, 184.0, -2.2, -210.7);
        giPlayerSetAng(1, 160.0);
        giPlayerSetPos(3, 185.9, -2.2, -260.6);
        giPlayerSetAng(3, 153.0);
        giNpcSetPos("MN001", 221.2, -2.2, -350.7);
        giNpcSetAng("MN001", 345.0);
        giCameraRunSingle("007", true);
        giIMMEnd();
        giWait(2.0);
        giFlashInBlack(1.5, true);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老，是玄霄……杀了……重光长老？！", "46248");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：他来此，是为寻一本宗炼留下的手记。", "46249");
        giSetPortrait("105A", true);
        giTalk("慕容紫英：师公的手记？！", "46250");
        giWait(0.3);
        giCameraRunSingle("012", true);
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：不错，宗炼生前留下的数本手记，都记载着铸剑、养剑之秘术，如今大部分藏于琼华派五灵剑阁之中……", "46251");
        giSetPortrait("217B", false);
        giTalk("青阳：但其中有一本，却是连掌门都未曾得见……", "46252");
        giNpcDoAction("MN001", "J02", 1, false);
        giTalk("青阳：……咳咳……", "46253");
        giIMMBegin();
        giPlayerSetPos(3, 188.6, -2.2, -291.4);
        giPlayerSetAng(3, 143.0);
        giCameraRunSingle("015", false);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老！", "46254");
        giWait(0.5);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：……无碍。且听我讲完。", "46255");
        giSetPortrait("105E", true);
        giTalk("慕容紫英：是……", "46256");
        giWait(0.3);
        giCameraRunSingle("008", true);
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：宗炼如琼华派历代执剑长老那样，为铸剑耗费一生心血，尤以羲和、望舒双剑为甚。双剑穷吾派三代之力，至宗炼手中乃成，临当此世，再无一人比他更了解双剑种种。", "46257");
        giWait(0.5);
        giCameraRunSingle("009", false);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：玄霄担心手记中有不利于双剑之记载，他如今正是飞升之前的紧要关头，何况多年修行，与羲和剑早已密不可分，自然不愿手记落在他人之手。", "46258");
        giWait(0.5);
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：那后来呢？后来怎样？！", "46259");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("217B", false);
        giTalk("青阳：……人生一世，经历多少风浪起伏，但我和重光做梦也料不到，十九年后重逢玄霄，他周身炽烈无比，眉宇间尽是狂态煞气……这是入邪之兆、入邪之兆……", "46260");
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：我告诉玄霄，宗炼经历与妖界之战，早已万念俱灰，将手记毁去，他虽半信半疑，但也只得作罢。", "46261");
        giWait(0.3);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：如此……重光长老又怎会……", "46262");
        giWait(0.5);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：事不由人，就算玄霄已有去意，我和重光又怎能让他就此离开？", "46263");
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：我二人劝他放弃飞升之计，他如今心魔深种，照此行事终会酿成大祸。但玄霄一意孤行，早已听不进去，重光便先行发难，欲强夺他手中羲和剑……", "46264");
        giWait(0.3);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：双剑缺一不可，重光长老想要以此阻止飞升？", "46265");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(0.5);
        giCameraRunSingle("017", true);
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：不错……只是玄霄功力与十九年前不可同日而语，重光全力相拼也远不敌他……我欲助重光，运功过度，之后气息逆行经络、不可遏制，才会变得如此模样……", "46266");
        giWait(0.5);
        giCameraRunSingle("018", true);
        giWait(0.5);
        giSetPortrait("103E", true);
        giTalk("韩菱纱：长老……", "46267");
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：姑娘，你心中定然怪我和重光，早知望舒剑一事，却不肯说出……", "46268");
        giWait(0.3);
        giSetPortrait("217B", false);
        giTalk("青阳：我二人不敢奢望你原谅……昔日相助玄霄，望他破冰之后修身养性，哪里料到会有今日之局……凝冰诀与三寒器之力终也抵不过他的欲望……", "46269");
        giWait(0.5);
        giSetPortrait("101G", true);
        giTalk("云天河：……", "46270");
        giWait(0.5);
        giScriptMusicStop(0, 2.5);
        giScriptMusicPlay("P35", 2, 0.0, 0.0);
        giCameraRunSingle("019", false);
        giSetPortrait("217B", false);
        giTalk("青阳：如今说什么都已太迟，我与重光一错再错……虽不愿承认，但恐怕琼华派数代苦心，终将付诸流水，羲和、望舒双剑再如何冠绝天下，亦是镜花水月，一场虚空……", "46271");
        giSetPortrait("105D", true);
        giTalk("慕容紫英：……长老何出此言？", "46272");
        giWait(0.6);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：飞升成仙，虽是凡人所向，但成与不成，皆看天意。", "46273");
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：合玄霄、夙瑶之力，或能令双剑成为剑柱，然而即便琼华派升起，接近昆仑山上天光所在处，玄霄如此心魔深种，如何能脱去肉体凡胎、成为仙身？", "46274");
        giWait(0.5);
        giSetPortrait("105E", true);
        giTalk("慕容紫英：神农之言……善心身合成仙，私念难成仙身……", "46275");
        giWait(0.5);
        giSetPortrait("103H", true);
        giTalk("韩菱纱： （唉……梭罗树仙……）", "46276");
        giWait(0.5);
        giSetPortrait("217B", false);
        giTalk("青阳：如今只怕反成了逆天而行，后果不堪设想……", "46277");
        giSetPortrait("101H", true);
        giTalk("云天河：意思是说，玄霄……他会死？", "46278");
        giWait(0.5);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", false);
        giTalk("青阳：死……或是堕入邪道、永不超生。", "46279");
        giSetPortrait("101D", true);
        giTalk("云天河：……！！", "46280");
        giWait(0.3);
        giSetPortrait("105A", true);
        giTalk("慕容紫英：长老，难道就没有其他办法阻止琼华派飞升吗？弟子等前来，也正是为了此事！", "46281");
        giSetPortrait("217B", false);
        giTalk("青阳：办法……那唯一的一线希望，却要问一问云天河了。", "46282");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetPos(1, 193.5, -2.2, -232.3);
        giPlayerSetAng(1, 237.0);
        giPlayerSetPos(3, 202.8, -2.2, -279.8);
        giPlayerSetAng(3, 258.0);
        giNpcSetPos("MN001", 178.6, -2.2, -362.0);
        giNpcSetAng("MN001", 314.0);
        giPlayerSetAng(0, 166.0);
        giCameraRunSingle("021", true);
        giIMMEnd();
        giWait(0.3);
        giSetPortrait("101D", false);
        giTalk("云天河：问我……？", "46283");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：天青生前，可曾交付给你一本手记？", "46284");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101C", false);
        giTalk("云天河：……爹是留了些书给我，可他什么也没交代……", "46285");
        giPlayerEndAction(0);
        giSetPortrait("217B", true);
        giTalk("青阳：唉，你再想想吧，那些书中或许就有宗炼的手记——", "46286");
        giPlayerSetDir(3, 190.0, false);
        giPlayerSetDir(1, 196.0, true);
        giWait(0.6);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：长老，弟子不明……师公的手记，怎会在云前辈那里……", "46287");
        giWait(0.3);
        giIMMBegin();
        giNpcSetAng("MN001", 2.0);
        giCameraRunSingle("022", true);
        giIMMEnd();
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：……当年我率众弟子捉拿逃出门派的天青与夙玉，几次交手，却总因一时心软，放他们离去……", "46288");
        giSetPortrait("217B", true);
        giTalk("青阳：事后想来，心中悔恨交织，若是将夙玉带回门派中，玄霄万万不会走火入魔，亦不会落到被冰封禁地的下场……", "46289");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：……与重光隐居之后，我不时下山探访，想要找回夙玉。", "46290");
        giSetPortrait("217B", true);
        giTalk("青阳：然而辗转数年，当我在青鸾峰寻到天青时，夙玉却已过世了，那一刻，我自觉想救玄霄已是无望……天下之大，要去何处找一个与夙玉命格体质相合的女子，更毋论令其修习仙术，调合玄霄的阳炎之力……", "46291");
        giIMMBegin();
        giPlayerSetPos(0, 143.6, -2.2, -254.2);
        giPlayerSetAng(0, 171.0);
        giPlayerSetPos(1, 230.5, -2.2, -271.2);
        giPlayerSetAng(1, 225.0);
        giPlayerSetPos(3, 180.4, -2.2, -276.4);
        giPlayerSetAng(3, 196.0);
        giIMMEnd();
        giCameraRunSingle("024", true);
        giPlayerDoAction(0, "J04", -1, false);
        giSetPortrait("101G", false);
        giTalk("云天河：……爹，就是那个时候知道了玄霄被冰封……", "46292");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giNpcSetAng("MN001", 357.0);
        giCameraRunSingle("023", true);
        giWait(0.3);
        giNpcDoAction("MN001", "C08", 1, false);
        giSetPortrait("217B", true);
        giTalk("青阳：天青他得知玄霄被囚，心中亦是痛苦不堪，而当时他体内的寒冰之气已不可遏制，命不久矣……我又如何责怪于他？", "46293");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：或许……我与重光、宗炼已隐约生念，造就双剑、和妖界之争，是否步步皆错……所以宗炼才会半生都在找寻一种方法，如何在宿主力量失控时，阻止他们继续使用双剑……", "46294");
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105D", false);
        giTalk("慕容紫英：……！师公……那个办法，他老人家找到了吗？！", "46295");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", true);
        giTalk("青阳：他离世前并未再提，只将关于双剑的手记托付于我，叮嘱万万不可轻易示人，而我不愿琼华派任何人再得到这本手记，遂将其交付给了天青……", "46296");
        giWait(0.3);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：长老的意思是，若能寻到师公的手记，其中或有记载阻止琼华派飞升之法？", "46297");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：……或许……有此一线希望！", "46298");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101E", false);
        giTalk("云天河：可是……爹根本没提过什么手记啊……我们要不要回青鸾峰找找？", "46299");
        giPlayerEndAction(0);
        giCameraRunSingle("025", false);
        giSetPortrait("217B", true);
        giTalk("青阳：……我恳求诸位，若是寻到办法，定要阻止玄霄和夙瑶。一是为韩姑娘的性命，我和重光大错铸成，悔之已晚……", "46300");
        giWait(0.3);
        giSetPortrait("103H", false);
        giTalk("韩菱纱：青阳长老……", "46301");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：二是为了琼华派门人的安危，逆天而行、人不胜天……尤其是玄霄，他如魔附身，心智早已不受控制，亦是身不由己，十九年前无法救他，十九年后竟还要见他入邪疯魔……", "46302");
        giPlayerDoAction(0, "J04", -1, false);
        giSetPortrait("101G", false);
        giTalk("云天河：……身不由己……还能救他吗？他早已经不是当初的玄霄了……", "46303");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giNpcDoAction("MN001", "C09", 1, false);
        giSetPortrait("217B", true);
        giTalk("青阳：……不尽然，他的心中或许还存着一丝善念……", "46304");
        giWait(0.5);
        giSetPortrait("101H", false);
        giTalk("云天河：真的？！", "46305");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：玄霄未取我性命，应是念了昔日的拂照之恩……", "46306");
        giPlayerDoAction(0, "C07", -1, false);
        giSetPortrait("101H", false);
        giTalk("云天河：这么说……他还有救？！还能变回以前的玄霄……？", "46307");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：长老，弟子尚有一事未明……纵然师叔已经走火入魔，掌门却仍是神智清明，琼华派飞升，凶吉未卜，掌门难道不会就此罢手？", "46308");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：……夙瑶素来好强，自是要倾尽全力，达成吾派数代以来的宏愿，她身在局中，怎能轻易放下执念？何况玄霄也不可能让她罢手……", "46309");
        giWait(0.3);
        giSetPortrait("217B", true);
        giTalk("青阳：且夙瑶并非望舒之主，勉力施为，定要玄霄相助才能使用望舒剑，又不得不臣服于他……如今整个门派，怕是系于玄霄一念之间……", "46310");
        giWait(0.5);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：…………", "46311");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：你们去吧，以寻到手记为先……", "46312");
        giWait(0.5);
        giSetPortrait("217B", true);
        giTalk("青阳：玄霄、夙瑶升仙之前不欲受扰，已在琼华派外做成结界，任何人都不能靠近，结界撤去之时，便是剑柱大成之日！", "46313");
        giWait(0.3);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：时间刻不容缓，弟子等这便赶去青鸾峰了……", "46314");
        giWait(0.6);
        giSetPortrait("217B", true);
        giTalk("青阳：去吧……我功力已散，阳寿将尽，只求在此静伴老友片刻……", "46315");
        giNpcWalkTo("MN001", 213.2, -2.2, -453.7, false);
        giWait(1.0);
        giFlashOutBlack(1.0, true, true);
        giScriptMusicStop(0, 2.5);
        giScriptMusicPlay("P26", 2, 2.5, 0.0);
        giIMMBegin();
        giPlayerSetPos(0, 1510.7, -298.2, 408.5);
        giPlayerSetAng(0, 242.0);
        giPlayerSetPos(1, 1464.9, -298.1, 390.6);
        giPlayerSetAng(1, 152.0);
        giPlayerSetPos(3, 1517.2, -298.2, 331.4);
        giPlayerSetAng(3, 333.0);
        giIMMEnd();
        giCameraRunSingle("035", true);
        giWait(2.5);
        giPlayerDoAction(1, "J04", -1, false);
        giFlashInBlack(2.5, false);
        giCameraRunSingle("032", false);
        giWait(1.5);
        giSetPortrait("103E", true);
        giTalk("韩菱纱：……青阳长老……留他一个人在这里，真的不要紧吗？", "46316");
        giSetPortrait("105A", false);
        giTalk("慕容紫英：一切就按长老吩咐的去做吧。", "46317");
        giSetPortrait("103H", true);
        giTalk("韩菱纱：……他和重光长老，都是可怜的人……十九年来没有一点安心，现在……现在又…………", "46318");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.3);
        giSetPortrait("105B", false);
        giTalk("慕容紫英：已经发生的事，不能再改变……但若是我们能阻止师叔，对两位长老，甚至是对师公来说，定然是莫大的欣慰……", "46319");
        giWait(0.3);
        giCameraRunSingle("033", true);
        giWait(0.6);
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("101J", true);
        giTalk("云天河：对，至少还有那本手记在。", "46320");
        giSetPortrait("101H", true);
        giTalk("云天河：菱纱，只要能救你，还有……让玄霄变回以前的玄霄……哪怕是一点点希望，我们都要去试！", "46321");
        giWait(0.6);
        giSetPortrait("105B", true);
        giTalk("慕容紫英：不错，师公一生铸剑无数，技艺之精湛、所知之广博，非我能望其项背，他的手记中一定写有十分重要的东西。", "46322");
        giPlayerDoAction(1, "C08", 1, false);
        giSetPortrait("103A", false);
        giTalk("韩菱纱：嗯……", "46323");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.3);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101E", true);
        giTalk("云天河：…………呃，我……有件事…………", "46324");
        giPlayerSetDir(1, 79.0, false);
        giPlayerSetDir(3, 345.0, true);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：什么？", "46325");
        giWait(0.6);
        giSetPortrait("101E", true);
        giTalk("云天河：我想起……爹的书……我烤肉时生火图方便……都……都烧得差不多了…………", "46326");
        giWait(0.3);
        giSetPortrait("105D", true);
        giTalk("慕容紫英：………………", "46327");
        giSetPortrait("103D", false);
        giTalk("韩菱纱：………………", "46328");
        giCameraRunSingle("039", true);
        giWait(0.3);
        giPlayerDoAction(1, "J01", -1, false);
        giSetPortrait("103I", false);
        giTalk("韩菱纱：你！你这傻瓜！大傻瓜！那种东西也能随便乱烧吗？！", "46329");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101E", true);
        giTalk("云天河：话是这么说没错，但是……那个时候，我又不知道它很重要……", "46330");
        giPlayerUnHoldAct(0);
        giPlayerEndAction(0);
        giCameraRunSingle("038", true);
        giPlayerDoAction(1, "J15", -1, false);
        giSetPortrait("103I", false);
        giTalk("韩菱纱：还敢说！真要被你气死！可恶可恶可恶！", "46331");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("101E", true);
        giTalk("云天河：……对、对不起……", "46332");
        giWait(0.3);
        giIMMBegin();
        giPlayerSetAng(0, 252.0);
        giCameraRunSingle("040", true);
        giIMMEnd();
        giWait(0.5);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105E", true);
        giTalk("慕容紫英：天河既然没什么印象，是不是真的烧了，也未可知，总之<colour red=255 green=187 blue=0 alpha=255>先去青鸾峰看看再说</colour><dc0>。</dc0>", "46333");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giPlayerSetDir(0, 179.0, true);
        giWait(0.5);
        giPlayerDoAction(0, "C08", 1, false);
        giSetPortrait("101B", false);
        giTalk("云天河：对对对！看看再说、看看再说……说不定还在呢……", "46334");
        giSetPortrait("103E", true);
        giTalk("韩菱纱：…………哼，走啦，猪头……真拿你没办法……", "46335");
        giPlayerSetDir(0, 254.0, true);
        giWait(0.3);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101E", false);
        giTalk("云天河：……", "46336");
        giPlayerDoAction(3, "C09", 1, false);
        giWait(0.6);
        giFlashOutBlack(1.5, true, true);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerSetVisible(3, false);
        giSetNpcVisible("MN001", false);
        giSetNpcVisible("MN002", false);
        giNpcResetEmotion("MN001");
        giCameraWait();
        giPlayerSetAng(0, 350.0);
        giCameraSetMode(0, true);
        giCameraSeekToPlayer();
        giFlushTailYAngle();
        global_mvar = 160400; // 0x00027290, 第四章 / 9-4-1.步虚词终 / 重回青鸾峰
        giPlayerUnLock();
        giSetObjectVisible("sound004", true);
        giScriptMusicStop(1, 2.5);
        giFlashInBlack(1.5, true);
    }
}
