// Structured PAL4 reconstruction for Q12.csb
// Only simple if / if-else candidates backed by CFG evidence are folded.

void Q12_Q12_init()
{
    if (global_mvar != 131001)
    {
        giArenaReadyRestore();
    }
    else
    {
        func2001();
    }
}

void func2001()
{
    if (global_mvar == 131001)
    {
        giPlayerLock();
        giCameraSetCollide(false);
        giCameraAutoSeek(false);
        giIMMBegin();
        giPlayerCurrentSetVisible(false);
        giPlayerSetPos(0, -26.1, -0.9, -8.0);
        giPlayerSetPos(1, -7.2, 3.5, -46.0);
        giPlayerSetPos(3, 14.7, 3.4, 23.6);
        giPlayerSetAng(0, 268.0);
        giPlayerSetAng(1, 275.0);
        giPlayerSetAng(3, 322.0);
        giPlayerSetVisible(0, true);
        giPlayerSetVisible(1, true);
        giPlayerSetVisible(3, true);
        giSetNpcVisible("MN001", true);
        giCameraPrepare("MC001");
        giCameraRunSingle("001", true);
        giIMMEnd();
        giArenaReady();
        gi2DSoundPlay("WB033", -1);
        giFlashInBlack(3.5, false);
        giWait(0.8);
        giCameraRunSingle("002", true);
        giWait(0.5);
        giPlayerSetDir(1, 329.0, false);
        giCameraRunSingle("003", true);
        giWait(1.2);
        giSetPortrait("103C", true);
        giTalk("韩菱纱：……这个划船的人好奇怪，一句话都不说，却愿意帮我们，应该是壬癸的朋友吧？", "45084");
        giWait(0.5);
        giPlayerSetDir(0, 152.0, true);
        giWait(0.3);
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101C", false);
        giTalk("云天河：不知道……", "45085");
        giPlayerEndAction(0);
        giCameraRunSingle("004", true);
        giWait(0.8);
        giSetPortrait("105E", true);
        giTalk("慕容紫英：……", "45086");
        giWait(0.7);
        giPlayerSetDir(0, 44.0, true);
        giWait(0.5);
        giSetPortrait("101J", true);
        giTalk("云天河：紫英，你在想什么？是不是……很在意梦璃是妖？", "45087");
        giWait(0.5);
        giPlayerDoAction(1, "J15", -1, false);
        giSetPortrait("103E", true);
        giTalk("韩菱纱：（天呐！笨死了，哪壶不开提哪壶！）", "45088");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giIMMBegin();
        giPlayerSetPos(1, -0.6, 0.6, -33.0);
        giPlayerSetAng(1, 19.0);
        giPlayerSetPos(3, 26.8, 3.5, 24.1);
        giPlayerSetAng(3, 322.0);
        giCameraRunSingle("005", true);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：……想不到……我竟与一个妖相处了这么久，而且毫无所觉……", "45089");
        giPlayerDoAction(0, "J14", 1, false);
        giSetPortrait("101H", true);
        giTalk("云天河：可是，在意这种事根本没啥用吧？我爹说的话，你不也听到了？", "45090");
        giPlayerEndAction(0);
        giWait(0.5);
        giPlayerDoAction(3, "C09", 1, true);
        giWait(0.3);
        giPlayerSetDir(3, 242.0, true);
        giWait(0.5);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：……我不知道……该怎么做才是对的，就像那个时候向掌门要水灵珠，似乎是我错了，但究竟错在哪里，却一点都不明白……", "45091");
        giWait(0.5);
        giPlayerDoAction(0, "J05", 1, false);
        giSetPortrait("101H", true);
        giTalk("云天河：不一样，那个时候根本是小气掌门的错吧！", "45092");
        giSetPortrait("101H", true);
        giTalk("云天河：我觉得……要是你不知道该怎么办，干脆先什么都别想了，一切等我们找到梦璃再说。", "45093");
        giWait(0.5);
        giPlayerDoAction(3, "C08", 1, false);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：嗯……", "45094");
        giWait(0.5);
        giSetObjectVisible("jeffect001", true);
        giCameraRunSingle("006", true);
        giWait(0.8);
        giPlayerSetDir(1, 277.0, true);
        giWait(0.5);
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103A", true);
        giTalk("韩菱纱：你们看！那边有亮光，是不是快到人间了？", "45095");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.3);
        giPlayerSetDir(0, 254.0, false);
        giWait(3.0);
        giCameraRunSingle("007", true);
        giWait(1.2);
        giPlayerSetDir(1, 91.0, true);
        giWait(0.8);
        giPlayerDoAction(1, "J13", -1, false);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：（咦？这个人……）", "45096");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giCameraWait();
        giWait(0.5);
        giPlayerSetDir(3, 122.0, false);
        giPlayerSetDir(0, 98.0, false);
        giWait(1.2);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：多谢相助，我等感激不尽，能否告知尊驾姓名？", "45097");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(1.2);
        giSetPortrait("228A", true);
        giTalk("划船人：……", "45098");
        giWait(1.0);
        giSetPortrait("105A", false);
        giTalk("慕容紫英：……如此，是我冒昧了。", "45099");
        giWait(0.5);
        giSetPortrait("101B", false);
        giTalk("云天河：他不愿意说就算了吧，大不了我们也帮他多烧点那个什么纸钱。", "45100");
        giWait(0.5);
        giCameraRunSingle("008", true);
        giWait(0.8);
        giPlayerWalkTo(1, 35.1, 0.6, -28.6, true);
        giWait(0.3);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：你……把头抬起来，让我看一看好吗？", "45101");
        giWait(0.5);
        giPlayerSetDir(3, 200.0, true);
        giWait(0.5);
        giSetPortrait("105C", false);
        giTalk("慕容紫英：菱纱？", "45102");
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("划船人：……", "45103");
        giCameraRunSingle("009", false);
        giSetPortrait("103I", false);
        giTalk("韩菱纱：你、你不敢吗？！你到底是谁？", "45104");
        giSetPortrait("228A", true);
        giTalk("划船人：…………", "45105");
        giWait(0.5);
        giPlayerSetDir(3, 116.0, true);
        giWait(0.3);
        giSetPortrait("103I", false);
        giTalk("韩菱纱：……", "45106");
        giWait(1.0);
        giScriptMusicPlay("P35", 2, 2.5, 2.5);
        giSetPortrait("228A", true);
        giTalk("划船人：……唉，丫头，你还是这么精灵，真拿你没办法……", "45107");
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103D", false);
        giTalk("韩菱纱：伯父，真的是你？！怎么可能？！", "45108");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giSetPortrait("105D", false);
        giTalk("慕容紫英：……！", "45109");
        giWait(0.5);
        giPlayerSetEmotion(1, "103_jy1");
        giCameraRunSingle("010", true);
        giWait(0.8);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：伯父，为什么你会在这里？为什么你要装作不认识我？要不是、要不是我认出你的轮廓……", "45110");
        giWait(0.5);
        giCameraRunSingle("011", true);
        giWait(0.8);
        giSetPortrait("228A", true);
        giTalk("韩北旷：丫头，你就当作没看见伯父好不好？", "45111");
        giWait(0.3);
        giPlayerDoAction(1, "J15", -1, false);
        giSetPortrait("103E", false);
        giTalk("韩菱纱：不好！我明明看见了！你都不知道，我有多想你，在转轮镜台的时候，我以为你已经转世去了，所以才不出现……", "45112");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("228A", true);
        giTalk("韩北旷：傻丫头，我要是转世，今天不就救不了你了？ ", "45113");
        giWait(0.5);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：……伯父，你说什么救不了我？为什么你会在这里划船？", "45114");
        giWait(0.5);
        giCameraRunSingle("012", false);
        giSetPortrait("228A", true);
        giTalk("韩北旷：……不止是我……几乎所有韩家人，死后都会在鬼界做苦役……我便是负责摆渡这青竹船，必要时往来人鬼两界……", "45115");
        giSetPortrait("103D", false);
        giTalk("韩菱纱：苦役？那是什么？他们怎么能让你做这种事呢？！", "45116");
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("韩北旷：…………", "45117");
        giSetPortrait("103I", false);
        giTalk("韩菱纱：伯父，你说嘛！告诉我好不好？", "45118");
        giWait(0.5);
        giCameraRunSingle("013", true);
        giWait(1.2);
        giSetPortrait("228A", false);
        giTalk("韩北旷：丫头，我刚才不想与你相认，就是在犹豫要不要告诉你一些事，对你来讲，现在就知道这些，未免过于沉重了……", "45119");
        giWait(0.5);
        giCameraRunSingle("014", false);
        giSetPortrait("103I", true);
        giTalk("韩菱纱：伯父，到底是怎么回事？！我要知道！", "45120");
        giWait(0.8);
        giSetPortrait("228A", false);
        giTalk("韩北旷：唉……韩氏世代盗墓，总以为人已入土，墓中器皿当可拿来救助活人，但如今你来了鬼界，应该知晓，鬼也如活人一般，有自己的感情、自己的种种思念……", "45121");
        giSetPortrait("228A", false);
        giTalk("韩北旷：我们一族惊扰死者，不仅生死薄上阳寿短暂，很多都只活到二三十岁，即便死后，也一样要做苦役来赎罪，待到罪孽偿清，才可再入轮回了……", "45122");
        giWait(0.5);
        giCameraRunSingle("015", true);
        giWait(0.1);
        giPlayerDoAction(1, "J02", -1, false);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：竟然、竟然这样……", "45123");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.7);
        giPlayerSetEmotion(1, "103_bs");
        giSetPortrait("103H", true);
        giTalk("韩菱纱：也就是说……我一直在找的长生之法，根本没有用？不管我怎么努力，也不能让族人活得更长久一些……", "45124");
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：丫头，我知道你很努力了，但是有些东西，冥冥之中自有安排，不是你一个人能够争得过……", "45125");
        giWait(0.7);
        giSetPortrait("103H", true);
        giTalk("韩菱纱：那，爹和娘呢？他们在哪？", "45126");
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：……自然也在鬼界的其他地方赎罪。", "45127");
        giWait(0.6);
        giSetPortrait("103H", true);
        giTalk("韩菱纱：……", "45128");
        giWait(0.5);
        giIMMBegin();
        giPlayerSetPos(0, -20.2, -0.9, -2.3);
        giPlayerSetPos(1, 20.3, 1.4, -36.4);
        giCameraRunSingle("016", true);
        giIMMEnd();
        giSetPortrait("228A", true);
        giTalk("韩北旷：丫头，你老实告诉我，你是不是一直很气自己爹娘？觉得他们待你不好？", "45129");
        giWait(0.5);
        giSetPortrait("103H", false);
        giTalk("韩菱纱：我……", "45130");
        giWait(0.5);
        giPlayerDoAction(1, "C08", 1, true);
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("韩北旷：唉，他们啊，知道自己多半命不长久，所以才故意对你冷淡，就是怕你依赖惯了，万一双亲离世，会太伤心，这世上又哪有爹娘不喜欢自己的孩子呢？", "45131");
        giWait(0.5);
        giSetPortrait("103D", false);
        giTalk("韩菱纱：伯父，你说的、都是真的吗？！", "45132");
        giWait(0.5);
        giCameraRunSingle("017", false);
        giSetPortrait("228A", true);
        giTalk("韩北旷：当然是真的！记得你还小的时候，你爹每天晚上非要在床边看你睡着了，他才肯睡，他就是有股傻劲，总觉得不多看几眼，多唤你几声名字，以后就没机会了…… ", "45133");
        giWait(0.5);
        giPlayerDoAction(1, "C09", 1, false);
        giWait(0.3);
        giSetPortrait("103H", false);
        giTalk("韩菱纱：……真是个傻爹爹，还有娘，也好笨！", "45134");
        giWait(0.3);
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103H", false);
        giTalk("韩菱纱：人活一辈子，本来就够短暂了，他们还要在意这在意那，害我伤心了好多年……", "45135");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giSetPortrait("228A", true);
        giTalk("韩北旷：……丫头……你真的长大了，看事情有自己的想法了……", "45136");
        giSetPortrait("228A", true);
        giTalk("韩北旷：……似乎、也结识了很好的朋友……旁边这两位都是吧？", "45137");
        giWait(0.5);
        giPlayerSetEmotion(1, "103_zc");
        giCameraRunSingle("018", true);
        giWait(0.8);
        giPlayerDoAction(0, "J14", 1, false);
        giWait(0.3);
        giSetPortrait("101B", false);
        giTalk("云天河：对啊，我和菱纱是很要好的朋友，呵呵。", "45138");
        giPlayerEndAction(0);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105B", false);
        giTalk("慕容紫英：晚辈慕容紫英，刚才多有失礼了。", "45139");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(0.5);
        giIMMBegin();
        giPlayerSetVisible(1, false);
        giNpcSetAng("MN001", 304.0);
        giCameraRunSingle("019", true);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("228A", false);
        giTalk("韩北旷：慕容？难道是大燕国的遗族？", "45140");
        giWait(0.5);
        giPlayerDoAction(3, "C07", -1, false);
        giSetPortrait("105D", true);
        giTalk("慕容紫英：……！前辈如何得知？", "45141");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：唉，我也是脑中灵光一闪而过，想到很久以前有一对夫妇，前去轮回井投胎……眉目间和你很有几分神似……而且慕容这个姓可不多见，曾是燕国的大家之姓……", "45142");
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：你爹……是不是叫慕容承？", "45143");
        giWait(0.5);
        giSetPortrait("105D", true);
        giTalk("慕容紫英：……正是家父。", "45144");
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：那就没错了。", "45145");
        giWait(0.5);
        giCameraRunSingle("020", true);
        giIMMBegin();
        giPlayerSetVisible(1, true);
        giPlayerSetAng(1, 21.0);
        giPlayerSetAng(0, 68.0);
        giIMMEnd();
        giWait(0.8);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：…………原来……原来爹和娘都已经过世……这么久了……", "45146");
        giWait(0.8);
        giSetPortrait("228A", true);
        giTalk("韩北旷：你也不用太过伤心，你爹和你娘神色平和，生前应该是过得很安泰。", "45147");
        giSetPortrait("228A", true);
        giTalk("韩北旷：只是他们似乎有些遗憾，没能在死之前再见自己的小儿子一面，说是因为那孩子年幼时体弱，家里不但请来道士替他批命取名，更是将他送去了仙山上修行，但愿他能活得长命百岁。", "45148");
        giWait(1.0);
        giSetPortrait("105E", false);
        giTalk("慕容紫英：……爹、娘…………", "45149");
        giWait(0.8);
        giCameraRunSingle("021", true);
        giWait(1.6);
        giSetPortrait("103H", false);
        giTalk("韩菱纱：（紫英……）", "45150");
        giWait(1.0);
        giIMMBegin();
        giNpcSetAng("MN001", 300.0);
        giCameraRunSingle("022", true);
        giIMMEnd();
        giWait(0.7);
        giSetPortrait("228A", false);
        giTalk("韩北旷：鬼界有种说法，叫作生前种种隔世抛，与其一直挂念，不如在心里希望过世的亲人朋友，投胎以后能够一生顺遂……", "45151");
        giWait(1.0);
        giPlayerDoAction(3, "J07", -1, false);
        giSetPortrait("105E", true);
        giTalk("慕容紫英：……多谢前辈指点，晚辈……晚辈都明白……", "45152");
        giPlayerUnHoldAct(3);
        giPlayerEndAction(3);
        giWait(0.5);
        giPlayerDoAction(1, "J04", -1, false);
        giSetPortrait("103H", true);
        giTalk("韩菱纱：（哪有那么容易看透，紫英你又在逞强了……不然为什么要露出那种悲伤的神情……）", "45153");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giSetPortrait("228A", false);
        giTalk("韩北旷：唉，是我该谢谢你们，一直照顾我家丫头。", "45154");
        giWait(0.5);
        giPlayerSetDir(1, 93.0, false);
        giIMMBegin();
        giPlayerSetAng(0, 106.0);
        giNpcSetAng("MN001", 266.0);
        giCameraRunSingle("023", true);
        giIMMEnd();
        giWait(0.8);
        giPlayerDoAction(1, "J05", 1, false);
        giSetPortrait("103E", false);
        giTalk("韩菱纱：伯父，你说什么呢……旁边这个倒也罢了，后面的那个啊，可是我一直在照顾他呀！", "45155");
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("韩北旷：哈哈，不管怎样，伯父今天能见到你，觉得很高兴……", "45156");
        giWait(0.5);
        giPlayerDoAction(1, "C07", -1, false);
        giSetPortrait("103E", false);
        giTalk("韩菱纱：我也是……伯父，你先别走，再多和我说些话好不好？", "45157");
        giPlayerUnHoldAct(1);
        giPlayerEndAction(1);
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("韩北旷：……时候差不多，你们该回阳间了。", "45158");
        giWait(0.5);
        giSetPortrait("103C", false);
        giTalk("韩菱纱：伯父，我会告诉族人，让他们别再去惊扰死者了……不过有机会的话，我还是要去找长生之法。", "45159");
        giWait(0.5);
        giSetPortrait("228A", true);
        giTalk("韩北旷：丫头，别总那样辛苦，多为自己想想吧。", "45160");
        giCameraRunSingle("024", false);
        giWait(0.5);
        giNpcBlendOut("MN001", 6.5, false);
        giSetPortrait("228A", true);
        giTalk("韩北旷：你出落得这么漂亮，记得找个好相公嫁了！我看你身后两个都不错啊！哈哈！", "45161");
        giWait(0.5);
        giSetPortrait("103D", true);
        giTalk("韩菱纱：伯父！", "45162");
        giWait(1.0);
        giFlashOutWhite(2.0, true, true);
        giCameraRunSingle("023", true);
        giIMMBegin();
        giPlayerSetVisible(0, false);
        giPlayerSetVisible(1, false);
        giPlayerSetVisible(2, false);
        giPlayerCurrentSetVisible(true);
        giIMMEnd();
        global_mvar = 131100; // 0x0002001C
        gi2DSoundStop();
        giArenaLoad("Q13", "Q13", "", true);
    }
}
